import { FormEvent, useEffect, useMemo, useState } from 'react'
import { Building2, ImagePlus, Pencil, Plus, X } from 'lucide-react'
import { ApiError, apiBlobRequest, apiRequest } from '../../api/client'
import { Partner, PartnerForm, blankPartner } from './types'

type Props={partners:Partner[];canManage:boolean;onReload:()=>Promise<void>;onSuccess:(text:string)=>void}

export function MaintenancePartners({partners,canManage,onReload,onSuccess}:Props){
  const [query,setQuery]=useState(''),[modal,setModal]=useState(false),[editing,setEditing]=useState<Partner|null>(null),[form,setForm]=useState<PartnerForm>(blankPartner()),[logo,setLogo]=useState<File|null>(null),[preview,setPreview]=useState<string|null>(null),[saving,setSaving]=useState(false),[error,setError]=useState('')
  const visible=useMemo(()=>{const term=query.trim().toLowerCase();return partners.filter(p=>!term||`${p.code} ${p.name} ${p.legal_name??''} ${p.document_number??''} ${p.contact_name??''} ${p.email??''} ${p.phone??''} ${p.specialties.join(' ')}`.toLowerCase().includes(term))},[partners,query])
  useEffect(()=>()=>{if(preview)URL.revokeObjectURL(preview)},[preview])
  function clearPreview(){if(preview)URL.revokeObjectURL(preview);setPreview(null)}
  function openNew(){clearPreview();setEditing(null);setForm(blankPartner());setLogo(null);setError('');setModal(true)}
  async function openEdit(p:Partner){clearPreview();setEditing(p);setLogo(null);setError('');setForm({name:p.name,legal_name:p.legal_name??'',document_number:p.document_number??'',contact_name:p.contact_name??'',email:p.email??'',phone:p.phone??'',whatsapp:p.whatsapp??'',street:p.address.street??'',number:p.address.number??'',complement:p.address.complement??'',neighborhood:p.address.neighborhood??'',city:p.address.city??'',state:p.address.state??'',postal_code:p.address.postal_code??'',specialties:p.specialties.join(', '),pix_key:p.pix_key??'',bank_name:p.bank_details.bank_name??'',agency:p.bank_details.agency??'',account:p.bank_details.account??'',notes:p.notes??'',is_active:p.is_active});setModal(true);if(p.has_logo&&p.logo_url){try{const blob=await apiBlobRequest(p.logo_url);setPreview(URL.createObjectURL(blob))}catch{/* preview opcional */}}}
  function close(){if(saving)return;setModal(false);setEditing(null);setLogo(null);clearPreview();setError('')}
  function choose(file:File|null){setLogo(file);clearPreview();if(file)setPreview(URL.createObjectURL(file))}
  async function save(e:FormEvent){e.preventDefault();setSaving(true);setError('');try{const wasEditing=Boolean(editing);const body={name:form.name,legal_name:form.legal_name||null,document_number:form.document_number||null,contact_name:form.contact_name||null,email:form.email||null,phone:form.phone||null,whatsapp:form.whatsapp||null,address:{street:form.street,number:form.number,complement:form.complement,neighborhood:form.neighborhood,city:form.city,state:form.state,postal_code:form.postal_code},specialties:form.specialties.split(',').map(v=>v.trim()).filter(Boolean),pix_key:form.pix_key||null,bank_details:{bank_name:form.bank_name,agency:form.agency,account:form.account},notes:form.notes||null,is_active:form.is_active};let saved=await apiRequest<Partner>(editing?`/maintenance/partners/${editing.id}`:'/maintenance/partners',{method:editing?'PUT':'POST',body:JSON.stringify(body)});if(logo){const data=new FormData();data.append('file',logo);saved=await apiRequest<Partner>(`/maintenance/partners/${saved.id}/logo`,{method:'POST',body:data})}close();await onReload();onSuccess(wasEditing?`${saved.code} atualizado.`:`${saved.code} cadastrado.`)}catch(cause){setError(cause instanceof ApiError?cause.detail:'Não foi possível salvar o parceiro.')}finally{setSaving(false)}}
  return <><div className="panel maintenance-toolbar"><label className="portfolio-search"><Building2 size={15}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Buscar parceiro, CPF/CNPJ, contato ou especialidade..."/></label><div className="heading-actions"><span className="maintenance-toolbar-count">{partners.filter(p=>p.is_active).length} ativo(s) · {partners.length} cadastrado(s)</span>{canManage&&<button className="button primary" type="button" onClick={openNew}><Plus size={14}/> Novo parceiro</button>}</div></div><div className="maintenance-partner-grid">{visible.map(p=><article className={`panel maintenance-partner-card ${p.is_active?'':'inactive'}`} key={p.id}><div className="partner-card-logo"><Building2 size={22}/><small>{p.has_logo?'logo ✓':'sem logo'}</small></div><div className="partner-card-main"><span>{p.code}</span><strong>{p.name}</strong><small>{p.legal_name||'Razão social não informada'}</small>{p.document_number&&<small>CPF/CNPJ: {p.document_number}</small>}</div><div className="partner-card-contact"><span>Contato</span><strong>{p.contact_name||'Não informado'}</strong><small>{p.phone||p.whatsapp||p.email||'Sem contato'}</small></div><div className="partner-card-specialties"><span>Especialidades</span><div>{p.specialties.length?p.specialties.slice(0,4).map(v=><i key={v}>{v}</i>):<small>Não informadas</small>}</div></div><div className="partner-card-actions"><i className={`status-badge ${p.is_active?'success':'neutral'}`}>{p.is_active?'Ativo':'Inativo'}</i>{canManage&&<button className="button secondary compact-button" type="button" onClick={()=>void openEdit(p)}><Pencil size={13}/> Editar</button>}</div></article>)}{!visible.length&&<article className="panel maintenance-empty"><Building2 size={28}/><strong>Nenhum parceiro encontrado.</strong><span>Cadastre a rede de prestadores usada nos orçamentos.</span></article>}</div>
    {modal&&<div className="portfolio-modal-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget)close()}}><form className="panel portfolio-modal maintenance-partner-modal" onSubmit={save}><div className="portfolio-modal-header"><div><span className="eyebrow">Rede terceirizada</span><h2>{editing?`Editar ${editing.code}`:'Novo parceiro'}</h2><p>A logo e estes dados identificam o parceiro nos PDFs de orçamento.</p></div><button className="portfolio-modal-close" type="button" onClick={close}><X size={18}/></button></div><div className="portfolio-modal-body">{error&&<div className="form-alert danger-alert">{error}</div>}<div className="partner-logo-editor"><div className="partner-logo-preview">{preview?<img src={preview} alt="Prévia da logo"/>:<><Building2 size={28}/><span>{editing?.has_logo?'Logo cadastrada':'Sem logo'}</span></>}</div><label className="button secondary"><ImagePlus size={14}/> {editing?.has_logo?'Trocar logo':'Adicionar logo'}<input hidden type="file" accept="image/png,image/jpeg,image/webp" onChange={e=>choose(e.target.files?.[0]??null)}/></label><small>JPG, PNG ou WEBP · até 4 MB.</small></div><div className="form-grid three-columns">
      <label className="field"><span>Nome comercial</span><input required value={form.name} onChange={e=>setForm(c=>({...c,name:e.target.value}))}/></label><label className="field"><span>Razão social / nome completo</span><input value={form.legal_name} onChange={e=>setForm(c=>({...c,legal_name:e.target.value}))}/></label><label className="field"><span>CPF/CNPJ</span><input value={form.document_number} onChange={e=>setForm(c=>({...c,document_number:e.target.value}))}/></label>
      <label className="field"><span>Contato</span><input value={form.contact_name} onChange={e=>setForm(c=>({...c,contact_name:e.target.value}))}/></label><label className="field"><span>E-mail</span><input type="email" value={form.email} onChange={e=>setForm(c=>({...c,email:e.target.value}))}/></label><label className="field"><span>Telefone</span><input value={form.phone} onChange={e=>setForm(c=>({...c,phone:e.target.value}))}/></label><label className="field"><span>WhatsApp</span><input value={form.whatsapp} onChange={e=>setForm(c=>({...c,whatsapp:e.target.value}))}/></label><label className="field field-span-2"><span>Especialidades</span><input value={form.specialties} onChange={e=>setForm(c=>({...c,specialties:e.target.value}))} placeholder="Elétrica, hidráulica, pintura..."/></label>
      <label className="field field-span-2"><span>Rua</span><input value={form.street} onChange={e=>setForm(c=>({...c,street:e.target.value}))}/></label><label className="field"><span>Número</span><input value={form.number} onChange={e=>setForm(c=>({...c,number:e.target.value}))}/></label><label className="field"><span>Complemento</span><input value={form.complement} onChange={e=>setForm(c=>({...c,complement:e.target.value}))}/></label><label className="field"><span>Bairro</span><input value={form.neighborhood} onChange={e=>setForm(c=>({...c,neighborhood:e.target.value}))}/></label><label className="field"><span>CEP</span><input value={form.postal_code} onChange={e=>setForm(c=>({...c,postal_code:e.target.value}))}/></label><label className="field"><span>Cidade</span><input value={form.city} onChange={e=>setForm(c=>({...c,city:e.target.value}))}/></label><label className="field"><span>UF</span><input maxLength={2} value={form.state} onChange={e=>setForm(c=>({...c,state:e.target.value.toUpperCase()}))}/></label>
      <label className="field"><span>Chave Pix</span><input value={form.pix_key} onChange={e=>setForm(c=>({...c,pix_key:e.target.value}))}/></label><label className="field"><span>Banco</span><input value={form.bank_name} onChange={e=>setForm(c=>({...c,bank_name:e.target.value}))}/></label><label className="field"><span>Agência</span><input value={form.agency} onChange={e=>setForm(c=>({...c,agency:e.target.value}))}/></label><label className="field"><span>Conta</span><input value={form.account} onChange={e=>setForm(c=>({...c,account:e.target.value}))}/></label><label className="field field-span-2"><span>Observações</span><input value={form.notes} onChange={e=>setForm(c=>({...c,notes:e.target.value}))}/></label><div className="field"><span>Situação</span><label className="maintenance-toggle"><input type="checkbox" checked={form.is_active} onChange={e=>setForm(c=>({...c,is_active:e.target.checked}))}/><span>Ativo para novos orçamentos</span></label></div>
    </div></div><div className="form-actions portfolio-modal-actions"><button className="button secondary" type="button" onClick={close}>Cancelar</button><button className="button primary" disabled={saving}>{saving?'Salvando...':editing?'Salvar alterações':'Cadastrar parceiro'}</button></div></form></div>}
  </>
}
