import { CheckCircle2, ChevronLeft, ChevronRight, Download, FileCheck2, Percent, Plus, RefreshCw, Settings2, UserRoundPlus, X, XCircle } from 'lucide-react'
import { FormEvent, useCallback, useEffect, useState } from 'react'
import { ApiError, apiBlobRequest, apiRequest } from '../../api/client'
import type { Person } from '../../api/types'
import { BrokerCreateModal } from '../properties/BrokerCreateModal'
import { shiftMonth } from './finance-period'
import './finance-advanced.css'

type Rule={id:string;code:string;name:string;event_type:string;basis:string;calculation_type:string;value:number;beneficiary_type:string;beneficiary_person_id:string;beneficiary_name:string;due_days:number;priority:number;is_active:boolean;notes:string|null}
type Entry={id:string;code:string;source_code:string;beneficiary_name:string;beneficiary_type:string;competence:string;basis_amount:number;amount:number;due_date:string;status:string;financial_title_id:string|null;paid_at:string|null}
type BatchItem={id:string;commission_entry_id:string;amount:number;snapshot:Record<string,unknown>}
type Batch={id:string;code:string;beneficiary_person_id:string;beneficiary_name:string;competence:string;status:string;total_amount:number;broker_legal_name:string|null;broker_document_number:string|null;organization_legal_name:string;organization_document_number:string|null;service_description:string;report_issued_at:string|null;invoice_filename:string|null;invoice_uploaded_at:string|null;finance_review_notes:string|null;approved_at:string|null;payment_due_date:string|null;paid_at:string|null;payment_reference:string|null;items:BatchItem[]}
const money=(v:number)=>Number(v||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'})
const currentMonth=()=>{const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}`}
const eventLabel:Record<string,string>={first_rent:'Primeiro aluguel',recurring:'Recorrente',intermediation:'Intermediação'}
const basisLabel:Record<string,string>={rent:'Aluguel',administration_fee:'Taxa de administração',intermediation_fee:'Intermediação',agency_revenue:'Receita da imobiliária'}

export function FinanceCommissionsPanel({permissions}:{permissions:string[]}){
 const canPrepare=permissions.includes('finance.payment.prepare'),canApprove=permissions.includes('finance.payment.approve'),canCreateBroker=permissions.includes('properties.create')
 const [month,setMonth]=useState(currentMonth()),[rules,setRules]=useState<Rule[]>([]),[entries,setEntries]=useState<Entry[]>([]),[batches,setBatches]=useState<Batch[]>([]),[people,setPeople]=useState<Person[]>([]),[open,setOpen]=useState(false),[brokerOpen,setBrokerOpen]=useState(false),[saving,setSaving]=useState(false),[error,setError]=useState(''),[modalError,setModalError]=useState(''),[success,setSuccess]=useState('')
 const [name,setName]=useState('Comissão de locação'),[eventType,setEventType]=useState('first_rent'),[basis,setBasis]=useState('agency_revenue'),[calc,setCalc]=useState('percent'),[value,setValue]=useState('20'),[beneficiaryType,setBeneficiaryType]=useState('broker'),[personId,setPersonId]=useState(''),[dueDays,setDueDays]=useState('0')
 const competence=`${month}-01`
 const load=useCallback(async()=>{setError('');try{
   if(canPrepare){const now=new Date();const previous=new Date(now.getFullYear(),now.getMonth()-1,1);const previousCompetence=`${previous.getFullYear()}-${String(previous.getMonth()+1).padStart(2,'0')}-01`;await apiRequest(`/finance/advanced/commissions/batches/ensure?competence=${previousCompetence}`,{method:'POST'}).catch(()=>undefined)}
   const [r,e,b,p1,p2]=await Promise.all([apiRequest<Rule[]>('/finance/advanced/commissions/rules'),apiRequest<Entry[]>(`/finance/advanced/commissions?competence=${competence}`),apiRequest<Batch[]>('/finance/advanced/commissions/batches'),apiRequest<Person[]>('/people?role=broker'),apiRequest<Person[]>('/people?role=referrer')]);setRules(r);setEntries(e);setBatches(b);const map=new Map([...p1,...p2].map(p=>[p.id,p]));const persons=[...map.values()];setPeople(persons);setPersonId(current=>persons.some(p=>p.id===current)?current:persons[0]?.id||'')}catch(cause){setError(cause instanceof ApiError?cause.detail:'Não foi possível carregar as comissões.')}},[competence,canPrepare])
 useEffect(()=>{void load()},[load])
 useEffect(()=>{if(!open)return;const close=(event:KeyboardEvent)=>{if(event.key==='Escape'&&!saving)setOpen(false)};window.addEventListener('keydown',close);return()=>window.removeEventListener('keydown',close)},[open,saving])
 async function createRule(ev:FormEvent){ev.preventDefault();if(!personId)return;setSaving(true);setModalError('');try{await apiRequest('/finance/advanced/commissions/rules',{method:'POST',body:JSON.stringify({name,event_type:eventType,basis,calculation_type:calc,value:Number(value.replace(',','.')),beneficiary_type:beneficiaryType,beneficiary_person_id:personId,property_id:null,lease_contract_id:null,due_days:Number(dueDays)||0,priority:100,notes:null})});setOpen(false);setSuccess('Regra de comissão criada.');await load()}catch(cause){setModalError(cause instanceof ApiError?cause.detail:'Não foi possível criar a regra.')}finally{setSaving(false)}}
 async function generate(){const [y,m]=month.split('-').map(Number);const end=new Date(y,m,0).toISOString().slice(0,10);setSaving(true);setError('');try{const created=await apiRequest<Entry[]>(`/finance/advanced/commissions/generate?start_date=${month}-01&end_date=${end}`,{method:'POST'});setSuccess(`${created.length} comissão(ões) gerada(s).`);await load()}catch(cause){setError(cause instanceof ApiError?cause.detail:'Não foi possível gerar comissões.')}finally{setSaving(false)}}
 async function action(entry:Entry,type:'approve'|'cancel'){setSaving(true);setError('');try{await apiRequest(`/finance/advanced/commissions/${entry.id}/${type}`,{method:'POST'});await load()}catch(cause){setError(cause instanceof ApiError?cause.detail:'Não foi possível atualizar a comissão.')}finally{setSaving(false)}}
 async function batchAction(batch:Batch,type:'approve'|'return'){setSaving(true);setError('');try{if(type==='return'){const reason=window.prompt('Motivo da devolução para correção:')?.trim();if(!reason)return;await apiRequest(`/finance/advanced/commissions/batches/${batch.id}/return?reason=${encodeURIComponent(reason)}`,{method:'POST'})}else await apiRequest(`/finance/advanced/commissions/batches/${batch.id}/approve`,{method:'POST'});await load()}catch(cause){setError(cause instanceof ApiError?cause.detail:'Não foi possível atualizar o lote.')}finally{setSaving(false)}}
 async function downloadInvoice(batch:Batch){try{const blob=await apiBlobRequest(`/finance/advanced/commissions/batches/${batch.id}/invoice`);const url=URL.createObjectURL(blob);window.open(url,'_blank','noopener,noreferrer');setTimeout(()=>URL.revokeObjectURL(url),30000)}catch(cause){setError(cause instanceof ApiError?cause.detail:'Não foi possível abrir a Nota Fiscal.')}}
 const batchStatusLabel:Record<string,string>={report_released:'Relatório liberado',report_issued:'Relatório emitido',awaiting_finance_approval:'Aguardando aprovação financeira',returned:'Devolvido para correção',scheduled:'Programado para pagamento',paid:'Pago',cancelled:'Cancelado'}
 const batchStatusClass=(status:string)=>status==='paid'?'success':status==='scheduled'?'warning':status==='awaiting_finance_approval'?'warning':status==='returned'?'danger':'neutral'
 function brokerCreated(person:Person){setPersonId(person.id);setSuccess(`${person.name} cadastrado como corretor.`);void load()}
 const pending=entries.filter(e=>!['paid','cancelled'].includes(e.status)),total=pending.reduce((s,e)=>s+e.amount,0),paid=entries.filter(e=>e.status==='paid').reduce((s,e)=>s+e.amount,0)
 return <section className="workspace finance-advanced-workspace"><div className="page-heading finance-heading"><div><span className="eyebrow">Financeiro · Comissões</span><h1>Comissões parametrizáveis</h1><p>Regras por evento e base de cálculo, gerando obrigação operacional rastreável no financeiro.</p></div><div className="heading-actions"><button className="icon-button" type="button" onClick={()=>setMonth(current=>shiftMonth(current,-1))} aria-label="Competência anterior" title="Competência anterior"><ChevronLeft size={16}/></button><input className="finance-compact-input" type="month" value={month} onChange={e=>setMonth(e.target.value)}/><button className="icon-button" type="button" onClick={()=>setMonth(current=>shiftMonth(current,1))} aria-label="Próxima competência" title="Próxima competência"><ChevronRight size={16}/></button><button className="button secondary" onClick={()=>void load()}><RefreshCw size={14}/> Atualizar</button>{canCreateBroker&&<button className="button secondary" onClick={()=>setBrokerOpen(true)}><UserRoundPlus size={14}/> Novo corretor</button>}{canPrepare&&<button className="button secondary" onClick={()=>void generate()} disabled={saving}><Percent size={14}/> Gerar período</button>}{canPrepare&&<button className="button primary" onClick={()=>{setModalError('');setOpen(true)}}><Plus size={14}/> Nova regra</button>}</div></div>{error&&<div className="form-alert danger-alert">{error}</div>}{success&&<div className="form-alert success-alert">{success}</div>}
 <div className="finance-advanced-metrics"><article className="panel"><span>Regras ativas</span><strong>{rules.filter(r=>r.is_active).length}</strong><small>{rules.length} cadastrada(s)</small></article><article className="panel"><span>A pagar</span><strong>{money(total)}</strong><small>{pending.length} comissão(ões)</small></article><article className="panel metric-positive"><span>Pagas no mês</span><strong>{money(paid)}</strong><small>Baixa vinculada ao financeiro</small></article></div>
 <div className="finance-advanced-grid two"><article className="panel finance-advanced-card"><div className="finance-advanced-card-head"><div><span className="eyebrow">Configuração</span><h2>Regras</h2></div><Settings2 size={20}/></div><div className="finance-compact-list">{rules.map(r=><div className={`finance-compact-row ${!r.is_active?'muted':''}`} key={r.id}><div><strong>{r.code} · {r.name}</strong><span>{eventLabel[r.event_type]||r.event_type} · {basisLabel[r.basis]||r.basis}</span><small>{r.beneficiary_name} · {r.calculation_type==='percent'?`${r.value}%`:money(r.value)}</small></div><i className={`status-badge ${r.is_active?'success':'neutral'}`}>{r.is_active?'Ativa':'Inativa'}</i></div>)}{rules.length===0&&<div className="finance-empty compact"><Percent size={23}/><strong>Nenhuma regra cadastrada.</strong><span>Defina percentuais ou valores fixos sem engessar o modelo de comissão.</span></div>}</div></article>
 <article className="panel finance-advanced-card"><div className="finance-advanced-card-head"><div><span className="eyebrow">Competência</span><h2>Comissões geradas</h2></div><Percent size={20}/></div><div className="finance-compact-list">{entries.map(e=><div className="finance-compact-row" key={e.id}><div><strong>{e.code} · {e.beneficiary_name}</strong><span>{e.source_code} · venc. {new Date(`${e.due_date}T12:00:00`).toLocaleDateString('pt-BR')}</span><small>Base {money(e.basis_amount)}</small></div><div><strong>{money(e.amount)}</strong><div className="finance-mini-actions">{canApprove&&e.status==='pending'&&<button onClick={()=>void action(e,'approve')}><CheckCircle2 size={12}/> Aprovar</button>}{canApprove&&!['paid','cancelled'].includes(e.status)&&<button onClick={()=>void action(e,'cancel')}><XCircle size={12}/></button>}<i className={`status-badge ${e.status==='paid'?'success':e.status==='approved'?'warning':e.status==='cancelled'?'neutral':'warning'}`}>{e.status}</i></div></div></div>)}{entries.length===0&&<div className="finance-empty compact"><CheckCircle2 size={23}/><strong>Nenhuma comissão nesta competência.</strong><span>Use “Gerar período” para aplicar as regras aos recebimentos realizados.</span></div>}</div></article></div>
 <article className="panel finance-advanced-card commission-batch-card"><div className="finance-advanced-card-head"><div><span className="eyebrow">Lotes de comissão</span><h2>Conferência de NF e programação de pagamento</h2><p>Os lotes são fechados pelo mês de recebimento e entram na fila após o corretor anexar a Nota Fiscal.</p></div><FileCheck2 size={20}/></div><div className="commission-batch-list">{batches.map(batch=><div className="commission-batch-row" key={batch.id}><div className="commission-batch-main"><strong>{batch.code} · {batch.beneficiary_name}</strong><span>{new Date(batch.competence+'T12:00:00').toLocaleDateString('pt-BR',{month:'long',year:'numeric'})} · {money(batch.total_amount)}</span><small><b>{batch.broker_legal_name||'Razão social não informada'}</b> · CNPJ {batch.broker_document_number||'não informado'}</small></div><div className="commission-batch-docs"><span>NF: {batch.invoice_filename||'não anexada'}</span>{batch.payment_due_date&&<small>Prev. pagamento {new Date(batch.payment_due_date+'T12:00:00').toLocaleDateString('pt-BR')}</small>}{batch.finance_review_notes&&<small className="danger-text">{batch.finance_review_notes}</small>}</div><div className="commission-batch-actions">{batch.invoice_filename&&<button className="button secondary compact" type="button" onClick={()=>void downloadInvoice(batch)}><Download size={12}/> Ver NF</button>}{canApprove&&batch.status==='awaiting_finance_approval'&&<><button className="button secondary compact" type="button" disabled={saving} onClick={()=>void batchAction(batch,'return')}><XCircle size={12}/> Devolver</button><button className="button primary compact" type="button" disabled={saving} onClick={()=>void batchAction(batch,'approve')}><CheckCircle2 size={12}/> Aprovar</button></>}<i className={'status-badge '+batchStatusClass(batch.status)}>{batchStatusLabel[batch.status]||batch.status}</i></div></div>)}{batches.length===0&&<div className="finance-empty compact"><FileCheck2 size={23}/><strong>Nenhum lote de comissão.</strong><span>Os lotes são liberados automaticamente após o fechamento do mês de recebimento.</span></div>}</div></article>
 {open&&<div className="portfolio-modal-backdrop" onMouseDown={e=>{if(e.currentTarget===e.target&&!saving)setOpen(false)}}><form className="panel portfolio-modal commission-rule-modal" onSubmit={createRule} role="dialog" aria-modal="true"><div className="portfolio-modal-header"><div><span className="eyebrow">Regra de comissão</span><h2>Nova regra</h2><p>A regra pode ser alterada depois sem perder a rastreabilidade das entradas já geradas.</p></div><button className="portfolio-modal-close" type="button" aria-label="Fechar" disabled={saving} onClick={()=>setOpen(false)}><X size={17}/></button></div><div className="commission-rule-body">{modalError&&<div className="form-alert danger-alert" role="alert">{modalError}</div>}<label className="field"><span>Nome</span><input value={name} onChange={e=>setName(e.target.value)} required/></label><div className="form-grid two-columns"><label className="field"><span>Evento</span><select value={eventType} onChange={e=>setEventType(e.target.value)}><option value="first_rent">Primeiro aluguel</option><option value="recurring">Recorrente</option><option value="intermediation">Intermediação</option></select></label><label className="field"><span>Base</span><select value={basis} onChange={e=>setBasis(e.target.value)}><option value="agency_revenue">Receita da imobiliária</option><option value="rent">Aluguel</option><option value="administration_fee">Taxa de administração</option><option value="intermediation_fee">Intermediação</option></select></label><label className="field"><span>Cálculo</span><select value={calc} onChange={e=>setCalc(e.target.value)}><option value="percent">Percentual</option><option value="fixed">Valor fixo</option></select></label><label className="field"><span>{calc==='percent'?'Percentual (%)':'Valor (R$)'}</span><input inputMode="decimal" value={value} onChange={e=>setValue(e.target.value)} required/></label><label className="field"><span>Tipo</span><select value={beneficiaryType} onChange={e=>setBeneficiaryType(e.target.value)}><option value="broker">Corretor</option><option value="referrer">Angariador</option><option value="other">Outro</option></select></label><label className="field"><span>Beneficiário</span><select value={personId} onChange={e=>setPersonId(e.target.value)} required><option value="">Selecione...</option>{people.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label><label className="field"><span>Vencimento após recebimento</span><input type="number" min="0" max="180" value={dueDays} onChange={e=>setDueDays(e.target.value)}/></label></div></div><div className="canonical-modal-actions"><button className="button secondary" type="button" onClick={()=>setOpen(false)}>Cancelar</button><button className="button primary" disabled={saving}>{saving?'Salvando...':'Salvar regra'}</button></div></form></div>}
 <BrokerCreateModal open={brokerOpen} onClose={()=>setBrokerOpen(false)} onCreated={brokerCreated}/>
 </section>
}
