import { Copy, ExternalLink, Link2, Plus, RefreshCw, ShieldCheck, X, XCircle } from 'lucide-react'
import { FormEvent, useCallback, useEffect, useState } from 'react'
import { ApiError, apiRequest } from '../../api/client'
import './finance-advanced.css'

type Person={id:string;name:string;document_number:string|null;email:string|null;role_keys:string[]}
type Access={id:string;person_id:string;person_name:string;document_number:string|null;roles:string[];label:string|null;is_active:boolean;expires_at:string;revoked_at:string|null;last_used_at:string|null;created_at:string;path:string}
const dt=(value:string|null)=>value?new Date(value).toLocaleString('pt-BR'):'Nunca'
const roleLabel=(roles:string[])=>roles.includes('owner')&&roles.includes('tenant')?'Proprietário + locatário':roles.includes('owner')?'Proprietário':roles.includes('tenant')?'Locatário':'Sem vínculo ativo'

export function FinancePortalsPanel({permissions}:{permissions:string[]}){
 const canManage=permissions.includes('finance.payment.approve')
 const [accesses,setAccesses]=useState<Access[]>([]),[people,setPeople]=useState<Person[]>([]),[personId,setPersonId]=useState(''),[label,setLabel]=useState(''),[open,setOpen]=useState(false),[created,setCreated]=useState<Access|null>(null),[error,setError]=useState(''),[modalError,setModalError]=useState(''),[success,setSuccess]=useState(''),[saving,setSaving]=useState(false)
 const load=useCallback(async()=>{setError('');try{setAccesses(await apiRequest<Access[]>('/finance/advanced/portal/access'))}catch(cause){setError(cause instanceof ApiError?cause.detail:'Não foi possível carregar os acessos externos.')}},[])
 useEffect(()=>{void load();void apiRequest<Person[]>('/people').then(items=>{setPeople(items);setPersonId(current=>current||items[0]?.id||'')}).catch(()=>setPeople([]))},[load])
 useEffect(()=>{if(!open)return;const close=(event:KeyboardEvent)=>{if(event.key==='Escape'&&!saving)setOpen(false)};window.addEventListener('keydown',close);return()=>window.removeEventListener('keydown',close)},[open,saving])
 const fullLink=(item:Access)=>`${window.location.origin}${item.path}`
 async function copy(item:Access){await navigator.clipboard.writeText(fullLink(item));setSuccess(`Link de ${item.person_name} copiado.`)}
 function openPortal(item:Access){window.open(fullLink(item),'_blank','noopener,noreferrer')}
 async function create(ev:FormEvent){ev.preventDefault();if(!personId)return;setSaving(true);setModalError('');try{const result=await apiRequest<Access>('/finance/advanced/portal/access',{method:'POST',body:JSON.stringify({person_id:personId,label:label||null})});setCreated(result);setOpen(false);setLabel('');setSuccess('Acesso permanente ativado. Este mesmo link continua disponível na lista.');await load()}catch(cause){setModalError(cause instanceof ApiError?cause.detail:'Não foi possível criar o acesso externo.')}finally{setSaving(false)}}
 async function revoke(item:Access){setSaving(true);setError('');try{await apiRequest(`/finance/advanced/portal/access/${item.id}/revoke`,{method:'POST'});setCreated(null);await load();setSuccess(`Acesso de ${item.person_name} revogado. O endereço poderá ser reativado depois sem mudar o link.`)}catch(cause){setError(cause instanceof ApiError?cause.detail:'Não foi possível revogar o acesso.')}finally{setSaving(false)}}
 return <section className="workspace finance-advanced-workspace"><div className="page-heading finance-heading"><div><span className="eyebrow">Financeiro · Portais</span><h1>Portais externos</h1><p>Um acesso permanente por pessoa. O mesmo link acompanha automaticamente os vínculos de proprietário e locatário.</p></div><div className="heading-actions"><button className="button secondary" onClick={()=>void load()}><RefreshCw size={14}/> Atualizar</button>{canManage&&<button className="button primary" onClick={()=>{setModalError('');setOpen(true)}}><Plus size={14}/> Novo acesso</button>}</div></div>{error&&<div className="form-alert danger-alert">{error}</div>}{success&&<div className="form-alert success-alert">{success}</div>}
 {created&&<article className="panel portal-created"><ShieldCheck size={20}/><div><strong>Acesso permanente de {created.person_name}</strong><span>Este endereço não desaparece ao fechar a tela e pode ser copiado novamente a qualquer momento.</span><code>{fullLink(created)}</code><div className="finance-inline-actions"><button className="button secondary compact" onClick={()=>void copy(created)}><Copy size={13}/> Copiar</button><button className="button primary compact" onClick={()=>openPortal(created)}><ExternalLink size={13}/> Abrir portal</button><button className="button secondary compact" onClick={()=>setCreated(null)}>Ocultar</button></div></div></article>}
 <div className="finance-advanced-metrics"><article className="panel"><span>Acessos ativos</span><strong>{accesses.filter(item=>item.is_active).length}</strong><small>Um endereço por pessoa</small></article><article className="panel"><span>Proprietários</span><strong>{accesses.filter(item=>item.is_active&&item.roles.includes('owner')).length}</strong><small>Prestação, repasses e informe anual</small></article><article className="panel"><span>Locatários</span><strong>{accesses.filter(item=>item.is_active&&item.roles.includes('tenant')).length}</strong><small>Cobranças, Pix e comprovantes</small></article></div>
 <article className="panel finance-advanced-card"><div className="finance-advanced-card-head"><div><span className="eyebrow">Controle de acesso</span><h2>Links permanentes</h2></div><Link2 size={20}/></div><div className="finance-compact-list portal-link-list">{accesses.map(item=><div className={`finance-compact-row portal-link-row ${!item.is_active?'muted':''}`} key={item.id}><div className="portal-link-person"><button className="portal-person-link" type="button" disabled={!item.is_active} onClick={()=>openPortal(item)}><strong>{item.person_name}</strong><ExternalLink size={12}/></button><span>{item.document_number||'CPF/CNPJ não informado'} · {roleLabel(item.roles)}</span><small>Último acesso: {dt(item.last_used_at)}</small></div><div className="portal-row-actions"><button className="button secondary compact" type="button" onClick={()=>void copy(item)}><Copy size={12}/> Copiar link</button><i className={`status-badge ${item.is_active?'success':'neutral'}`}>{item.is_active?'Ativo':'Revogado'}</i>{item.is_active&&canManage&&<button className="icon-danger" title="Revogar" onClick={()=>void revoke(item)}><XCircle size={15}/></button>}</div></div>)}{accesses.length===0&&<div className="finance-empty compact"><Link2 size={24}/><strong>Nenhum acesso externo criado.</strong><span>Crie um acesso para uma pessoa; os papéis são identificados automaticamente pelos contratos e imóveis.</span></div>}</div></article>
 {open&&<div className="portfolio-modal-backdrop" onMouseDown={event=>{if(event.currentTarget===event.target&&!saving)setOpen(false)}}><form className="panel portfolio-modal portal-access-modal" onSubmit={create} role="dialog" aria-modal="true"><div className="portfolio-modal-header"><div><span className="eyebrow">Portal externo</span><h2>Ativar acesso permanente</h2><p>Se a pessoa já teve um portal, o mesmo endereço será reativado.</p></div><button className="portfolio-modal-close" type="button" aria-label="Fechar" disabled={saving} onClick={()=>setOpen(false)}><X size={17}/></button></div><div className="portal-access-modal-body">{modalError&&<div className="form-alert danger-alert" role="alert">{modalError}</div>}<div className="form-grid two-columns"><label className="field"><span>Pessoa</span><select value={personId} onChange={e=>setPersonId(e.target.value)} required><option value="">Selecione...</option>{people.map(person=><option key={person.id} value={person.id}>{person.name}{person.document_number?` · ${person.document_number}`:''}</option>)}</select></label><label className="field"><span>Identificação interna (opcional)</span><input value={label} onChange={e=>setLabel(e.target.value)} placeholder="Ex.: acesso principal"/></label></div></div><div className="canonical-modal-actions"><button type="button" className="button secondary" disabled={saving} onClick={()=>setOpen(false)}>Cancelar</button><button className="button primary" disabled={saving||!personId}>{saving?'Ativando...':'Ativar link'}</button></div></form></div>}
 </section>
}
