import { BarChart3, ChevronLeft, ChevronRight, Download, FileText, RefreshCw, TrendingDown, TrendingUp } from 'lucide-react'
import { useCallback, useEffect, useMemo, useState } from 'react'
import { ApiError, apiBlobRequest, apiRequest } from '../../api/client'
import { shiftMonth } from './finance-period'
import './finance-advanced.css'

type Overview={start_date:string;end_date:string;tenant_collections:number;agency_revenue:number;owner_repasses:number;maintenance_revenue:number;maintenance_cost:number;commissions:number;overdue_amount:number;overdue_count:number;paid_charges:number;open_charges:number}
type DreLine={key:string;label:string;kind:'revenue'|'expense';amount:number}
type Dre={start_date:string;end_date:string;regime:'cash'|'competence';total_revenue:number;total_expenses:number;result:number;margin_percent:number;lines:DreLine[]}
type Person={id:string;name:string;document_number:string|null;role_keys:string[]}
type AnnualLine={competence:string;payment_date:string|null;property_code:string;charge_code:string;rent_amount:number;additional_charges:number;total_amount:number;administration_fee:number;owner_net_amount:number}
type Annual={year:number;party_type:'owner'|'tenant';person_id:string;person_name:string;allocation_method:string;total_rent:number;total_additional_charges:number;total_paid:number;total_administration_fee:number;total_owner_net:number;lines:AnnualLine[]}
const money=(v:number)=>Number(v||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'})
const todayMonth=()=>{const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}`}
const range=(month:string)=>{const [y,m]=month.split('-').map(Number);return {start:`${month}-01`,end:new Date(y,m,0).toISOString().slice(0,10)}}
function openBlob(blob:Blob){const url=URL.createObjectURL(blob);window.open(url,'_blank','noopener,noreferrer');setTimeout(()=>URL.revokeObjectURL(url),60000)}

export function FinanceReportsPanel({permissions}:{permissions:string[]}){
  const canExport=permissions.includes('reports.export')
  const [month,setMonth]=useState(todayMonth());const [regime,setRegime]=useState<'cash'|'competence'>('cash');const [overview,setOverview]=useState<Overview|null>(null);const [dre,setDre]=useState<Dre|null>(null)
  const [party,setParty]=useState<'tenant'|'owner'>('tenant');const [people,setPeople]=useState<Person[]>([]);const [personId,setPersonId]=useState('');const [year,setYear]=useState(String(new Date().getFullYear()));const [annual,setAnnual]=useState<Annual|null>(null)
  const [loading,setLoading]=useState(true);const [error,setError]=useState('')
  const period=useMemo(()=>range(month),[month])
  const load=useCallback(async()=>{setLoading(true);setError('');try{const [o,d]=await Promise.all([apiRequest<Overview>(`/finance/advanced/reports/overview?start_date=${period.start}&end_date=${period.end}`),apiRequest<Dre>(`/finance/advanced/reports/dre?start_date=${period.start}&end_date=${period.end}&regime=${regime}`)]);setOverview(o);setDre(d)}catch(e){setError(e instanceof ApiError?e.detail:'Não foi possível carregar os relatórios.')}finally{setLoading(false)}},[period.start,period.end,regime])
  useEffect(()=>{void load()},[load])
  useEffect(()=>{void (async()=>{try{const p=await apiRequest<Person[]>(`/people?role=${party}`);setPeople(p);setPersonId(current=>p.some(x=>x.id===current)?current:p[0]?.id||'');setAnnual(null)}catch{setPeople([]);setPersonId('')}})()},[party])
  async function loadAnnual(){if(!personId)return;setError('');try{setAnnual(await apiRequest<Annual>(`/finance/advanced/reports/annual-income?year=${year}&party_type=${party}&person_id=${personId}`))}catch(e){setError(e instanceof ApiError?e.detail:'Não foi possível gerar o informe anual.')}}
  async function pdf(kind:'dre'|'annual'|'statement'){
    if(!canExport)return
    try{let path='';if(kind==='dre')path=`/finance/advanced/reports/dre.pdf?start_date=${period.start}&end_date=${period.end}&regime=${regime}`;else if(kind==='annual')path=`/finance/advanced/reports/annual-income.pdf?year=${year}&party_type=${party}&person_id=${personId}`;else path=`/finance/statements/${personId}/pdf?competence=${month}-01`;openBlob(await apiBlobRequest(path))}catch(e){setError(e instanceof ApiError?e.detail:'Não foi possível abrir o PDF.')}
  }
  return <section className="workspace finance-advanced-workspace finance-reports-workspace">
    <div className="page-heading finance-heading finance-reports-heading"><div><span className="eyebrow">Financeiro · Relatórios</span><h1>DRE, indicadores e informes</h1><p>Receita da imobiliária separada dos recursos de terceiros, com relatórios operacionais e documentos anuais.</p></div><div className="heading-actions"><button className="icon-button" type="button" onClick={()=>setMonth(current=>shiftMonth(current,-1))} aria-label="Competência anterior" title="Competência anterior"><ChevronLeft size={16}/></button><input className="finance-compact-input" type="month" value={month} onChange={e=>setMonth(e.target.value)}/><button className="icon-button" type="button" onClick={()=>setMonth(current=>shiftMonth(current,1))} aria-label="Próxima competência" title="Próxima competência"><ChevronRight size={16}/></button><select className="finance-compact-input" value={regime} onChange={e=>setRegime(e.target.value as 'cash'|'competence')}><option value="cash">Regime de caixa</option><option value="competence">Competência</option></select><button className="button secondary" onClick={()=>void load()}><RefreshCw size={14}/> Atualizar</button></div></div>
    {error&&<div className="form-alert danger-alert">{error}</div>}
    <div className="finance-advanced-metrics finance-reports-metrics"><article className="panel"><span>Recebido de locatários</span><strong>{money(overview?.tenant_collections||0)}</strong><small>Movimento de terceiros</small></article><article className="panel metric-positive"><span>Receita da imobiliária</span><strong>{money(overview?.agency_revenue||0)}</strong><small>Taxas reconhecidas</small></article><article className="panel"><span>Repasses pagos</span><strong>{money(overview?.owner_repasses||0)}</strong><small>Valores de proprietários</small></article><article className="panel"><span>Manutenção · margem bruta</span><strong>{money((overview?.maintenance_revenue||0)-(overview?.maintenance_cost||0))}</strong><small>{money(overview?.maintenance_revenue||0)} cobrado · {money(overview?.maintenance_cost||0)} parceiro</small></article><article className={`panel ${(overview?.overdue_count||0)?'metric-danger':''}`}><span>Inadimplência</span><strong>{money(overview?.overdue_amount||0)}</strong><small>{overview?.overdue_count||0} cobrança(s)</small></article></div>
    <div className="finance-advanced-grid two finance-reports-grid">
      <article className="panel finance-advanced-card finance-report-card finance-report-dre"><div className="finance-advanced-card-head"><div><span className="eyebrow">Resultado</span><h2>DRE da imobiliária</h2></div><BarChart3 size={21}/></div>{loading&&!dre?<div className="settings-loading">Carregando DRE...</div>:dre&&<><div className="dre-summary"><div><TrendingUp size={16}/><span>Receitas</span><strong>{money(dre.total_revenue)}</strong></div><div><TrendingDown size={16}/><span>Despesas</span><strong>{money(dre.total_expenses)}</strong></div><div><span>Resultado</span><strong className={dre.result<0?'negative':'positive'}>{money(dre.result)}</strong><small>Margem {dre.margin_percent.toLocaleString('pt-BR')}%</small></div></div><div className="finance-compact-list">{dre.lines.map(line=><div className="finance-compact-row" key={line.key}><div><strong>{line.label}</strong><span>{line.kind==='revenue'?'Receita operacional':'Custo / despesa'}</span></div><strong className={line.kind==='revenue'?'positive':'negative'}>{money(line.amount)}</strong></div>)}</div>{canExport?<button className="button secondary compact" onClick={()=>void pdf('dre')}><Download size={13}/> Abrir DRE em PDF</button>:<small>Seu perfil permite consultar, mas não exportar relatórios.</small>}</>}</article>
      <article className="panel finance-advanced-card finance-report-card finance-report-annual"><div className="finance-advanced-card-head"><div><span className="eyebrow">Documento anual</span><h2>Informe de rendimentos</h2><p>Gere o informe por pessoa e ano-calendário.</p></div><FileText size={21}/></div><div className="finance-form-row finance-report-toolbar"><select value={party} onChange={e=>setParty(e.target.value as 'tenant'|'owner')}><option value="tenant">Locatário</option><option value="owner">Proprietário</option></select><select value={personId} onChange={e=>{setPersonId(e.target.value);setAnnual(null)}}><option value="">Selecione...</option>{people.map(p=><option value={p.id} key={p.id}>{p.name}</option>)}</select><input type="number" min="2000" max="2200" value={year} onChange={e=>setYear(e.target.value)}/><button className="button primary compact" disabled={!personId} onClick={()=>void loadAnnual()}>Gerar</button></div>{annual&&<><div className="finance-provider-note"><FileText size={14}/><span>Critério: {annual.allocation_method}.</span></div><div className="dre-summary annual"><div><span>Aluguel</span><strong>{money(annual.total_rent)}</strong></div><div><span>Encargos</span><strong>{money(annual.total_additional_charges)}</strong></div><div><span>Total no ano</span><strong>{money(annual.total_paid)}</strong></div></div><div className="finance-compact-list limited">{annual.lines.map((l,i)=><div className="finance-compact-row" key={`${l.charge_code}-${i}`}><div><strong>{l.charge_code} · {l.property_code}</strong><span>{l.competence.slice(0,7).split('-').reverse().join('/')}</span></div><strong>{money(l.total_amount)}</strong></div>)}</div>{canExport?<div className="finance-inline-actions"><button className="button secondary compact" onClick={()=>void pdf('annual')}><Download size={13}/> Informe PDF</button>{party==='owner'&&<button className="button secondary compact" onClick={()=>void pdf('statement')}><Download size={13}/> Prestação mensal PDF</button>}</div>:<small>Seu perfil permite consultar, mas não exportar relatórios.</small>}</>}</article>
    </div>
  </section>
}
