import { CheckCircle2, Percent, Plus, RefreshCw, Settings2, XCircle } from 'lucide-react'
import { FormEvent, useCallback, useEffect, useState } from 'react'
import { ApiError, apiRequest } from '../../api/client'
import './finance-advanced.css'

type Person={id:string;name:string;role_keys:string[]}
type Rule={id:string;code:string;name:string;event_type:string;basis:string;calculation_type:string;value:number;beneficiary_type:string;beneficiary_person_id:string;beneficiary_name:string;due_days:number;priority:number;is_active:boolean;notes:string|null}
type Entry={id:string;code:string;source_code:string;beneficiary_name:string;beneficiary_type:string;competence:string;basis_amount:number;amount:number;due_date:string;status:string;financial_title_id:string|null;paid_at:string|null}
const money=(v:number)=>Number(v||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'})
const currentMonth=()=>{const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}`}
const eventLabel:Record<string,string>={first_rent:'Primeiro aluguel',recurring:'Recorrente',intermediation:'Intermediação'}
const basisLabel:Record<string,string>={rent:'Aluguel',administration_fee:'Taxa de administração',intermediation_fee:'Intermediação',agency_revenue:'Receita da imobiliária'}

export function FinanceCommissionsPanel({permissions}:{permissions:string[]}){
 const canPrepare=permissions.includes('finance.payment.prepare'),canApprove=permissions.includes('finance.payment.approve')
 const [month,setMonth]=useState(currentMonth());const [rules,setRules]=useState<Rule[]>([]);const [entries,setEntries]=useState<Entry[]>([]);const [people,setPeople]=useState<Person[]>([]);const [open,setOpen]=useState(false);const [saving,setSaving]=useState(false);const [error,setError]=useState('');const [success,setSuccess]=useState('')
 const [name,setName]=useState('Comissão de locação');const [eventType,setEventType]=useState('first_rent');const [basis,setBasis]=useState('agency_revenue');const [calc,setCalc]=useState('percent');const [value,setValue]=useState('20');const [beneficiaryType,setBeneficiaryType]=useState('broker');const [personId,setPersonId]=useState('');const [dueDays,setDueDays]=useState('0')
 const competence=`${month}-01`
 const load=useCallback(async()=>{setError('');try{const [r,e,p1,p2]=await Promise.all([apiRequest<Rule[]>('/finance/advanced/commissions/rules'),apiRequest<Entry[]>(`/finance/advanced/commissions?competence=${competence}`),apiRequest<Person[]>('/people?role=broker'),apiRequest<Person[]>('/people?role=referrer')]);setRules(r);setEntries(e);const map=new Map([...p1,...p2].map(p=>[p.id,p]));const persons=[...map.values()];setPeople(persons);setPersonId(current=>persons.some(p=>p.id===current)?current:persons[0]?.id||'')}catch(e){setError(e instanceof ApiError?e.detail:'Não foi possível carregar as comissões.')}},[competence])
 useEffect(()=>{void load()},[load])
 async function createRule(ev:FormEvent){ev.preventDefault();if(!personId)return;setSaving(true);setError('');try{await apiRequest('/finance/advanced/commissions/rules',{method:'POST',body:JSON.stringify({name,event_type:eventType,basis,calculation_type:calc,value:Number(value.replace(',','.')),beneficiary_type:beneficiaryType,beneficiary_person_id:personId,property_id:null,lease_contract_id:null,due_days:Number(dueDays)||0,priority:100,notes:null})});setOpen(false);setSuccess('Regra de comissão criada.');await load()}catch(e){setError(e instanceof ApiError?e.detail:'Não foi possível criar a regra.')}finally{setSaving(false)}}
 async function generate(){const [y,m]=month.split('-').map(Number);const end=new Date(y,m,0).toISOString().slice(0,10);setSaving(true);setError('');try{const created=await apiRequest<Entry[]>(`/finance/advanced/commissions/generate?start_date=${month}-01&end_date=${end}`,{method:'POST'});setSuccess(`${created.length} comissão(ões) gerada(s).`);await load()}catch(e){setError(e instanceof ApiError?e.detail:'Não foi possível gerar comissões.')}finally{setSaving(false)}}
 async function action(entry:Entry,type:'approve'|'cancel'){setSaving(true);setError('');try{await apiRequest(`/finance/advanced/commissions/${entry.id}/${type}`,{method:'POST'});await load()}catch(e){setError(e instanceof ApiError?e.detail:'Não foi possível atualizar a comissão.')}finally{setSaving(false)}}
 const pending=entries.filter(e=>!['paid','cancelled'].includes(e.status));const total=pending.reduce((s,e)=>s+e.amount,0);const paid=entries.filter(e=>e.status==='paid').reduce((s,e)=>s+e.amount,0)
 return <section className="workspace finance-advanced-workspace"><div className="page-heading finance-heading"><div><span className="eyebrow">Financeiro · Comissões</span><h1>Comissões parametrizáveis</h1><p>Regras por evento e base de cálculo, gerando obrigação operacional rastreável no financeiro.</p></div><div className="heading-actions"><input className="finance-compact-input" type="month" value={month} onChange={e=>setMonth(e.target.value)}/><button className="button secondary" onClick={()=>void load()}><RefreshCw size={14}/> Atualizar</button>{canPrepare&&<button className="button secondary" onClick={()=>void generate()} disabled={saving}><Percent size={14}/> Gerar período</button>}{canPrepare&&<button className="button primary" onClick={()=>setOpen(true)}><Plus size={14}/> Nova regra</button>}</div></div>{error&&<div className="form-alert danger-alert">{error}</div>}{success&&<div className="form-alert success-alert">{success}</div>}
 <div className="finance-advanced-metrics"><article className="panel"><span>Regras ativas</span><strong>{rules.filter(r=>r.is_active).length}</strong><small>{rules.length} cadastrada(s)</small></article><article className="panel"><span>A pagar</span><strong>{money(total)}</strong><small>{pending.length} comissão(ões)</small></article><article className="panel metric-positive"><span>Pagas no mês</span><strong>{money(paid)}</strong><small>Baixa vinculada ao financeiro</small></article></div>
 <div className="finance-advanced-grid two"><article className="panel finance-advanced-card"><div className="finance-advanced-card-head"><div><span className="eyebrow">Configuração</span><h2>Regras</h2></div><Settings2 size={20}/></div><div className="finance-compact-list">{rules.map(r=><div className={`finance-compact-row ${!r.is_active?'muted':''}`} key={r.id}><div><strong>{r.code} · {r.name}</strong><span>{eventLabel[r.event_type]||r.event_type} · {basisLabel[r.basis]||r.basis}</span><small>{r.beneficiary_name} · {r.calculation_type==='percent'?`${r.value}%`:money(r.value)}</small></div><i className={`status-badge ${r.is_active?'success':'neutral'}`}>{r.is_active?'Ativa':'Inativa'}</i></div>)}{rules.length===0&&<div className="finance-empty compact"><Percent size={23}/><strong>Nenhuma regra cadastrada.</strong><span>Defina percentuais ou valores fixos sem engessar o modelo de comissão.</span></div>}</div></article>
 <article className="panel finance-advanced-card"><div className="finance-advanced-card-head"><div><span className="eyebrow">Competência</span><h2>Comissões geradas</h2></div><Percent size={20}/></div><div className="finance-compact-list">{entries.map(e=><div className="finance-compact-row" key={e.id}><div><strong>{e.code} · {e.beneficiary_name}</strong><span>{e.source_code} · venc. {new Date(`${e.due_date}T12:00:00`).toLocaleDateString('pt-BR')}</span><small>Base {money(e.basis_amount)}</small></div><div><strong>{money(e.amount)}</strong><div className="finance-mini-actions">{canApprove&&e.status==='pending'&&<button onClick={()=>void action(e,'approve')}><CheckCircle2 size={12}/> Aprovar</button>}{canApprove&&!['paid','cancelled'].includes(e.status)&&<button onClick={()=>void action(e,'cancel')}><XCircle size={12}/></button>}<i className={`status-badge ${e.status==='paid'?'success':e.status==='approved'?'warning':e.status==='cancelled'?'neutral':'warning'}`}>{e.status}</i></div></div></div>)}{entries.length===0&&<div className="finance-empty compact"><CheckCircle2 size={23}/><strong>Nenhuma comissão nesta competência.</strong><span>Use “Gerar período” para aplicar as regras aos recebimentos realizados.</span></div>}</div></article></div>
 {open&&<div className="finance-modal-backdrop" onMouseDown={e=>{if(e.currentTarget===e.target)setOpen(false)}}><form className="panel finance-modal finance-advanced-modal" onSubmit={createRule}><div className="finance-modal-header"><div><span className="eyebrow">Regra de comissão</span><h2>Nova regra</h2><p>A regra pode ser alterada ou desativada depois, mantendo entradas já geradas rastreáveis.</p></div><button type="button" onClick={()=>setOpen(false)}>×</button></div><label><span>Nome</span><input value={name} onChange={e=>setName(e.target.value)} required/></label><div className="form-grid two-columns"><label><span>Evento</span><select value={eventType} onChange={e=>setEventType(e.target.value)}><option value="first_rent">Primeiro aluguel</option><option value="recurring">Recorrente</option><option value="intermediation">Intermediação</option></select></label><label><span>Base</span><select value={basis} onChange={e=>setBasis(e.target.value)}><option value="agency_revenue">Receita da imobiliária</option><option value="rent">Aluguel</option><option value="administration_fee">Taxa de administração</option><option value="intermediation_fee">Intermediação</option></select></label><label><span>Cálculo</span><select value={calc} onChange={e=>setCalc(e.target.value)}><option value="percent">Percentual</option><option value="fixed">Valor fixo</option></select></label><label><span>{calc==='percent'?'Percentual (%)':'Valor (R$)'}</span><input value={value} onChange={e=>setValue(e.target.value)} required/></label><label><span>Tipo</span><select value={beneficiaryType} onChange={e=>setBeneficiaryType(e.target.value)}><option value="broker">Corretor</option><option value="referrer">Angariador</option><option value="other">Outro</option></select></label><label><span>Beneficiário</span><select value={personId} onChange={e=>setPersonId(e.target.value)} required><option value="">Selecione...</option>{people.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label><label><span>Vencimento após recebimento</span><input type="number" min="0" max="180" value={dueDays} onChange={e=>setDueDays(e.target.value)}/></label></div><div className="finance-modal-actions"><button className="button secondary" type="button" onClick={()=>setOpen(false)}>Cancelar</button><button className="button primary" disabled={saving}>Salvar regra</button></div></form></div>}
 </section>
}
