import { AlertTriangle, CalendarDays, CheckCircle2, ChevronLeft, ChevronRight, FileText, History, ReceiptText, RefreshCw, Search, Send, WalletCards, X } from 'lucide-react'
import { FormEvent, useCallback, useEffect, useMemo, useRef, useState } from 'react'
import { ApiError, apiRequest } from '../../api/client'
import { shiftMonth } from './finance-period'
import './finance-receivables.css'
type Charge={id:string;code:string;lease_code:string;property_code:string;property_address:Record<string,string>;tenants:Array<{name?:string}>;competence:string;due_date:string;status:string;days_overdue:number;critical_overdue:boolean;rent_amount:number;gross_amount:number;updated_amount:number;amount_as_of:string;late_fee_percent:number;late_interest_percent_monthly:number;late_fee_amount:number;late_interest_amount:number;charge_items:Array<{key:string;label:string;amount:number}>;sent_at:string|null;paid_at:string|null;paid_amount:number|null;payment_method:string|null;payment_reference:string|null;settlement:{agency_fee_withheld:number;repasses:Array<{id:string;owner_name:string;amount:number;status:string}>}|null;created_at:string}
type Tab='overview'|'composition'|'payments'|'history'
const money=(v:number|null|undefined)=>Number(v||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'})
const date=(v:string|null|undefined)=>v?new Date(v.slice(0,10)+'T12:00:00').toLocaleDateString('pt-BR'):'—'
const when=(v:string|null|undefined)=>v?new Date(v).toLocaleString('pt-BR'):'—'
const localNow=()=>{const d=new Date();return new Date(d.getTime()-d.getTimezoneOffset()*60000).toISOString().slice(0,16)}
const address=(c:Charge)=>[c.property_address.street,c.property_address.number,c.property_address.neighborhood,c.property_address.city].filter(Boolean).join(', ')||'Endereço não informado'
const labels:Record<string,string>={generated:'Gerada',sent:'Enviada',overdue:'Em atraso',paid:'Recebida',cancelled:'Cancelada'}
const tone=(s:string)=>s==='paid'?'success':s==='overdue'?'danger':'neutral'
export function FinanceReceivablesPanel({permissions,month,setMonth}:{permissions:string[];month:string;setMonth:(next:string|((month:string)=>string))=>void}){
 const requestId=useRef(0)
 const [items,setItems]=useState<Charge[]>([]),[selectedId,setSelectedId]=useState<string|null>(null)
 const [query,setQuery]=useState(''),[status,setStatus]=useState('all'),[tab,setTab]=useState<Tab>('overview')
 const [loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[error,setError]=useState(''),[success,setSuccess]=useState('')
 const [payOpen,setPayOpen]=useState(false),[amount,setAmount]=useState(''),[paidAt,setPaidAt]=useState(localNow()),[method,setMethod]=useState('pix'),[reference,setReference]=useState('')
 const canGenerate=permissions.includes('finance.charge.create'),canReconcile=permissions.includes('finance.reconcile'),competence=month+'-01'
 const load=useCallback(async()=>{
  const request=++requestId.current
  setLoading(true);setError('')
  try{
    const result=await apiRequest<Charge[]>('/finance/charges?competence='+competence)
    if(request===requestId.current)setItems(result)
  }catch(e){
    if(request===requestId.current)setError(e instanceof ApiError?e.detail:'Erro ao carregar cobranças.')
  }finally{if(request===requestId.current)setLoading(false)}
 },[competence])
 useEffect(()=>{void load();return()=>{requestId.current+=1}},[load])
 const filtered=useMemo(()=>items.filter(c=>(status==='all'||c.status===status)&&(!query.trim()||[c.code,c.lease_code,c.property_code,address(c),...c.tenants.map(t=>t.name||'')].join(' ').toLocaleLowerCase('pt-BR').includes(query.trim().toLocaleLowerCase('pt-BR')))),[items,status,query])
 useEffect(()=>{if(!filtered.length)setSelectedId(null);else if(!selectedId||!filtered.some(c=>c.id===selectedId))setSelectedId(filtered[0].id)},[filtered,selectedId])
 const selected=filtered.find(c=>c.id===selectedId)||null
 useEffect(()=>{setPayOpen(false)},[selectedId,month])
 const metrics=useMemo(()=>({due:items.filter(c=>!['paid','cancelled'].includes(c.status)).reduce((a,c)=>a+Number(c.updated_amount||0),0),paid:items.filter(c=>c.status==='paid').reduce((a,c)=>a+Number(c.paid_amount||0),0),overdue:items.filter(c=>c.status==='overdue').reduce((a,c)=>a+Number(c.updated_amount||0),0),count:items.length}),[items])
 async function generate(){setSaving(true);setError('');setSuccess('');try{const r=await apiRequest<{generated:number}>('/finance/charges/generate',{method:'POST',body:JSON.stringify({competence})});await load();setSuccess(String(r.generated)+' cobrança(s) gerada(s).')}catch(e){setError(e instanceof ApiError?e.detail:'Erro ao gerar mês.')}finally{setSaving(false)}}
 async function sent(c:Charge){setSaving(true);setError('');setSuccess('');try{await apiRequest('/finance/charges/'+c.id+'/mark-sent',{method:'POST'});await load();setSuccess(c.code+' marcada como enviada.')}catch(e){setError(e instanceof ApiError?e.detail:'Erro ao registrar envio.')}finally{setSaving(false)}}
 async function receive(e:FormEvent){e.preventDefault();if(!selected)return;const value=Number(amount.replace(',','.'));if(!Number.isFinite(value)||value<=0||!paidAt){setError('Informe valor e data válidos.');return}setSaving(true);setError('');setSuccess('');try{await apiRequest('/finance/charges/'+selected.id+'/payment',{method:'POST',body:JSON.stringify({paid_amount:value,paid_at:new Date(paidAt).toISOString(),payment_method:method,payment_reference:reference||null})});setPayOpen(false);await load();setSuccess(selected.code+' recebida e liquidada.')}catch(err){setError(err instanceof ApiError?err.detail:'Não foi possível baixar a cobrança.')}finally{setSaving(false)}}
 return <section className="workspace finance-receivables">
  <div className="page-heading finance-heading"><div><span className="eyebrow">FINANCEIRO · CONTAS A RECEBER</span><h1>Cobranças</h1><p>Contrato, locatário, valor atualizado, recebimentos e histórico.</p></div><div className="heading-actions"><button className="icon-button" type="button" aria-label="Mês anterior" onClick={()=>setMonth(m=>shiftMonth(m,-1))}><ChevronLeft size={16}/></button><label className="finance-month"><CalendarDays size={15}/><input type="month" value={month} onChange={e=>setMonth(e.target.value)}/></label><button className="icon-button" type="button" aria-label="Mês seguinte" onClick={()=>setMonth(m=>shiftMonth(m,1))}><ChevronRight size={16}/></button><button className="button secondary" type="button" disabled={loading} onClick={()=>void load()}><RefreshCw size={14}/> Atualizar</button>{canGenerate&&<button className="button primary" type="button" disabled={saving||loading} onClick={()=>void generate()}><ReceiptText size={14}/> Gerar mês</button>}</div></div>
  {error&&<div role="alert" className="form-alert danger-alert">{error}</div>}{success&&<div role="status" className="form-alert success-alert">{success}</div>}
  <div className="receivables-metrics"><article className="panel"><span>A receber</span><strong>{money(metrics.due)}</strong><small>Valor atualizado</small></article><article className="panel"><span>Recebido</span><strong>{money(metrics.paid)}</strong><small>Baixas da competência</small></article><article className="panel"><span>Em atraso</span><strong>{money(metrics.overdue)}</strong><small>Valores vencidos</small></article><article className="panel"><span>Cobranças</span><strong>{metrics.count}</strong><small>Registros da competência</small></article></div>
  <div className="receivables-master"><aside className="panel receivables-directory"><label className="receivables-search"><Search size={15}/><input aria-label="Buscar cobrança" placeholder="Buscar cobrança, imóvel, contrato..." value={query} onChange={e=>setQuery(e.target.value)}/></label><select aria-label="Situação" value={status} onChange={e=>setStatus(e.target.value)}><option value="all">Todos os status</option><option value="generated">Geradas</option><option value="sent">Enviadas</option><option value="overdue">Em atraso</option><option value="paid">Recebidas</option><option value="cancelled">Canceladas</option></select><small>{filtered.length} de {items.length} cobrança(s)</small><div className="receivables-list">{filtered.map(c=><button type="button" key={c.id} aria-pressed={selectedId===c.id} className={'receivables-row '+(selectedId===c.id?'active':'')} onClick={()=>{setSelectedId(c.id);setTab('overview')}}><span className="receivables-row-head"><strong>{c.code}</strong><i className={'status-badge '+tone(c.status)}>{labels[c.status]||c.status}</i></span><b>{c.tenants.map(t=>t.name).filter(Boolean).join(' / ')||'Locatário não informado'}</b><small title={address(c)}>Imóvel #{c.property_code} · {address(c)}</small><span className="receivables-row-head"><strong>{money(c.status==='paid'?c.paid_amount:c.updated_amount)}</strong><small>Venc. {date(c.due_date)}</small></span></button>)}{!loading&&!filtered.length&&<p>Nenhuma cobrança para estes filtros.</p>}</div></aside>
  <div className="panel receivables-detail">{loading?<div className="receivables-empty">Carregando...</div>:!selected?<div className="receivables-empty">Selecione uma cobrança para visualizar os detalhes.</div>:<>
   <header className="receivables-header"><div><span className="eyebrow">{selected.lease_code} · IMÓVEL #{selected.property_code}</span><h2>{selected.code} <i className={'status-badge '+tone(selected.status)}>{labels[selected.status]||selected.status}</i></h2><p>{address(selected)}</p></div><div className="receivables-actions">{canGenerate&&['generated','overdue'].includes(selected.status)&&<button type="button" className="button secondary" disabled={saving} onClick={()=>void sent(selected)}><Send size={14}/> Marcar enviada</button>}{canReconcile&&!['paid','cancelled'].includes(selected.status)&&<button type="button" className="button primary" disabled={saving} onClick={()=>{setAmount(Number(selected.updated_amount).toFixed(2));setPaidAt(localNow());setPayOpen(true)}}><CheckCircle2 size={14}/> Confirmar recebimento</button>}</div></header>
   <div className="receivables-facts"><div><span>Locatário</span><strong>{selected.tenants.map(t=>t.name).filter(Boolean).join(' / ')||'—'}</strong></div><div><span>Vencimento</span><strong>{date(selected.due_date)}</strong></div><div><span>Valor original</span><strong>{money(selected.gross_amount)}</strong></div><div><span>Valor atualizado</span><strong>{money(selected.updated_amount)}</strong></div></div>
   <nav className="receivables-tabs" aria-label="Abas da cobrança"><button type="button" className={tab==='overview'?'active':''} onClick={()=>setTab('overview')}><FileText size={14}/> Visão geral</button><button type="button" className={tab==='composition'?'active':''} onClick={()=>setTab('composition')}><ReceiptText size={14}/> Composição</button><button type="button" className={tab==='payments'?'active':''} onClick={()=>setTab('payments')}><WalletCards size={14}/> Pagamentos</button><button type="button" className={tab==='history'?'active':''} onClick={()=>setTab('history')}><History size={14}/> Histórico</button></nav>
   <div className="receivables-body">{tab==='overview'&&<div className="receivables-overview"><article className="receivables-card"><h3>Condições principais</h3><div className="receivables-cells"><div><span>Contrato</span><strong>{selected.lease_code}</strong></div><div><span>Competência</span><strong>{date(selected.competence)}</strong></div><div><span>Aluguel base</span><strong>{money(selected.rent_amount)}</strong></div><div><span>Encargos</span><strong>{money(selected.gross_amount-selected.rent_amount)}</strong></div><div><span>Multa e juros</span><strong>{money(selected.late_fee_amount+selected.late_interest_amount)}</strong></div><div><span>Enviada</span><strong>{when(selected.sent_at)}</strong></div></div></article><article className="receivables-card"><h3>Situação</h3><div className="receivables-lines"><div><span>Dias em atraso</span><strong>{selected.days_overdue}</strong></div><div><span>Atualizado em</span><strong>{date(selected.amount_as_of)}</strong></div><div><span>Recebido</span><strong>{money(selected.paid_amount)}</strong></div>{selected.critical_overdue&&<div><AlertTriangle size={15}/> Atraso crítico</div>}</div></article></div>}
   {tab==='composition'&&<article className="receivables-card"><h3>Composição do valor</h3><div className="receivables-lines"><div><span>Aluguel base</span><strong>{money(selected.rent_amount)}</strong></div>{selected.charge_items.map((i,index)=><div key={i.key+'-'+index}><span>{i.label}</span><strong>{money(i.amount)}</strong></div>)}<div><span>Multa ({selected.late_fee_percent}%)</span><strong>{money(selected.late_fee_amount)}</strong></div><div><span>Juros ({selected.late_interest_percent_monthly}% a.m.)</span><strong>{money(selected.late_interest_amount)}</strong></div><div className="total"><span>Total atualizado</span><strong>{money(selected.updated_amount)}</strong></div></div></article>}
   {tab==='payments'&&<article className="receivables-card"><h3>Baixa e liquidação</h3><div className="receivables-cells"><div><span>Recebido</span><strong>{money(selected.paid_amount)}</strong></div><div><span>Pago em</span><strong>{when(selected.paid_at)}</strong></div><div><span>Meio de pagamento</span><strong>{selected.payment_method||'—'}</strong></div><div><span>Referência</span><strong>{selected.payment_reference||'—'}</strong></div><div><span>Retenção da imobiliária</span><strong>{money(selected.settlement?.agency_fee_withheld)}</strong></div></div>{selected.settlement&&<div className="receivables-lines"><h3>Repasses</h3>{selected.settlement.repasses.map(r=><div key={r.id}><span>{r.owner_name} · {r.status}</span><strong>{money(r.amount)}</strong></div>)}</div>}</article>}
   {tab==='history'&&<article className="receivables-card"><h3>Eventos registrados</h3><div className="receivables-lines"><div><span>Criação</span><strong>{when(selected.created_at)}</strong></div>{selected.sent_at&&<div><span>Envio</span><strong>{when(selected.sent_at)}</strong></div>}{selected.paid_at&&<div><span>Recebimento</span><strong>{when(selected.paid_at)}</strong></div>}</div><p>Contatos de cobrança e ações de inadimplência permanecem no módulo de Inadimplência.</p></article>}</div>
  </>}</div></div>
  {payOpen&&selected&&<div className="finance-modal-backdrop"><form className="panel finance-modal receivables-pay" onSubmit={receive}><div className="finance-modal-header"><div><h2>Confirmar recebimento</h2><p>{selected.code} · {money(selected.updated_amount)}</p></div><button type="button" aria-label="Fechar" disabled={saving} onClick={()=>setPayOpen(false)}><X size={18}/></button></div><div className="receivables-fields"><label>Valor recebido<input required inputMode="decimal" value={amount} onChange={e=>setAmount(e.target.value)}/></label><label>Data e hora<input type="datetime-local" required value={paidAt} onChange={e=>setPaidAt(e.target.value)}/></label><label>Meio<select value={method} onChange={e=>setMethod(e.target.value)}><option value="pix">Pix</option><option value="bank_transfer">Transferência</option><option value="boleto">Boleto</option><option value="cash">Dinheiro</option></select></label><label>Referência<input value={reference} onChange={e=>setReference(e.target.value)}/></label></div><div className="form-actions"><button type="button" className="button secondary" disabled={saving} onClick={()=>setPayOpen(false)}>Cancelar</button><button type="submit" disabled={saving} className="button primary">{saving?'Registrando...':'Confirmar baixa'}</button></div></form></div>}
 </section>
}
