import {
  ArrowDownCircle,
  ArrowUpCircle,
  Building2,
  CheckCircle2,
  ChevronLeft,
  ChevronRight,
  FileUp,
  History,
  Landmark,
  Link2,
  Plus,
  RefreshCw,
  Search,
  WalletCards,
  X,
} from 'lucide-react'
import { FormEvent, useCallback, useEffect, useMemo, useState } from 'react'
import { ApiError, apiRequest } from '../../api/client'
import { shiftMonth } from './finance-period'
import './finance-banking.css'
import './finance-banking-polish.css'

type FundScope='operating'|'third_party'
type Account={id:string;code:string;name:string;bank_name:string;bank_code:string|null;branch:string|null;account_number:string|null;account_digit:string|null;account_type:string;fund_scope:FundScope;provider:string;pix_key:string|null;opening_balance:number;current_balance:number;is_active:boolean;last_sync_at:string|null;created_at:string}
type Allocation={id:string;target_type:string;target_id:string;target_code:string;target_direction:string;amount:number;notes:string|null;reconciled_at:string}
type Transaction={id:string;code:string;bank_account_id:string;transaction_date:string;posted_at:string|null;direction:'credit'|'debit';amount:number;description:string;document:string|null;counterparty_name:string|null;bank_reference:string|null;balance_after:number|null;source:string;status:string;reconciled_amount:number;remaining_amount:number;reconciliations:Allocation[];created_at:string}
type Overview={account:Account;competence:string;credits_amount:number;debits_amount:number;pending_credits_amount:number;pending_debits_amount:number;reconciled_amount:number;pending_count:number;reconciled_count:number;transactions:Transaction[]}
type Candidate={target_type:string;target_id:string;target_code:string;direction:'receivable'|'payable';fund_scope:FundScope;description:string;counterparty_name:string;due_date:string|null;remaining_amount:number;transaction_remaining_amount:number;suggested_allocation:number;difference_amount:number;difference_kind:'exact'|'bank_excess'|'title_exceeds_bank';settlement_compatible:boolean;score:number;identifier_match:boolean;matched_identifier:string|null}
type ReconciliationException={id:string;transaction_id:string;transaction_code:string;transaction_date:string;direction:'credit'|'debit';amount:number;remaining_amount:number;description:string;bank_reference:string|null;reason:'ambiguous_identifier'|'identifier_detected'|'strong_candidate'|'review_required'|'no_candidate';severity:'routine'|'exception';status:'open'|'ignored'|'resolved';reason_label:string;candidate_count:number;top_candidate_code:string|null;top_candidate_score:number|null;matched_identifier:string|null;resolution_note:string|null;resolved_at:string|null;updated_at:string}
type BankProvider={key:string;name:string;direct_integration:boolean;capabilities:{statement:boolean;balance:boolean;billing:boolean;pix_payment:boolean}}
type ImportHistory={import_id:string;filename:string;source:string;total_rows:number;created_rows:number;duplicate_rows:number;imported_at:string}
type ReconciliationSummary={pending_count:number;routine_count:number;exception_count:number;ignored_count:number;deterministic_count:number;strong_candidate_count:number;ambiguous_count:number;review_required_count:number;no_candidate_count:number}

const statusLabel:Record<string,string>={pending:'Pendente',partial:'Parcial',reconciled:'Conciliado'}
const targetLabel:Record<string,string>={rent:'Locação',owner_repasse:'Repasse',maintenance:'Manutenção',manual:'Manual',financial_title:'Título financeiro'}
const exceptionLabel:Record<ReconciliationException['reason'],string>={ambiguous_identifier:'Referência ambígua',identifier_detected:'Identificador encontrado',strong_candidate:'Candidato forte',review_required:'Revisão necessária',no_candidate:'Sem candidato'}
function money(value:number|null|undefined){return Number(value||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'})}
function dateLabel(value:string|null|undefined){if(!value)return '—';return new Date(`${value.slice(0,10)}T12:00:00`).toLocaleDateString('pt-BR')}
function dateTimeLabel(value:string|null|undefined){if(!value)return '—';return new Date(value).toLocaleString('pt-BR',{dateStyle:'short',timeStyle:'short'})}
function currentMonth(){const now=new Date();return `${now.getFullYear()}-${String(now.getMonth()+1).padStart(2,'0')}`}
function today(){const now=new Date();const offset=now.getTimezoneOffset();return new Date(now.getTime()-offset*60000).toISOString().slice(0,10)}
function normalizeMoneyInput(value:string){const normalized=value.trim().replace(/\./g,'').replace(',','.');const parsed=Number(normalized||0);return Number.isFinite(parsed)?parsed.toLocaleString('pt-BR',{minimumFractionDigits:2,maximumFractionDigits:2}):'0,00'}
function moneyInputNumber(value:string){const normalized=value.trim().replace(/\./g,'').replace(',','.');const parsed=Number(normalized);return Number.isFinite(parsed)?parsed:0}

export function FinanceBankingPanel({permissions}:{permissions:string[]}){
  const canReconcile=permissions.includes('finance.reconcile'),canApprovePayment=permissions.includes('finance.payment.approve'),canAdjust=permissions.includes('finance.adjustment.create')
  const [month,setMonth]=useState(currentMonth()),[accounts,setAccounts]=useState<Account[]>([]),[providers,setProviders]=useState<BankProvider[]>([]),[selectedId,setSelectedId]=useState(''),[overview,setOverview]=useState<Overview|null>(null),[exceptions,setExceptions]=useState<ReconciliationException[]>([]),[summary,setSummary]=useState<ReconciliationSummary|null>(null),[imports,setImports]=useState<ImportHistory[]>([]),[historyOpen,setHistoryOpen]=useState(false),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[error,setError]=useState(''),[success,setSuccess]=useState(''),[filter,setFilter]=useState<'all'|'pending'|'exceptions'|'credit'|'debit'>('all'),[selectedTransactionId,setSelectedTransactionId]=useState<string|null>(null)
  const [accountOpen,setAccountOpen]=useState(false),[accountName,setAccountName]=useState(''),[bankName,setBankName]=useState(''),[bankCode,setBankCode]=useState(''),[bankProvider,setBankProvider]=useState('manual'),[branch,setBranch]=useState(''),[accountNumber,setAccountNumber]=useState(''),[accountDigit,setAccountDigit]=useState(''),[accountScope,setAccountScope]=useState<FundScope>('operating'),[openingBalance,setOpeningBalance]=useState('0,00')
  const [moveOpen,setMoveOpen]=useState(false),[moveDate,setMoveDate]=useState(today()),[moveDirection,setMoveDirection]=useState<'credit'|'debit'>('credit'),[moveAmount,setMoveAmount]=useState(''),[moveDescription,setMoveDescription]=useState(''),[moveReference,setMoveReference]=useState('')
  const [importOpen,setImportOpen]=useState(false),[importFile,setImportFile]=useState<File|null>(null),[reconcileTx,setReconcileTx]=useState<Transaction|null>(null),[candidates,setCandidates]=useState<Candidate[]>([]),[candidateLoading,setCandidateLoading]=useState(false),[candidateQuery,setCandidateQuery]=useState('')
  const [adjustTx,setAdjustTx]=useState<Transaction|null>(null),[adjustCategory,setAdjustCategory]=useState<'bank_fee'|'interest'|'penalty'|'discount'|'revenue'|'expense'|'adjustment'>('adjustment'),[adjustDescription,setAdjustDescription]=useState(''),[adjustAmount,setAdjustAmount]=useState('')
  const competence=`${month}-01`
  const loadAccounts=useCallback(async(preferredId?:string)=>{const items=await apiRequest<Account[]>('/finance/banking/accounts');setAccounts(items);const next=preferredId||selectedId||items[0]?.id||'';if(next&&items.some(item=>item.id===next))setSelectedId(next);else setSelectedId(items[0]?.id||'');return next},[selectedId])
  const loadOverview=useCallback(async(accountId?:string)=>{const id=accountId||selectedId;if(!id){setOverview(null);setExceptions([]);setSummary(null);setLoading(false);return}setLoading(true);setError('');try{const [nextOverview,nextExceptions,nextSummary]=await Promise.all([apiRequest<Overview>(`/finance/banking/overview?account_id=${id}&competence=${competence}`),apiRequest<ReconciliationException[]>(`/finance/banking/exceptions?account_id=${id}&competence=${competence}`),apiRequest<ReconciliationSummary>(`/finance/banking/reconciliation-summary?account_id=${id}&competence=${competence}`)]);setOverview(nextOverview);setExceptions(nextExceptions);setSummary(nextSummary)}catch(cause){setError(cause instanceof ApiError?cause.detail:'Não foi possível carregar o extrato bancário.')}finally{setLoading(false)}},[selectedId,competence])
  useEffect(()=>{void loadAccounts().catch(cause=>{setError(cause instanceof ApiError?cause.detail:'Não foi possível carregar as contas bancárias.');setLoading(false)})/* eslint-disable-next-line react-hooks/exhaustive-deps */},[])
  useEffect(()=>{if(selectedId)void loadOverview(selectedId)},[selectedId,competence,loadOverview])
  useEffect(()=>{if(!accountOpen||providers.length)return;void apiRequest<BankProvider[]>('/finance/banking/providers').then(items=>{setProviders(items);if(items.length&&!items.some(item=>item.key===bankProvider))setBankProvider(items[0].key)}).catch(cause=>setError(cause instanceof ApiError?cause.detail:'Não foi possível carregar os providers bancários.'))},[accountOpen,providers.length,bankProvider])
  useEffect(()=>{if(!historyOpen||!selectedId)return;setImports([]);void apiRequest<ImportHistory[]>(`/finance/banking/accounts/${selectedId}/imports?limit=8`).then(setImports).catch(cause=>setError(cause instanceof ApiError?cause.detail:'Não foi possível carregar o histórico de importações.'))},[historyOpen,selectedId])
  const selected=useMemo(()=>accounts.find(item=>item.id===selectedId)||overview?.account||null,[accounts,selectedId,overview])
  const transactions=useMemo(()=>{const all=overview?.transactions||[];if(filter==='all')return all;if(filter==='pending')return all.filter(item=>item.remaining_amount>0);if(filter==='exceptions'){const ids=new Set(exceptions.map(item=>item.transaction_id));return all.filter(item=>ids.has(item.id))}return all.filter(item=>item.direction===filter)},[overview,filter,exceptions])
  const exceptionByTransaction=useMemo(()=>new Map(exceptions.map(item=>[item.transaction_id,item])),[exceptions])
  const activeTransaction=transactions.find(item=>item.id===selectedTransactionId)||transactions[0]||null
  const activeException=activeTransaction?exceptionByTransaction.get(activeTransaction.id)||null:null
  const pendingAmount=Number(overview?.pending_credits_amount||0)+Number(overview?.pending_debits_amount||0)
  const remainingTotal=(overview?.transactions||[]).reduce((sum,item)=>sum+Number(item.remaining_amount||0),0)
  const visibleCandidates=useMemo(()=>{const query=candidateQuery.trim().toLowerCase();if(!query)return candidates;return candidates.filter(item=>`${item.target_code} ${item.description} ${item.counterparty_name}`.toLowerCase().includes(query))},[candidates,candidateQuery])
  async function refresh(){try{await loadAccounts(selectedId);await loadOverview(selectedId);setSuccess('Dados bancários atualizados.')}catch(cause){setError(cause instanceof ApiError?cause.detail:'Não foi possível atualizar os dados bancários.')}}
  async function createAccount(event:FormEvent){event.preventDefault();setSaving(true);setError('');setSuccess('');try{const created=await apiRequest<Account>('/finance/banking/accounts',{method:'POST',body:JSON.stringify({name:accountName,bank_name:bankName,bank_code:bankCode||null,branch:branch||null,account_number:accountNumber||null,account_digit:accountDigit||null,account_type:'checking',fund_scope:accountScope,provider:bankProvider,opening_balance:moneyInputNumber(openingBalance)})});setAccountOpen(false);setAccountName('');setBranch('');setAccountNumber('');setAccountDigit('');setOpeningBalance('0,00');await loadAccounts(created.id);setSelectedId(created.id);await loadOverview(created.id);setSuccess(`${created.name} cadastrada.`)}catch(cause){setError(cause instanceof ApiError?cause.detail:'Não foi possível cadastrar a conta bancária.')}finally{setSaving(false)}}
  async function createMovement(event:FormEvent){event.preventDefault();if(!selectedId)return;setSaving(true);setError('');setSuccess('');try{await apiRequest(`/finance/banking/accounts/${selectedId}/transactions`,{method:'POST',body:JSON.stringify({transaction_date:moveDate,direction:moveDirection,amount:moneyInputNumber(moveAmount),description:moveDescription,bank_reference:moveReference||null})});setMoveOpen(false);setMoveAmount('');setMoveDescription('');setMoveReference('');await loadOverview(selectedId);await loadAccounts(selectedId);setSuccess('Movimento incluído no extrato.')}catch(cause){setError(cause instanceof ApiError?cause.detail:'Não foi possível incluir o movimento.')}finally{setSaving(false)}}
  async function importStatement(event:FormEvent){event.preventDefault();if(!selectedId||!importFile)return;setSaving(true);setError('');setSuccess('');try{const data=new FormData();data.append('file',importFile);const result=await apiRequest<{created_rows:number;duplicate_rows:number;total_rows:number}>(`/finance/banking/accounts/${selectedId}/import`,{method:'POST',body:data});setImportOpen(false);setImportFile(null);await loadOverview(selectedId);await loadAccounts(selectedId);setSuccess(`${result.created_rows} movimento(s) importado(s). ${result.duplicate_rows} duplicado(s) ignorado(s).`)}catch(cause){setError(cause instanceof ApiError?cause.detail:'Não foi possível importar o extrato.')}finally{setSaving(false)}}
  async function openReconcile(item:Transaction){setReconcileTx(item);setCandidateLoading(true);setCandidates([]);setCandidateQuery('');setError('');try{setCandidates(await apiRequest<Candidate[]>(`/finance/banking/transactions/${item.id}/candidates`))}catch(cause){setError(cause instanceof ApiError?cause.detail:'Não foi possível buscar títulos para conciliação.')}finally{setCandidateLoading(false)}}
  async function reconcile(candidate:Candidate){if(!reconcileTx||!candidate.settlement_compatible)return;setSaving(true);setError('');setSuccess('');try{const amount=candidate.suggested_allocation;const exception=exceptionByTransaction.get(reconcileTx.id);const path=exception?`/finance/banking/exceptions/${exception.id}/resolve`:`/finance/banking/transactions/${reconcileTx.id}/reconcile`;await apiRequest(path,{method:'POST',body:JSON.stringify({target_type:candidate.target_type,target_id:candidate.target_id,amount,note:exception?'Título confirmado manualmente na fila de exceções.':undefined})});const code=reconcileTx.code;setReconcileTx(null);setCandidates([]);await loadOverview(selectedId);await loadAccounts(selectedId);setSuccess(exception?`${code} resolvido e conciliado com ${candidate.target_code}.`:`${code} conciliado com ${candidate.target_code}.`)}catch(cause){setError(cause instanceof ApiError?cause.detail:'Não foi possível concluir a conciliação.')}finally{setSaving(false)}}
  async function classifyResidual(event:FormEvent){event.preventDefault();if(!adjustTx)return;setSaving(true);setError('');setSuccess('');try{await apiRequest(`/finance/banking/transactions/${adjustTx.id}/residual-adjustment`,{method:'POST',body:JSON.stringify({category:adjustCategory,description:adjustDescription,amount:moneyInputNumber(adjustAmount)||adjustTx.remaining_amount,note:'Classificação operacional do saldo residual bancário.'})});const code=adjustTx.code;setAdjustTx(null);setAdjustDescription('');setAdjustAmount('');setAdjustCategory('adjustment');await loadOverview(selectedId);await loadAccounts(selectedId);setSuccess(`${code}: saldo residual classificado e conciliado.`)}catch(cause){setError(cause instanceof ApiError?cause.detail:'Não foi possível classificar o saldo residual.')}finally{setSaving(false)}}
  async function ignoreException(item:ReconciliationException){setSaving(true);setError('');setSuccess('');try{await apiRequest(`/finance/banking/exceptions/${item.id}/ignore`,{method:'POST',body:JSON.stringify({note:'Ignorada pela operação na fila de conciliação.'})});await loadOverview(selectedId);setSuccess(`${item.transaction_code} removido da fila de exceções.`)}catch(cause){setError(cause instanceof ApiError?cause.detail:'Não foi possível ignorar a exceção.')}finally{setSaving(false)}}
  const canConciliateTx=(item:Transaction)=>item.remaining_amount>0&&(item.direction==='credit'?canReconcile:canApprovePayment)

  return <section className="workspace finance-banking-workspace"><div className="page-heading finance-heading"><div><span className="eyebrow">Financeiro · Bancos</span><h1>Contas bancárias e conciliação</h1><p>Extrato real, separação entre recursos próprios e de terceiros e baixa financeira ligada à origem do lançamento.</p></div><div className="heading-actions"><button className="icon-button" type="button" onClick={()=>setMonth(current=>shiftMonth(current,-1))} aria-label="Competência anterior" title="Competência anterior"><ChevronLeft size={16}/></button><label className="finance-month"><input type="month" value={month} onChange={event=>setMonth(event.target.value)}/></label><button className="icon-button" type="button" onClick={()=>setMonth(current=>shiftMonth(current,1))} aria-label="Próxima competência" title="Próxima competência"><ChevronRight size={16}/></button><button className="button secondary" type="button" onClick={()=>void refresh()} disabled={loading}><RefreshCw size={14}/> Atualizar</button>{selected&&<button className="button secondary" type="button" onClick={()=>setHistoryOpen(true)}><History size={14}/> Histórico</button>}{canReconcile&&<button className="button secondary" type="button" onClick={()=>setAccountOpen(true)}><Landmark size={14}/> Nova conta</button>}{selected&&canReconcile&&<button className="button secondary" type="button" onClick={()=>setImportOpen(true)}><FileUp size={14}/> Importar extrato</button>}{selected&&canReconcile&&<button className="button primary" type="button" onClick={()=>{setMoveOpen(true);setMoveDate(today())}}><Plus size={14}/> Movimento</button>}</div></div>
    {accounts.length>0&&<div className="finance-bank-account-strip">{accounts.map(item=><button type="button" key={item.id} className={`panel finance-bank-account ${selectedId===item.id?'active':''}`} onClick={()=>setSelectedId(item.id)}><div><Building2 size={16}/><span>{item.bank_name}</span></div><strong>{item.name}</strong><small>{item.code} · {item.fund_scope==='third_party'?'Recursos de terceiros':'Caixa operacional'}</small><b>{money(item.current_balance)}</b></button>)}</div>}
    {error&&<div className="form-alert danger-alert">{error}</div>}{success&&<div className="form-alert success-alert">{success}</div>}
    {!selected&&!loading?<article className="panel finance-bank-empty"><Landmark size={32}/><strong>Nenhuma conta bancária cadastrada.</strong><span>Cadastre separadamente a conta operacional e a conta usada para valores de proprietários/locatários.</span>{canReconcile&&<button className="button primary" type="button" onClick={()=>setAccountOpen(true)}>Cadastrar primeira conta</button>}</article>:overview&&<>
      <div className="finance-bank-metrics finance-bank-metrics-v82">
        <article className="panel"><span>A conciliar</span><strong>{money(pendingAmount)}</strong><small>{overview.pending_count} movimento(s) pendente(s)</small></article>
        <article className="panel credit"><span>Matches fortes</span><strong>{summary?(summary.deterministic_count+summary.strong_candidate_count):0}</strong><small>{summary?.deterministic_count||0} determinístico(s) · {summary?.strong_candidate_count||0} sugerido(s)</small></article>
        <article className="panel debit"><span>Exceções</span><strong>{summary?.exception_count??exceptions.length}</strong><small>{summary?.ambiguous_count||0} ambígua(s) · {summary?.no_candidate_count||0} sem candidato</small></article>
        <article className="panel"><span>Conciliados</span><strong>{overview.reconciled_count}</strong><small>movimentos fechados na competência</small></article>
        <article className="panel"><span>Diferença pendente</span><strong>{money(remainingTotal)}</strong><small>saldo ainda sem origem financeira</small></article>
      </div>
      <div className="panel finance-bank-toolbar"><div className="finance-filter"><button className={filter==='all'?'active':''} onClick={()=>{setFilter('all');setSelectedTransactionId(null)}}>Todos</button><button className={filter==='pending'?'active':''} onClick={()=>{setFilter('pending');setSelectedTransactionId(null)}}>A conciliar</button><button className={filter==='exceptions'?'active':''} onClick={()=>{setFilter('exceptions');setSelectedTransactionId(null)}}>Exceções ({exceptions.length})</button><button className={filter==='credit'?'active':''} onClick={()=>{setFilter('credit');setSelectedTransactionId(null)}}>Entradas</button><button className={filter==='debit'?'active':''} onClick={()=>{setFilter('debit');setSelectedTransactionId(null)}}>Saídas</button></div><span>{transactions.length} movimento(s)</span></div>
      {loading?<article className="panel settings-loading">Carregando extrato...</article>:transactions.length===0?<article className="panel finance-empty"><WalletCards size={28}/><strong>Nenhum movimento nesta visão.</strong><span>Ajuste o filtro, importe um CSV/OFX ou registre um movimento bancário.</span></article>:<div className="finance-bank-master-detail">
        <aside className="panel finance-bank-queue">
          <div className="finance-bank-queue-head"><div><span className="eyebrow">Fila operacional</span><strong>{transactions.length} movimento(s)</strong></div><small>{selected?.fund_scope==='third_party'?'Recursos de terceiros':'Caixa operacional'}</small></div>
          <div className="finance-bank-queue-list">{transactions.map(item=>{const exception=exceptionByTransaction.get(item.id);return <button type="button" key={item.id} className={'finance-bank-queue-row '+(activeTransaction?.id===item.id?'active ':'')+(item.remaining_amount<=0?'reconciled':'')} onClick={()=>setSelectedTransactionId(item.id)}>
            <span className={'finance-bank-queue-direction '+item.direction}>{item.direction==='credit'?<ArrowDownCircle size={14}/>:<ArrowUpCircle size={14}/>}</span>
            <span className="finance-bank-queue-copy"><span><strong>{item.code}</strong><i className={'status-badge '+(item.remaining_amount<=0?'success':'warning')}>{item.remaining_amount<=0?'Conciliado':exception?exceptionLabel[exception.reason]:'Pendente'}</i></span><b>{item.description}</b><small>{item.counterparty_name||item.bank_reference||'Sem contraparte'} · {dateLabel(item.transaction_date)}</small></span>
            <span className="finance-bank-queue-value"><strong>{money(item.amount)}</strong>{item.remaining_amount>0?<small>{money(item.remaining_amount)} restante</small>:<small>zerado</small>}</span>
          </button>})}</div>
        </aside>
        {activeTransaction&&<main className="panel finance-bank-detail">
          <header className="finance-bank-detail-head"><div><span className="eyebrow">MOVIMENTO · {activeTransaction.code}</span><h2>{activeTransaction.description}</h2><p>{activeTransaction.counterparty_name||'Contraparte não informada'} · {activeTransaction.source.toUpperCase()} · {dateLabel(activeTransaction.transaction_date)}</p></div><div><i className={'status-badge '+(activeTransaction.remaining_amount<=0?'success':'warning')}>{activeTransaction.remaining_amount<=0?'Conciliado':activeException?exceptionLabel[activeException.reason]:'A conciliar'}</i><strong className={activeTransaction.direction==='credit'?'positive':'negative'}>{money(activeTransaction.amount)}</strong></div></header>
          <div className="finance-bank-detail-strip"><div><span>Conciliado</span><strong>{money(activeTransaction.reconciled_amount)}</strong></div><div><span>Saldo restante</span><strong>{money(activeTransaction.remaining_amount)}</strong></div><div><span>Referência bancária</span><strong>{activeTransaction.bank_reference||activeTransaction.document||'—'}</strong></div><div><span>Natureza</span><strong>{activeTransaction.direction==='credit'?'Entrada':'Saída'}</strong></div></div>
          {activeException&&<div className="finance-bank-detail-alert"><div><strong>{exceptionLabel[activeException.reason]}</strong><span>{activeException.reason_label}</span></div>{activeException.top_candidate_code&&<small>Melhor candidato: {activeException.top_candidate_code}{activeException.top_candidate_score!=null?' · score '+activeException.top_candidate_score:''}</small>}</div>}
          <section className="finance-bank-detail-section"><div className="finance-bank-detail-title"><div><span className="eyebrow">Origem financeira</span><h3>Para onde esse movimento foi conciliado</h3></div><strong>{activeTransaction.reconciliations.length}</strong></div>
            {activeTransaction.reconciliations.length?<div className="finance-bank-allocation-list">{activeTransaction.reconciliations.map(link=><article key={link.id}><div><Link2 size={13}/><span><strong>{link.target_code}</strong><small>{targetLabel[link.target_type]||link.target_type}</small></span></div><strong>{money(link.amount)}</strong><small>{dateTimeLabel(link.reconciled_at)}</small></article>)}</div>:<div className="finance-bank-detail-empty"><Link2 size={20}/><strong>Nenhuma origem vinculada.</strong><span>Use a conciliação para ligar o movimento à locação, repasse, comissão, manutenção ou título correspondente.</span></div>}
          </section>
          {activeTransaction.remaining_amount>0&&activeTransaction.reconciled_amount>0&&<div className="finance-bank-residual"><div><strong>Saldo residual</strong><span>{money(activeTransaction.remaining_amount)} ainda precisa ser classificado ou conciliado. O ERP não absorve diferenças automaticamente.</span></div></div>}
          <div className="finance-bank-detail-actions">{canConciliateTx(activeTransaction)&&<button className="button primary" type="button" onClick={()=>void openReconcile(activeTransaction)}><CheckCircle2 size={14}/>{activeException?' Resolver pendência':' Conciliar movimento'}</button>}{activeTransaction.remaining_amount>0&&activeTransaction.reconciled_amount>0&&canAdjust&&canConciliateTx(activeTransaction)&&<button className="button secondary" type="button" onClick={()=>{setAdjustTx(activeTransaction);setAdjustAmount(String(activeTransaction.remaining_amount).replace('.',','));setAdjustDescription('Classificação do saldo residual')}}>Classificar residual</button>}{activeException&&canReconcile&&<button className="button secondary" type="button" disabled={saving} onClick={()=>void ignoreException(activeException)}>Ignorar exceção</button>}</div>
        </main>}
      </div>}
    </>}
    {accountOpen&&<div className="finance-modal-backdrop" onMouseDown={event=>{if(event.currentTarget===event.target)setAccountOpen(false)}}><form className="panel finance-modal finance-bank-account-modal" onSubmit={createAccount} role="dialog" aria-modal="true"><div className="finance-modal-header"><div><span className="eyebrow">Conta bancária</span><h2>Nova conta</h2><p>Cadastre a conta uma única vez. A natureza mantém recursos próprios e valores de terceiros separados.</p></div><button type="button" aria-label="Fechar" onClick={()=>setAccountOpen(false)}><X size={17}/></button></div><div className="form-grid two-columns finance-bank-account-form"><label className="field"><span>Nome da conta</span><input required value={accountName} onChange={e=>setAccountName(e.target.value)} placeholder="Ex.: Inter · Operacional"/></label><label className="field"><span>Natureza</span><select value={accountScope} onChange={e=>setAccountScope(e.target.value as FundScope)}><option value="operating">Operacional</option><option value="third_party">Recursos de terceiros</option></select></label><label className="field"><span>Banco</span><input required value={bankName} onChange={e=>setBankName(e.target.value)} placeholder="Ex.: Itaú, Santander, Sicredi"/></label><label className="field"><span>Integração</span><select value={bankProvider} onChange={e=>setBankProvider(e.target.value)}>{providers.map(item=><option key={item.key} value={item.key}>{item.name}{item.direct_integration?' · API':' · arquivo/manual'}</option>)}</select><small>{bankProvider==='manual'?'Funciona com CSV/OFX e lançamentos manuais, independente do banco.':'Provider instalado para automações bancárias.'}</small></label><label className="field"><span>Código do banco</span><input value={bankCode} onChange={e=>setBankCode(e.target.value)} placeholder="077"/></label><label className="field"><span>Agência</span><input value={branch} onChange={e=>setBranch(e.target.value)} placeholder="0001"/></label><label className="field"><span>Conta</span><div className="finance-bank-account-number"><input value={accountNumber} onChange={e=>setAccountNumber(e.target.value)} placeholder="00000000"/><input value={accountDigit} onChange={e=>setAccountDigit(e.target.value)} placeholder="DV"/></div></label><label className="field full"><span>Saldo inicial</span><input inputMode="decimal" data-format="money" value={openingBalance} onChange={e=>setOpeningBalance(e.target.value)} onBlur={()=>setOpeningBalance(current=>normalizeMoneyInput(current))} placeholder="0,00"/></label></div><div className="form-actions"><button className="button secondary" type="button" onClick={()=>setAccountOpen(false)}>Cancelar</button><button className="button primary" disabled={saving}>Salvar conta</button></div></form></div>}
    {moveOpen&&<div className="finance-modal-backdrop" onMouseDown={event=>{if(event.currentTarget===event.target)setMoveOpen(false)}}><form className="panel finance-modal" onSubmit={createMovement} role="dialog" aria-modal="true"><div className="finance-modal-header"><div><span className="eyebrow">Extrato</span><h2>Novo movimento</h2><p>Use para lançamentos bancários ainda não importados pelo arquivo ou integração.</p></div><button type="button" aria-label="Fechar" onClick={()=>setMoveOpen(false)}><X size={17}/></button></div><div className="form-grid two-columns"><label><span>Data</span><input type="date" required value={moveDate} onChange={e=>setMoveDate(e.target.value)}/></label><label><span>Tipo</span><select value={moveDirection} onChange={e=>setMoveDirection(e.target.value as 'credit'|'debit')}><option value="credit">Entrada</option><option value="debit">Saída</option></select></label><label className="full"><span>Descrição</span><input required value={moveDescription} onChange={e=>setMoveDescription(e.target.value)} placeholder="Histórico do extrato"/></label><label><span>Valor</span><input required inputMode="decimal" value={moveAmount} onChange={e=>setMoveAmount(e.target.value)} placeholder="0,00"/></label><label><span>Referência bancária</span><input value={moveReference} onChange={e=>setMoveReference(e.target.value)}/></label></div><div className="form-actions"><button className="button secondary" type="button" onClick={()=>setMoveOpen(false)}>Cancelar</button><button className="button primary" disabled={saving}>Adicionar</button></div></form></div>}
    {importOpen&&<div className="finance-modal-backdrop" onMouseDown={event=>{if(event.currentTarget===event.target)setImportOpen(false)}}><form className="panel finance-modal" onSubmit={importStatement} role="dialog" aria-modal="true"><div className="finance-modal-header"><div><span className="eyebrow">Extrato bancário</span><h2>Importar CSV ou OFX</h2><p>Movimentos repetidos são identificados e ignorados automaticamente.</p></div><button type="button" aria-label="Fechar" onClick={()=>setImportOpen(false)}><X size={17}/></button></div><div className="finance-bank-import-box"><FileUp size={28}/><input type="file" required accept=".csv,.ofx,text/csv,application/x-ofx" onChange={e=>setImportFile(e.target.files?.[0]||null)}/><span>{importFile?importFile.name:'Selecione o arquivo do banco'}</span><small>Até 5 MB. Para CSV, use colunas de data, descrição e valor; o sinal do valor identifica entrada/saída quando não houver coluna de tipo.</small></div><div className="form-actions"><button className="button secondary" type="button" onClick={()=>setImportOpen(false)}>Cancelar</button><button className="button primary" disabled={saving||!importFile}>Importar</button></div></form></div>}
    {adjustTx&&<div className="finance-modal-backdrop" onMouseDown={event=>{if(event.currentTarget===event.target)setAdjustTx(null)}}><form className="panel finance-modal" onSubmit={classifyResidual} role="dialog" aria-modal="true"><div className="finance-modal-header"><div><span className="eyebrow">Saldo residual</span><h2>{adjustTx.code} · {money(adjustTx.remaining_amount)}</h2><p>Classifique a diferença sem alterar o principal do título já conciliado.</p></div><button type="button" aria-label="Fechar" onClick={()=>setAdjustTx(null)}><X size={17}/></button></div><div className="form-grid two-columns"><label><span>Classificação</span><select value={adjustCategory} onChange={e=>setAdjustCategory(e.target.value as typeof adjustCategory)}><option value="interest">Juros</option><option value="penalty">Multa</option><option value="discount">Desconto</option><option value="bank_fee">Tarifa bancária</option><option value="revenue">Receita</option><option value="expense">Despesa</option><option value="adjustment">Ajuste</option></select></label><label><span>Valor</span><input required inputMode="decimal" value={adjustAmount} onChange={e=>setAdjustAmount(e.target.value)} /></label><label className="full"><span>Descrição</span><input required minLength={3} value={adjustDescription} onChange={e=>setAdjustDescription(e.target.value)} /></label></div><div className="form-actions"><button className="button secondary" type="button" onClick={()=>setAdjustTx(null)}>Cancelar</button><button className="button primary" disabled={saving}>Classificar e conciliar</button></div></form></div>}
    {historyOpen&&<div className="finance-modal-backdrop" onMouseDown={event=>{if(event.currentTarget===event.target)setHistoryOpen(false)}}><div className="panel finance-modal finance-import-history-modal" role="dialog" aria-modal="true"><div className="finance-modal-header"><div><span className="eyebrow">Extratos bancários</span><h2>Histórico de importações</h2><p>Arquivos idênticos são bloqueados para evitar reprocessamento acidental.</p></div><button type="button" aria-label="Fechar" onClick={()=>setHistoryOpen(false)}><X size={17}/></button></div><div className="finance-import-history-list">{imports.map(item=><article key={item.import_id}><div><strong>{item.filename}</strong><span>{item.source.toUpperCase()} · {dateTimeLabel(item.imported_at)}</span></div><div><b>{item.created_rows}</b><span>novos</span></div><div><b>{item.duplicate_rows}</b><span>duplicados</span></div><div><b>{item.total_rows}</b><span>linhas</span></div></article>)}{imports.length===0&&<div className="finance-reconcile-empty"><strong>Nenhum extrato importado.</strong><span>As próximas importações CSV/OFX aparecerão aqui.</span></div>}</div></div></div>}
    {reconcileTx&&<div className="finance-modal-backdrop" onMouseDown={event=>{if(event.currentTarget===event.target)setReconcileTx(null)}}><div className="panel finance-modal finance-reconcile-modal" role="dialog" aria-modal="true"><div className="finance-modal-header"><div><span className="eyebrow">Conciliação bancária</span><h2>{reconcileTx.code} · {money(reconcileTx.remaining_amount)}</h2><p>{reconcileTx.description}</p></div><button type="button" aria-label="Fechar" onClick={()=>setReconcileTx(null)}><X size={17}/></button></div><div className="finance-reconcile-search"><Search size={14}/><input value={candidateQuery} onChange={e=>setCandidateQuery(e.target.value)} placeholder="Buscar por código, pessoa ou descrição"/></div><div className="finance-reconcile-list">{candidateLoading?<div className="settings-loading">Buscando títulos compatíveis...</div>:visibleCandidates.map(item=><button type="button" className={`finance-reconcile-candidate ${item.settlement_compatible?'':'blocked'}`} key={`${item.target_type}-${item.target_id}`} disabled={saving||!item.settlement_compatible} onClick={()=>void reconcile(item)}><div><strong>{item.target_code}</strong><span>{targetLabel[item.target_type]||item.target_type}</span>{item.identifier_match?<i>Identificado por referência bancária</i>:item.score>=70&&<i>Melhor correspondência</i>}</div><h3>{item.description}</h3><p>{item.counterparty_name} · vence {dateLabel(item.due_date)}</p><div className="finance-reconcile-values"><b>{money(item.remaining_amount)}</b>{item.difference_kind==='exact'?<small>Valor exato do extrato</small>:item.difference_kind==='bank_excess'?<small>Extrato tem {money(item.difference_amount)} a mais · concilia {money(item.suggested_allocation)}</small>:<small>Faltam {money(Math.abs(item.difference_amount))} para liquidar integralmente</small>}</div>{!item.settlement_compatible&&<em>Este título exige liquidação integral; o saldo bancário atual não é suficiente.</em>}</button>)}{!candidateLoading&&visibleCandidates.length===0&&<div className="finance-reconcile-empty"><strong>Nenhum título compatível.</strong><span>A conciliação respeita entrada/saída e também impede misturar conta operacional com recursos de terceiros.</span></div>}</div></div></div>}
  </section>
}