import { ArrowDownCircle, ArrowUpCircle, LockKeyhole, Plus, RefreshCw, Save, Tags, Trash2, X } from 'lucide-react'
import { FormEvent, useCallback, useEffect, useMemo, useState } from 'react'
import { ApiError, apiRequest } from '../../api/client'
import './finance-classifications.css'

type Rule={key:string;label:string;direction:'receivable'|'payable';fund_scope:'operating'|'third_party';category:string;scope_locked:boolean;custom?:boolean;deletable?:boolean}
type Response={rules:Rule[]}

export function FinanceClassificationsPanel({permissions}:{permissions:string[]}){
  const canEdit=permissions.includes('finance.payment.prepare')
  const [rules,setRules]=useState<Rule[]>([])
  const [loading,setLoading]=useState(true),[saving,setSaving]=useState(false)
  const [error,setError]=useState(''),[success,setSuccess]=useState(''),[modalError,setModalError]=useState('')
  const [open,setOpen]=useState(false),[newLabel,setNewLabel]=useState(''),[newDirection,setNewDirection]=useState<'receivable'|'payable'>('receivable'),[newScope,setNewScope]=useState<'operating'|'third_party'>('operating')

  const load=useCallback(async()=>{setLoading(true);setError('');try{setRules((await apiRequest<Response>('/finance/advanced/classifications')).rules)}catch(cause){setError(cause instanceof ApiError?cause.detail:'Não foi possível carregar as classificações financeiras.')}finally{setLoading(false)}},[])
  useEffect(()=>{void load()},[load])
  useEffect(()=>{if(!open)return;const close=(event:KeyboardEvent)=>{if(event.key==='Escape'&&!saving)setOpen(false)};window.addEventListener('keydown',close);return()=>window.removeEventListener('keydown',close)},[open,saving])

  const incoming=useMemo(()=>rules.filter(item=>item.direction==='receivable'),[rules])
  const outgoing=useMemo(()=>rules.filter(item=>item.direction==='payable'),[rules])
  function update(key:string,category:string){setRules(current=>current.map(item=>item.key===key?{...item,category}:item));setSuccess('')}
  async function save(){setSaving(true);setError('');setSuccess('');try{const result=await apiRequest<Response>('/finance/advanced/classifications',{method:'PUT',body:JSON.stringify({rules:rules.map(({key,category})=>({key,category}))})});setRules(result.rules);setSuccess('Classificações gerenciais atualizadas.')}catch(cause){setError(cause instanceof ApiError?cause.detail:'Não foi possível salvar as classificações.')}finally{setSaving(false)}}
  async function create(event:FormEvent){event.preventDefault();setSaving(true);setModalError('');try{const result=await apiRequest<Response>('/finance/advanced/classifications',{method:'POST',body:JSON.stringify({label:newLabel,direction:newDirection,fund_scope:newScope})});setRules(result.rules);setOpen(false);setNewLabel('');setSuccess('Nova categoria financeira criada.')}catch(cause){setModalError(cause instanceof ApiError?cause.detail:'Não foi possível criar a categoria.')}finally{setSaving(false)}}
  async function remove(item:Rule){if(!item.deletable||!window.confirm(`Excluir a categoria “${item.label}”?`))return;setSaving(true);setError('');try{const result=await apiRequest<Response>(`/finance/advanced/classifications/${encodeURIComponent(item.key)}`,{method:'DELETE'});setRules(result.rules);setSuccess('Categoria excluída.')}catch(cause){setError(cause instanceof ApiError?cause.detail:'Não foi possível excluir a categoria.')}finally{setSaving(false)}}

  function group(title:string,items:Rule[],direction:'receivable'|'payable'){
    return <section className="panel finance-classification-group"><div className="finance-classification-heading"><div className={`finance-classification-icon ${direction}`}>{direction==='receivable'?<ArrowDownCircle size={18}/>:<ArrowUpCircle size={18}/>}</div><div><h2>{title}</h2><p>Classificações enxutas para leitura gerencial do caixa.</p></div></div><div className="finance-classification-list">{items.map(item=><div className={`finance-classification-row ${item.custom?'custom':''}`} key={item.key}><div className="finance-classification-meta"><strong>{item.label}</strong><span>{item.fund_scope==='operating'?'Caixa operacional':'Recursos de terceiros'} {item.scope_locked&&<LockKeyhole size={11}/>}</span></div><label><span>Classificação gerencial</span><input value={item.category} disabled={!canEdit} onChange={event=>update(item.key,event.target.value)} /></label>{canEdit&&item.deletable?<button className="finance-classification-delete" type="button" aria-label={`Excluir ${item.label}`} disabled={saving} onClick={()=>void remove(item)}><Trash2 size={15}/></button>:<div className="finance-classification-lock"><LockKeyhole size={13}/></div>}</div>)}</div></section>
  }

  return <section className="workspace finance-classifications-workspace finance-classifications-refresh"><div className="page-heading"><div><span className="eyebrow">Financeiro · Cadastros</span><h1>Classificações financeiras</h1><p>Organize o fluxo com categorias claras sem alterar a natureza protegida dos lançamentos automáticos.</p></div><div className="page-heading-actions"><button className="button secondary" type="button" onClick={()=>void load()} disabled={loading}><RefreshCw size={14}/> Atualizar</button>{canEdit&&<button className="button secondary" type="button" onClick={()=>{setModalError('');setOpen(true)}}><Plus size={14}/> Nova categoria</button>}{canEdit&&<button className="button primary" type="button" onClick={()=>void save()} disabled={saving||loading}><Save size={14}/> {saving?'Salvando...':'Salvar'}</button>}</div></div>
    {error&&<div className="form-alert danger-alert">{error}</div>}{success&&<div className="form-alert success-alert">{success}</div>}
    {loading?<article className="panel settings-loading">Carregando classificações...</article>:<><div className="finance-classification-note"><Tags size={16}/><div><strong>Simples de manter, seguro para o financeiro</strong><span>As categorias do ERP podem ser renomeadas. Categorias personalizadas podem ser criadas ou excluídas; a natureza dos lançamentos automáticos permanece protegida.</span></div></div><div className="finance-classifications-grid">{group('Entradas',incoming,'receivable')}{group('Saídas',outgoing,'payable')}</div></>}

    {open&&<div className="portfolio-modal-backdrop" onMouseDown={event=>{if(event.currentTarget===event.target&&!saving)setOpen(false)}}><form className="panel portfolio-modal classification-create-modal" onSubmit={create} role="dialog" aria-modal="true"><div className="portfolio-modal-header"><div><span className="eyebrow">Financeiro · Categoria</span><h2>Nova categoria</h2><p>Crie apenas o necessário para manter o fluxo organizado e fácil de ler.</p></div><button className="portfolio-modal-close" type="button" aria-label="Fechar" disabled={saving} onClick={()=>setOpen(false)}><X size={17}/></button></div><div className="classification-modal-body">{modalError&&<div className="form-alert danger-alert" role="alert">{modalError}</div>}<label className="field"><span>Nome da categoria</span><input autoFocus required minLength={2} maxLength={120} value={newLabel} onChange={event=>setNewLabel(event.target.value)} placeholder="Ex.: Marketing e anúncios"/></label><div className="form-grid two-columns"><label className="field"><span>Natureza</span><select value={newDirection} onChange={event=>setNewDirection(event.target.value as 'receivable'|'payable')}><option value="receivable">Entrada</option><option value="payable">Saída</option></select></label><label className="field"><span>Caixa</span><select value={newScope} onChange={event=>setNewScope(event.target.value as 'operating'|'third_party')}><option value="operating">Operacional</option><option value="third_party">Recursos de terceiros</option></select></label></div></div><div className="canonical-modal-actions"><button className="button secondary" type="button" disabled={saving} onClick={()=>setOpen(false)}>Cancelar</button><button className="button primary" disabled={saving||newLabel.trim().length<2}>{saving?'Criando...':'Criar categoria'}</button></div></form></div>}
  </section>
}
