import { FileSearch, FileUp, Landmark, Link2, Plus, ReceiptText, UserRound, UserPlus, X } from 'lucide-react'
import { FormEvent, useEffect, useMemo, useState } from 'react'
import { ApiError, apiRequest } from '../../api/client'
import type { Person } from '../../api/types'
import './finance-manual-title.css'

type Direction='receivable'|'payable'
type Scope='operating'|'third_party'
type Tab='entry'|'links'|'document'
type Lease={id:string;code:string;property_code:string;tenants:Array<{name?:string}>;owners:Array<{name?:string}>;status:string}
type Parsed={filename:string;extracted:{due_date:string|null;amount:number|null;boleto_line:string|null;document_number:string|null;counterparty_name:string|null};warnings:string[]}
type Created={id:string;code:string}
type Classification={key:string;label:string;direction:Direction;fund_scope:Scope;category:string}
type ClassificationResponse={rules:Classification[]}
type Suggestion={found:boolean;category:string|null;fund_scope:Scope|null;source_title_id:string|null}
type Props={direction:Direction;onClose:()=>void;onCreated:(message:string)=>void}

const payableCategories=['Colaboradores','Aluguel da sede','Energia elétrica','Água','Internet / telefonia','Insumos','Impostos e taxas','Serviços de terceiros','Comissões','Angariações','Reembolsos','Outras despesas']
const receivableCategories=['Serviços','Reembolso','Cobrança adicional','Honorários / taxas','Manutenção','Outras receitas']
function today(){const now=new Date();const offset=now.getTimezoneOffset();return new Date(now.getTime()-offset*60000).toISOString().slice(0,10)}
function currentMonth(){return today().slice(0,7)}
function parseMoney(value:string){const parsed=Number(value.trim().replace(/\./g,'').replace(',','.'));return Number.isFinite(parsed)?parsed:0}
function formatInput(value:number){return Number(value||0).toLocaleString('pt-BR',{minimumFractionDigits:2,maximumFractionDigits:2})}
function digits(value:string|null|undefined){return String(value||'').replace(/\D/g,'')}

export function FinanceManualTitleModal({direction,onClose,onCreated}:Props){
  const defaults=direction==='payable'?payableCategories:receivableCategories
  const [tab,setTab]=useState<Tab>('entry')
  const [scope,setScope]=useState<Scope>('operating')
  const [category,setCategory]=useState(defaults[0])
  const [classifications,setClassifications]=useState<Classification[]>([])
  const [description,setDescription]=useState('')
  const [people,setPeople]=useState<Person[]>([]),[personId,setPersonId]=useState(''),[counterparty,setCounterparty]=useState('')
  const [leases,setLeases]=useState<Lease[]>([]),[leaseId,setLeaseId]=useState('')
  const [competence,setCompetence]=useState(currentMonth()),[dueDate,setDueDate]=useState(today()),[amount,setAmount]=useState('0,00')
  const [notes,setNotes]=useState(''),[boletoLine,setBoletoLine]=useState('')
  const [file,setFile]=useState<File|null>(null),[parsing,setParsing]=useState(false),[parseWarnings,setParseWarnings]=useState<string[]>([])
  const [quickOpen,setQuickOpen]=useState(false),[quickName,setQuickName]=useState(''),[quickDocument,setQuickDocument]=useState('')
  const [saving,setSaving]=useState(false),[error,setError]=useState(''),[remembered,setRemembered]=useState(false)

  useEffect(()=>{void Promise.allSettled([apiRequest<Person[]>('/people'),apiRequest<Lease[]>('/lease-contracts'),apiRequest<ClassificationResponse>('/finance/advanced/classifications')]).then(([persons,contracts,rules])=>{if(persons.status==='fulfilled')setPeople(persons.value);if(contracts.status==='fulfilled')setLeases(contracts.value);if(rules.status==='fulfilled')setClassifications(rules.value.rules)})},[])
  useEffect(()=>{const close=(event:KeyboardEvent)=>{if(event.key==='Escape'&&!saving)onClose()};window.addEventListener('keydown',close);return()=>window.removeEventListener('keydown',close)},[onClose,saving])
  const selectedPerson=useMemo(()=>people.find(item=>item.id===personId)||null,[people,personId])
  useEffect(()=>{if(selectedPerson)setCounterparty(selectedPerson.name)},[selectedPerson])
  useEffect(()=>{setRemembered(false);if(!personId)return;void apiRequest<Suggestion>(`/finance/advanced/classifications/suggestion?person_id=${encodeURIComponent(personId)}&direction=${direction}`).then(result=>{if(!result.found)return;if(result.category)setCategory(result.category);if(result.fund_scope)setScope(result.fund_scope);setRemembered(true)}).catch(()=>{})},[personId,direction])
  const categoryOptions=useMemo(()=>[...new Set([...defaults,...classifications.filter(item=>item.direction===direction).map(item=>item.category),category].filter(Boolean))],[defaults,classifications,direction,category])

  async function parseDocument(next:File|null){setFile(next);setParseWarnings([]);if(!next)return;setParsing(true);setError('');try{const data=new FormData();data.append('file',next);const result=await apiRequest<Parsed>('/finance/treasury/manual-titles/parse-document',{method:'POST',body:data});setParseWarnings(result.warnings||[]);if(result.extracted.due_date)setDueDate(result.extracted.due_date);if(result.extracted.amount!=null)setAmount(formatInput(result.extracted.amount));if(result.extracted.boleto_line)setBoletoLine(result.extracted.boleto_line);const document=result.extracted.document_number;const byDocument=document?people.find(person=>digits(person.document_number)===digits(document)):null;const byName=result.extracted.counterparty_name?people.find(person=>person.name.toLowerCase().includes(result.extracted.counterparty_name!.toLowerCase())||result.extracted.counterparty_name!.toLowerCase().includes(person.name.toLowerCase())):null;const found=byDocument||byName;if(found){setPersonId(found.id);setCounterparty(found.name)}else if(result.extracted.counterparty_name)setCounterparty(result.extracted.counterparty_name);if(!description)setDescription(direction==='payable'?'Pagamento de boleto / documento':'Cobrança vinculada a documento')}catch(cause){setError(cause instanceof ApiError?cause.detail:'Não foi possível ler o documento.')}finally{setParsing(false)}}

  async function quickCreate(){if(quickName.trim().length<2)return;setSaving(true);setError('');try{const created=await apiRequest<Person>('/people',{method:'POST',body:JSON.stringify({person_type:digits(quickDocument).length>11?'company':'individual',name:quickName.trim(),document_number:quickDocument||null,email:null,phone:null,address:{street:'',number:'',complement:'',neighborhood:'',city:'Curitiba',state:'PR',postal_code:''},notes:direction==='payable'?'Criado a partir do contas a pagar.':'Criado a partir do contas a receber.',role_keys:direction==='payable'?['supplier']:[]})});setPeople(current=>[created,...current]);setPersonId(created.id);setCounterparty(created.name);setQuickOpen(false);setQuickName('');setQuickDocument('')}catch(cause){setError(cause instanceof ApiError?cause.detail:'Não foi possível cadastrar a contraparte.')}finally{setSaving(false)}}

  async function submit(event:FormEvent){event.preventDefault();if(parseMoney(amount)<=0){setTab('entry');setError('Informe um valor maior que zero.');return}if(description.trim().length<2){setTab('entry');setError('Informe uma descrição para o lançamento.');return}setSaving(true);setError('');try{const created=await apiRequest<Created>('/finance/treasury/manual-titles',{method:'POST',body:JSON.stringify({direction,fund_scope:scope,category,description:description.trim(),counterparty_name:counterparty||null,counterparty_person_id:personId||null,competence:`${competence}-01`,due_date:dueDate,amount:parseMoney(amount),lease_contract_id:leaseId||null,property_id:null,notes:notes||null,boleto_line:boletoLine||null})});if(file){const data=new FormData();data.append('file',file);await apiRequest(`/finance/treasury/manual-titles/${created.id}/attachments`,{method:'POST',body:data})}onCreated(`${created.code} criado como ${direction==='payable'?'conta a pagar':'conta a receber'}.`);onClose()}catch(cause){setError(cause instanceof ApiError?cause.detail:'Não foi possível criar o lançamento financeiro.')}finally{setSaving(false)}}

  const title=direction==='payable'?'Nova saída / conta a pagar':'Nova entrada / conta a receber'
  return <div className="portfolio-modal-backdrop finance-manual-backdrop" onMouseDown={event=>{if(event.currentTarget===event.target&&!saving)onClose()}}><form className="panel portfolio-modal finance-manual-title-modal" onSubmit={submit} role="dialog" aria-modal="true">
    <div className="portfolio-modal-header finance-manual-header"><div className={`finance-manual-title-icon ${direction}`}><ReceiptText size={20}/></div><div><span className="eyebrow">Tesouraria · lançamento financeiro</span><h2>{title}</h2><p>Registre apenas o que não nasce automaticamente de outro módulo do ERP.</p></div><button className="portfolio-modal-close" type="button" aria-label="Fechar" disabled={saving} onClick={onClose}><X size={17}/></button></div>
    <nav className="finance-manual-tabs"><button type="button" className={tab==='entry'?'active':''} onClick={()=>setTab('entry')}><ReceiptText size={14}/> Lançamento</button><button type="button" className={tab==='links'?'active':''} onClick={()=>setTab('links')}><UserRound size={14}/> Contraparte e vínculo</button><button type="button" className={tab==='document'?'active':''} onClick={()=>setTab('document')}><FileUp size={14}/> Documento</button></nav>
    <div className="finance-manual-body">{error&&<div className="form-alert danger-alert finance-manual-error" role="alert">{error}</div>}
      {tab==='entry'&&<section className="finance-manual-section"><div className="finance-manual-section-heading"><div><Landmark size={16}/></div><span><strong>Dados do lançamento</strong><small>Classificação, competência e valor.</small></span></div><div className="finance-manual-grid"><label><span>Natureza do recurso</span><select value={scope} onChange={e=>setScope(e.target.value as Scope)}><option value="operating">Operacional</option><option value="third_party">Recursos de terceiros</option></select></label><label><span>Classificação gerencial</span><select value={category} onChange={e=>{setCategory(e.target.value);setRemembered(false)}}>{categoryOptions.map(item=><option key={item}>{item}</option>)}</select>{remembered&&<small className="finance-remembered">Lembrada do último lançamento desta contraparte.</small>}</label><label className="full"><span>Descrição</span><input required value={description} onChange={e=>setDescription(e.target.value)} placeholder={direction==='payable'?'Ex.: Energia elétrica do escritório':'Ex.: Reembolso de despesa'}/></label><label><span>Competência</span><input type="month" required value={competence} onChange={e=>setCompetence(e.target.value)}/></label><label><span>Vencimento</span><input type="date" required value={dueDate} onChange={e=>setDueDate(e.target.value)}/></label><label className="full value-field"><span>Valor</span><input inputMode="decimal" data-format="money" required value={amount} onChange={e=>setAmount(e.target.value)} placeholder="0,00"/></label></div>{scope==='third_party'&&<div className="finance-manual-scope-warning">Este lançamento ficará segregado do caixa operacional e aparecerá em <strong>Recursos de terceiros</strong>.</div>}</section>}
      {tab==='links'&&<section className="finance-manual-section"><div className="finance-manual-section-heading"><div><Link2 size={16}/></div><span><strong>Contraparte e vínculo</strong><small>Fornecedor, cliente, proprietário, locatário e contrato relacionado.</small></span></div><div className="finance-manual-grid"><label className="full"><span>{direction==='payable'?'Fornecedor / favorecido':'Cliente / pagador'}</span><div className="finance-manual-inline"><select value={personId} onChange={e=>setPersonId(e.target.value)}><option value="">Sem cadastro vinculado</option>{people.filter(item=>item.is_active).map(person=><option key={person.id} value={person.id}>{person.name}{person.document_number?` · ${person.document_number}`:''}</option>)}</select><button className="button secondary compact" type="button" onClick={()=>setQuickOpen(value=>!value)}><UserPlus size={13}/> Novo</button></div></label>{!personId&&<label className="full"><span>Nome da contraparte</span><input value={counterparty} onChange={e=>setCounterparty(e.target.value)} placeholder="Nome do fornecedor, colaborador, proprietário ou cliente"/></label>}{quickOpen&&<div className="finance-manual-quick full"><div><strong>Novo {direction==='payable'?'fornecedor / favorecido':'contato financeiro'}</strong><small>Fica salvo em Pessoas e pode ser reutilizado nos próximos lançamentos.</small></div><input value={quickName} onChange={e=>setQuickName(e.target.value)} placeholder="Nome / razão social"/><input data-format="cpf-cnpj" value={quickDocument} onChange={e=>setQuickDocument(e.target.value)} placeholder="CPF ou CNPJ"/><button className="button secondary compact" type="button" disabled={saving||quickName.trim().length<2} onClick={()=>void quickCreate()}><Plus size={13}/> Cadastrar</button></div>}<label className="full"><span>Contrato de locação (opcional)</span><select value={leaseId} onChange={e=>setLeaseId(e.target.value)}><option value="">Sem contrato vinculado</option>{leases.map(lease=><option key={lease.id} value={lease.id}>{lease.code} · imóvel {lease.property_code} · {(lease.tenants||[]).map(item=>item.name).filter(Boolean).join(' / ')||'sem locatário'}</option>)}</select></label></div><div className="finance-link-hint"><strong>Memória por CPF/CNPJ</strong><span>Ao selecionar uma Pessoa já utilizada, o ERP sugere automaticamente a última classificação e natureza usadas para ela.</span></div></section>}
      {tab==='document'&&<section className="finance-manual-section"><div className="finance-manual-section-heading"><div><FileSearch size={16}/></div><span><strong>Documento e referência</strong><small>Boleto, PDF e observações do lançamento.</small></span></div><div className="finance-manual-grid"><label className="full"><span>Linha digitável / referência</span><input value={boletoLine} onChange={e=>setBoletoLine(e.target.value)} placeholder="Opcional"/></label><label className="full"><span>Documento / boleto</span><div className="finance-manual-file"><FileUp size={19}/><input type="file" accept=".pdf,.txt,.csv,image/*,application/pdf" onChange={e=>void parseDocument(e.target.files?.[0]||null)}/><div><strong>{file?file.name:'Selecionar documento'}</strong><small>{parsing?'Lendo dados do arquivo...':'PDF com texto: tenta preencher valor, vencimento, linha digitável e beneficiário.'}</small></div><FileSearch size={16}/></div>{parseWarnings.map(warning=><small className="finance-manual-warning" key={warning}>{warning}</small>)}</label><label className="full"><span>Observações</span><textarea rows={4} value={notes} onChange={e=>setNotes(e.target.value)} placeholder="Informações adicionais do lançamento"/></label></div></section>}
    </div>
    <div className="form-actions finance-manual-actions"><button className="button secondary" type="button" disabled={saving} onClick={onClose}>Cancelar</button><button className="button primary" disabled={saving||parsing}>{saving?'Salvando...':direction==='payable'?'Criar saída':'Criar entrada'}</button></div>
  </form></div>
}
