import { Copy, ExternalLink, KeyRound, Link2, Plus, RefreshCw, ShieldCheck, X, XCircle } from 'lucide-react'
import { FormEvent, useCallback, useEffect, useMemo, useState } from 'react'
import { ApiError, apiRequest } from '../../api/client'
import './finance-advanced.css'

type Person={id:string;name:string;document_number:string|null;email:string|null;role_keys:string[]}
type Access={id:string;person_id:string;person_name:string;document_number:string|null;roles:string[];label:string|null;is_active:boolean;expires_at:string;revoked_at:string|null;last_used_at:string|null;created_at:string;path:string}
type Account={id:string;access_id:string;person_id:string;email:string;is_active:boolean;last_login_at:string|null;locked_until:string|null;password_changed_at:string}
const dt=(value:string|null)=>value?new Date(value).toLocaleString('pt-BR'):'Nunca'
const roleLabel=(roles:string[])=>roles.includes('owner')&&roles.includes('tenant')?'Proprietário + locatário':roles.includes('owner')?'Proprietário':roles.includes('tenant')?'Locatário':'Sem vínculo ativo'

export function FinancePortalsPanel({permissions}:{permissions:string[]}){
 const canManage=permissions.includes('finance.payment.approve')
 const [accesses,setAccesses]=useState<Access[]>([]),[accounts,setAccounts]=useState<Account[]>([]),[people,setPeople]=useState<Person[]>([]),[personId,setPersonId]=useState(''),[label,setLabel]=useState(''),[open,setOpen]=useState(false),[created,setCreated]=useState<Access|null>(null),[error,setError]=useState(''),[modalError,setModalError]=useState(''),[success,setSuccess]=useState(''),[saving,setSaving]=useState(false)
 const [credentialAccess,setCredentialAccess]=useState<Access|null>(null),[password,setPassword]=useState(''),[credentialError,setCredentialError]=useState('')
 const accountByAccess=useMemo(()=>new Map(accounts.map(item=>[item.access_id,item])),[accounts])
 const peopleById=useMemo(()=>new Map(people.map(item=>[item.id,item])),[people])
 const load=useCallback(async()=>{setError('');try{const [accessRows,accountRows]=await Promise.all([apiRequest<Access[]>('/finance/advanced/portal/access'),apiRequest<Account[]>('/finance/advanced/portal/accounts')]);setAccesses(accessRows);setAccounts(accountRows)}catch(cause){setError(cause instanceof ApiError?cause.detail:'Não foi possível carregar os acessos externos.')}},[])
 useEffect(()=>{void load();void apiRequest<Person[]>('/people').then(items=>{setPeople(items);setPersonId(current=>current||items[0]?.id||'')}).catch(()=>setPeople([]))},[load])
 useEffect(()=>{if(!open&&!credentialAccess)return;const close=(event:KeyboardEvent)=>{if(event.key==='Escape'&&!saving){setOpen(false);setCredentialAccess(null)}};window.addEventListener('keydown',close);return()=>window.removeEventListener('keydown',close)},[open,credentialAccess,saving])
 const fullLink=(item:Access)=>`${window.location.origin}${item.path}`
 const tenantLoginLink=()=>`${window.location.origin}/portal`
 async function copy(item:Access){await navigator.clipboard.writeText(fullLink(item));setSuccess(`Link de ${item.person_name} copiado.`)}
 async function copyTenantLogin(){await navigator.clipboard.writeText(tenantLoginLink());setSuccess('Endereço do Portal do Inquilino copiado.')}
 function openPortal(item:Access){window.open(fullLink(item),'_blank','noopener,noreferrer')}
 function openTenantPortal(){window.open(tenantLoginLink(),'_blank','noopener,noreferrer')}
 async function create(ev:FormEvent){ev.preventDefault();if(!personId)return;setSaving(true);setModalError('');try{const result=await apiRequest<Access>('/finance/advanced/portal/access',{method:'POST',body:JSON.stringify({person_id:personId,label:label||null})});setCreated(result);setOpen(false);setLabel('');setSuccess('Acesso permanente ativado. Se for locatário, configure também a senha do Portal do Inquilino.');await load()}catch(cause){setModalError(cause instanceof ApiError?cause.detail:'Não foi possível criar o acesso externo.')}finally{setSaving(false)}}
 async function revoke(item:Access){setSaving(true);setError('');try{await apiRequest(`/finance/advanced/portal/access/${item.id}/revoke`,{method:'POST'});setCreated(null);await load();setSuccess(`Acesso de ${item.person_name} revogado. O link e o login do portal ficam bloqueados até a reativação.`)}catch(cause){setError(cause instanceof ApiError?cause.detail:'Não foi possível revogar o acesso.')}finally{setSaving(false)}}
 async function configureCredentials(ev:FormEvent){ev.preventDefault();if(!credentialAccess)return;setSaving(true);setCredentialError('');try{const result=await apiRequest<{email:string}>(`/finance/advanced/portal/access/${credentialAccess.id}/credentials`,{method:'POST',body:JSON.stringify({password})});setCredentialAccess(null);setPassword('');setSuccess(`Login do Portal do Inquilino configurado para ${result.email}. Encaminhe a senha ao cliente por um canal seguro.`);await load()}catch(cause){setCredentialError(cause instanceof ApiError?cause.detail:'Não foi possível configurar a senha do portal.')}finally{setSaving(false)}}
 function beginCredentials(item:Access){setPassword('');setCredentialError('');setCredentialAccess(item)}
 const activeAccounts=accounts.filter(item=>item.is_active).length
 return <section className="workspace finance-advanced-workspace"><div className="page-heading finance-heading"><div><span className="eyebrow">Financeiro · Portais</span><h1>Portais externos</h1><p>Gerencie o login autenticado do Portal do Inquilino e mantenha os links financeiros permanentes já existentes.</p></div><div className="heading-actions"><button className="button secondary" onClick={()=>void load()}><RefreshCw size={14}/> Atualizar</button>{canManage&&<button className="button primary" onClick={()=>{setModalError('');setOpen(true)}}><Plus size={14}/> Novo acesso</button>}</div></div>{error&&<div className="form-alert danger-alert">{error}</div>}{success&&<div className="form-alert success-alert">{success}</div>}
 <article className="panel portal-created"><KeyRound size={20}/><div><strong>Portal do Inquilino</strong><span>Inquilinos com senha configurada entram pelo endereço único abaixo. Cada usuário visualiza somente os contratos vinculados ao próprio cadastro.</span><code>{tenantLoginLink()}</code><div className="finance-inline-actions"><button className="button secondary compact" type="button" onClick={()=>void copyTenantLogin()}><Copy size={13}/> Copiar endereço</button><button className="button primary compact" type="button" onClick={openTenantPortal}><ExternalLink size={13}/> Abrir portal</button></div></div></article>
 {created&&<article className="panel portal-created"><ShieldCheck size={20}/><div><strong>Acesso permanente de {created.person_name}</strong><span>O link financeiro legado continua disponível e pode ser copiado novamente a qualquer momento.</span><code>{fullLink(created)}</code><div className="finance-inline-actions"><button className="button secondary compact" onClick={()=>void copy(created)}><Copy size={13}/> Copiar</button><button className="button primary compact" onClick={()=>openPortal(created)}><ExternalLink size={13}/> Abrir link financeiro</button><button className="button secondary compact" onClick={()=>setCreated(null)}>Ocultar</button></div></div></article>}
 <div className="finance-advanced-metrics"><article className="panel"><span>Acessos ativos</span><strong>{accesses.filter(item=>item.is_active).length}</strong><small>Vínculos externos autorizados</small></article><article className="panel"><span>Logins do inquilino</span><strong>{activeAccounts}</strong><small>Contas com senha configurada</small></article><article className="panel"><span>Locatários</span><strong>{accesses.filter(item=>item.is_active&&item.roles.includes('tenant')).length}</strong><small>Elegíveis ao portal autenticado</small></article></div>
 <article className="panel finance-advanced-card"><div className="finance-advanced-card-head"><div><span className="eyebrow">Controle de acesso</span><h2>Clientes e portais</h2></div><Link2 size={20}/></div><div className="finance-compact-list portal-link-list">{accesses.map(item=>{const account=accountByAccess.get(item.id);const person=peopleById.get(item.person_id);const tenant=item.roles.includes('tenant');return <div className={`finance-compact-row portal-link-row ${!item.is_active?'muted':''}`} key={item.id}><div className="portal-link-person"><button className="portal-person-link" type="button" disabled={!item.is_active} onClick={()=>openPortal(item)}><strong>{item.person_name}</strong><ExternalLink size={12}/></button><span>{item.document_number||'CPF/CNPJ não informado'} · {roleLabel(item.roles)}</span><small>{tenant?account?`Portal do Inquilino: ${account.email} · último login ${dt(account.last_login_at)}`:`Portal do Inquilino ainda sem senha${person?.email?` · ${person.email}`:' · e-mail não cadastrado'}`:'Acesso financeiro por link permanente'} · Último acesso geral: {dt(item.last_used_at)}</small></div><div className="portal-row-actions">{tenant&&item.is_active&&canManage&&<button className="button secondary compact" type="button" onClick={()=>beginCredentials(item)}><KeyRound size={12}/> {account?'Redefinir senha':'Configurar login'}</button>}<button className="button secondary compact" type="button" onClick={()=>void copy(item)}><Copy size={12}/> Link financeiro</button><i className={`status-badge ${item.is_active?'success':'neutral'}`}>{item.is_active?'Ativo':'Revogado'}</i>{item.is_active&&canManage&&<button className="icon-danger" title="Revogar" onClick={()=>void revoke(item)}><XCircle size={15}/></button>}</div></div>})}{accesses.length===0&&<div className="finance-empty compact"><Link2 size={24}/><strong>Nenhum acesso externo criado.</strong><span>Crie um acesso para uma pessoa; os papéis são identificados automaticamente pelos contratos e imóveis.</span></div>}</div></article>
 {open&&<div className="portfolio-modal-backdrop" onMouseDown={event=>{if(event.currentTarget===event.target&&!saving)setOpen(false)}}><form className="panel portfolio-modal portal-access-modal" onSubmit={create} role="dialog" aria-modal="true"><div className="portfolio-modal-header"><div><span className="eyebrow">Portal externo</span><h2>Ativar acesso permanente</h2><p>Se a pessoa já teve um portal, o mesmo vínculo será reativado.</p></div><button className="portfolio-modal-close" type="button" aria-label="Fechar" disabled={saving} onClick={()=>setOpen(false)}><X size={17}/></button></div><div className="portal-access-modal-body">{modalError&&<div className="form-alert danger-alert" role="alert">{modalError}</div>}<div className="form-grid two-columns"><label className="field"><span>Pessoa</span><select value={personId} onChange={e=>setPersonId(e.target.value)} required><option value="">Selecione...</option>{people.map(person=><option key={person.id} value={person.id}>{person.name}{person.document_number?` · ${person.document_number}`:''}</option>)}</select></label><label className="field"><span>Identificação interna (opcional)</span><input value={label} onChange={e=>setLabel(e.target.value)} placeholder="Ex.: acesso principal"/></label></div></div><div className="canonical-modal-actions"><button type="button" className="button secondary" disabled={saving} onClick={()=>setOpen(false)}>Cancelar</button><button className="button primary" disabled={saving||!personId}>{saving?'Ativando...':'Ativar acesso'}</button></div></form></div>}
 {credentialAccess&&<div className="portfolio-modal-backdrop" onMouseDown={event=>{if(event.currentTarget===event.target&&!saving)setCredentialAccess(null)}}><form className="panel portfolio-modal portal-access-modal" onSubmit={configureCredentials} role="dialog" aria-modal="true"><div className="portfolio-modal-header"><div><span className="eyebrow">Portal do Inquilino</span><h2>{accountByAccess.has(credentialAccess.id)?'Redefinir senha':'Configurar login'}</h2><p>{credentialAccess.person_name} · {peopleById.get(credentialAccess.person_id)?.email||'e-mail não cadastrado'}</p></div><button className="portfolio-modal-close" type="button" aria-label="Fechar" disabled={saving} onClick={()=>setCredentialAccess(null)}><X size={17}/></button></div><div className="portal-access-modal-body">{credentialError&&<div className="form-alert danger-alert" role="alert">{credentialError}</div>}<label className="field"><span>Nova senha</span><input type="password" value={password} onChange={e=>setPassword(e.target.value)} minLength={8} maxLength={200} autoComplete="new-password" required placeholder="Mínimo de 8 caracteres"/></label><p className="helper-text">Ao redefinir a senha, todas as sessões anteriores deste cliente serão encerradas.</p></div><div className="canonical-modal-actions"><button type="button" className="button secondary" disabled={saving} onClick={()=>setCredentialAccess(null)}>Cancelar</button><button className="button primary" disabled={saving||password.length<8}>{saving?'Salvando...':'Salvar senha'}</button></div></form></div>}
 </section>
}
