import { CheckCircle2, Landmark, ReceiptText, RefreshCw, WalletCards, X } from 'lucide-react'
import { FormEvent, useCallback, useEffect, useMemo, useState } from 'react'
import { ApiError, apiRequest } from '../../api/client'
import './maintenance-finance.css'

type Entry={id:string;direction:'payable'|'receivable';status:string;counterparty_type:string;counterparty_name:string;responsibility:string;collection_method:string|null;amount:number;settled_amount:number;remaining_amount:number;margin_amount:number;due_date:string|null;settled_at:string|null;payment_reference:string|null}
type Case={maintenance_id:string;maintenance_code:string;property_id:string;property_code:string;property_title:string;title:string;responsibility:string;quote_code:string|null;partner_name:string|null;partner_cost:number;client_charge:number;margin:number;completed_at:string|null;payable:Entry|null;receivable:Entry|null}
type Dashboard={payable_pending:number;receivable_pending:number;expected_margin:number;settled_payables:number;settled_receivables:number;cases:Case[]}
type Modal={entry:Entry;kind:'pay'|'receive'}

const money=(v:number|null|undefined)=>Number(v||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'})
const dateTime=(v:string|null|undefined)=>v?new Date(v).toLocaleString('pt-BR'):'—'
const localDateTime=()=>{const d=new Date();return new Date(d.getTime()-d.getTimezoneOffset()*60000).toISOString().slice(0,16)}
const resp:Record<string,string>={owner:'Proprietário',tenant:'Locatário',agency:'Imobiliária',partner:'Parceiro',pending:'A definir'}

export function MaintenanceFinancePanel({permissions}:{permissions:string[]}){
  const canReconcile=permissions.includes('finance.reconcile'),canPay=permissions.includes('finance.payment.approve'),canRepasse=permissions.includes('finance.repasse.execute')
  const [data,setData]=useState<Dashboard|null>(null),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[error,setError]=useState(''),[success,setSuccess]=useState('')
  const [filter,setFilter]=useState<'all'|'pending'|'settled'>('all'),[modal,setModal]=useState<Modal|null>(null),[settledAt,setSettledAt]=useState(localDateTime()),[reference,setReference]=useState('')
  const load=useCallback(async()=>{setLoading(true);setError('');try{setData(await apiRequest<Dashboard>('/finance/maintenance'))}catch(e){setError(e instanceof ApiError?e.detail:'Não foi possível carregar o financeiro das manutenções.')}finally{setLoading(false)}},[])
  useEffect(()=>{void load()},[load])
  const cases=useMemo(()=>{const rows=data?.cases??[];if(filter==='all')return rows;return rows.filter(c=>filter==='pending'?[c.payable,c.receivable].some(e=>e&&e.status!=='settled'&&e.status!=='cancelled'):[c.payable,c.receivable].filter(Boolean).every(e=>e!.status==='settled'||e!.status==='cancelled'))},[data,filter])
  function open(entry:Entry,kind:Modal['kind']){setModal({entry,kind});setSettledAt(localDateTime());setReference('');setError('');setSuccess('')}
  async function submit(e:FormEvent){e.preventDefault();if(!modal)return;setSaving(true);setError('');try{const url=modal.kind==='pay'?`/finance/maintenance/payables/${modal.entry.id}/payment`:`/finance/maintenance/receivables/${modal.entry.id}/receipt`;await apiRequest(url,{method:'POST',body:JSON.stringify({settled_at:new Date(settledAt).toISOString(),payment_reference:reference||null})});setModal(null);await load();setSuccess(modal.kind==='pay'?'Pagamento ao parceiro registrado.':'Recebimento da manutenção registrado.')}catch(cause){setError(cause instanceof ApiError?cause.detail:'Não foi possível liquidar o lançamento.')}finally{setSaving(false)}}
  async function offset(entry:Entry){setSaving(true);setError('');try{await apiRequest(`/finance/maintenance/receivables/${entry.id}/apply-owner-repasse`,{method:'POST'});await load();setSuccess('Valor da manutenção abatido do(s) repasse(s) pendente(s) do imóvel.')}catch(cause){setError(cause instanceof ApiError?cause.detail:'Não foi possível aplicar o desconto no repasse.')}finally{setSaving(false)}}

  return <section className="workspace maintenance-finance-workspace"><div className="page-heading finance-heading"><div><span className="eyebrow">Financeiro · Manutenções</span><h1>Manutenções</h1><p>Pagamento real do parceiro, cobrança do cliente e margem da imobiliária separados por chamado.</p></div><button className="button secondary" onClick={()=>void load()} disabled={loading}><RefreshCw size={14}/> Atualizar</button></div>
    {data&&<div className="finance-metrics maintenance-finance-metrics"><article className="panel finance-metric"><span>A pagar a parceiros</span><strong>{money(data.payable_pending)}</strong><small>obrigações ainda não liquidadas</small></article><article className="panel finance-metric"><span>A receber de clientes</span><strong>{money(data.receivable_pending)}</strong><small>reembolsos / cobranças de manutenção</small></article><article className="panel finance-metric"><span>Margem prevista</span><strong>{money(data.expected_margin)}</strong><small>preço ao cliente menos custo do parceiro</small></article><article className="panel finance-metric"><span>Parceiros já pagos</span><strong>{money(data.settled_payables)}</strong><small>{money(data.settled_receivables)} já recebidos</small></article></div>}
    {error&&<div className="form-alert danger-alert">{error}</div>}{success&&<div className="form-alert success-alert">{success}</div>}
    <div className="finance-filter"><button className={filter==='all'?'active':''} onClick={()=>setFilter('all')}>Todas</button><button className={filter==='pending'?'active':''} onClick={()=>setFilter('pending')}>Pendentes</button><button className={filter==='settled'?'active':''} onClick={()=>setFilter('settled')}>Liquidadas</button></div>
    {loading?<article className="panel settings-loading">Carregando financeiro das manutenções...</article>:<div className="maintenance-finance-list">{cases.map(item=><article className="panel maintenance-finance-case" key={item.maintenance_id}><div className="maintenance-finance-head"><div><span>{item.maintenance_code} · Imóvel #{item.property_code}</span><strong>{item.title}</strong><small>{item.property_title} · {dateTime(item.completed_at)}</small></div><div><span>Parceiro</span><strong>{item.partner_name||'—'}</strong><small>{item.quote_code||'orçamento aprovado'}</small></div><div><span>Responsável</span><strong>{resp[item.responsibility]||item.responsibility}</strong></div></div><div className="maintenance-finance-values"><div><ReceiptText size={15}/><span>Custo parceiro</span><strong>{money(item.partner_cost)}</strong></div><div><WalletCards size={15}/><span>Cobrar cliente</span><strong>{item.responsibility==='agency'?'Não aplicável':money(item.client_charge)}</strong></div><div><Landmark size={15}/><span>Margem</span><strong className={item.margin<0?'negative':''}>{money(item.margin)}</strong></div></div><div className="maintenance-finance-entries">
      {item.payable&&<div><div><span>Conta a pagar</span><strong>{item.payable.counterparty_name}</strong><small>{money(item.payable.remaining_amount)} pendente · {item.payable.status==='settled'?'Pago':'A pagar'}</small></div>{item.payable.status!=='settled'&&canPay&&<button className="button primary compact" disabled={saving} onClick={()=>open(item.payable!,'pay')}><CheckCircle2 size={13}/> Registrar pagamento</button>}</div>}
      {item.receivable&&item.receivable.status!=='cancelled'&&<div><div><span>Conta a receber</span><strong>{item.receivable.counterparty_name}</strong><small>{money(item.receivable.remaining_amount)} pendente · {item.receivable.status==='settled'?'Recebido':'A receber'}</small></div><div className="heading-actions">{item.receivable.status!=='settled'&&item.receivable.collection_method==='owner_repasse_deduction'&&canRepasse&&<button className="button secondary compact" disabled={saving} onClick={()=>void offset(item.receivable!)}>Abater do repasse</button>}{item.receivable.status!=='settled'&&canReconcile&&<button className="button primary compact" disabled={saving} onClick={()=>open(item.receivable!,'receive')}><CheckCircle2 size={13}/> Registrar recebimento</button>}</div></div>}
    </div></article>)}{!cases.length&&<article className="panel finance-empty"><ReceiptText size={26}/><strong>Nenhuma manutenção financeira neste filtro.</strong><span>Os lançamentos nascem automaticamente quando uma manutenção com orçamento aprovado é concluída.</span></article>}</div>}
    {modal&&<div className="finance-modal-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget&&!saving)setModal(null)}}><form className="panel finance-modal" onSubmit={submit}><div className="finance-modal-header"><div><span className="eyebrow">{modal.kind==='pay'?'Pagamento ao parceiro':'Recebimento do cliente'}</span><h2>{modal.entry.counterparty_name}</h2><p>Valor integral: {money(modal.entry.remaining_amount)}</p></div><button type="button" onClick={()=>setModal(null)}><X size={18}/></button></div><div className="form-grid two-columns"><label className="field"><span>Data</span><input required type="datetime-local" value={settledAt} onChange={e=>setSettledAt(e.target.value)}/></label><label className="field"><span>Referência / comprovante</span><input value={reference} onChange={e=>setReference(e.target.value)} placeholder="Pix, transferência, autenticação..."/></label></div><div className="form-actions"><button className="button secondary" type="button" onClick={()=>setModal(null)}>Cancelar</button><button className="button primary" disabled={saving}>{saving?'Salvando...':'Confirmar'}</button></div></form></div>}
  </section>
}
