import { BadgeCheck, BadgeDollarSign, BriefcaseBusiness, Building2, CalendarCheck2, FileText, History, Landmark, Mail, MapPin, Pencil, Phone, Plus, Search, Target, UserRoundCheck, Users, WalletCards, X } from 'lucide-react'
import { FormEvent, useCallback, useEffect, useMemo, useState } from 'react'
import { ApiError, apiRequest } from '../../api/client'
import type { Address, Person, PersonCreate, Property } from '../../api/types'
import './brokers.css'

const emptyAddress:Address={street:'',number:'',complement:'',neighborhood:'',city:'Curitiba',state:'PR',postal_code:''}
type BankAccountType='checking'|'savings'|'payment'
type PixKeyType='none'|'cpf_cnpj'|'email'|'phone'|'random'
type BankForm={bank_name:string;bank_code:string;branch:string;account_number:string;account_digit:string;account_type:BankAccountType;pix_key_type:PixKeyType;pix_key:string;account_holder_name:string;account_holder_document:string}
type BankDetails=BankForm&{id:string;person_id:string;created_at:string;updated_at:string}
type BrokerTab='overview'|'portfolio'|'leads'|'visits'|'proposals'|'goals'|'commissions'|'documents'|'history'
const emptyBank:BankForm={bank_name:'',bank_code:'',branch:'',account_number:'',account_digit:'',account_type:'checking',pix_key_type:'none',pix_key:'',account_holder_name:'',account_holder_document:''}
function documentLabel(value:string|null){return value||'CPF/CNPJ não informado'}

export function BrokersPage({permissions}:{permissions:string[]}){
  const canCreate=permissions.includes('properties.create'),canEdit=permissions.includes('properties.edit')
  const [items,setItems]=useState<Person[]>([]),[properties,setProperties]=useState<Property[]>([]),[query,setQuery]=useState(''),[loading,setLoading]=useState(true)
  const [selectedId,setSelectedId]=useState<string|null>(null),[detailTab,setDetailTab]=useState<BrokerTab>('overview')
  const [pageError,setPageError]=useState(''),[modalError,setModalError]=useState(''),[success,setSuccess]=useState('')
  const [open,setOpen]=useState(false),[editing,setEditing]=useState<Person|null>(null),[saving,setSaving]=useState(false),[bankLoading,setBankLoading]=useState(false)
  const [personType,setPersonType]=useState<'individual'|'company'>('individual'),[name,setName]=useState(''),[documentNumber,setDocumentNumber]=useState(''),[email,setEmail]=useState(''),[phone,setPhone]=useState(''),[creci,setCreci]=useState(''),[address,setAddress]=useState<Address>(emptyAddress),[notes,setNotes]=useState(''),[bank,setBank]=useState<BankForm>(emptyBank)
  const load=useCallback(async()=>{setLoading(true);setPageError('');try{const [brokers,portfolio]=await Promise.all([apiRequest<Person[]>('/people?role=broker'),apiRequest<Property[]>('/properties')]);setItems(brokers);setProperties(portfolio);setSelectedId(current=>current&&brokers.some(item=>item.id===current)?current:(brokers[0]?.id??null))}catch(cause){setPageError(cause instanceof ApiError?cause.detail:'Não foi possível carregar os corretores.')}finally{setLoading(false)}},[])
  useEffect(()=>{void load()},[load])
  useEffect(()=>{if(!open)return;const close=(event:KeyboardEvent)=>{if(event.key==='Escape'&&!saving)setOpen(false)};window.addEventListener('keydown',close);return()=>window.removeEventListener('keydown',close)},[open,saving])
  const filtered=useMemo(()=>{const q=query.trim().toLowerCase();if(!q)return items;return items.filter(item=>(item.name+' '+(item.document_number||'')+' '+(item.email||'')+' '+(item.phone||'')+' '+(item.notes||'')).toLowerCase().includes(q))},[items,query])
  const selected=useMemo(()=>items.find(item=>item.id===selectedId)??null,[items,selectedId])
  const selectedProperties=useMemo(()=>selected?properties.filter(item=>item.responsible_broker?.person_id===selected.id):[],[properties,selected])
  const brokerStats=useMemo(()=>({total:selectedProperties.length,available:selectedProperties.filter(item=>item.status==='available').length,published:selectedProperties.filter(item=>item.publication_enabled).length,leased:selectedProperties.filter(item=>item.status==='leased').length}),[selectedProperties])
  const tabs:Array<{key:BrokerTab;label:string;icon:typeof Users}>=[{key:'overview',label:'Visão Geral',icon:UserRoundCheck},{key:'portfolio',label:'Carteira',icon:BriefcaseBusiness},{key:'leads',label:'Leads',icon:Users},{key:'visits',label:'Visitas',icon:CalendarCheck2},{key:'proposals',label:'Propostas',icon:FileText},{key:'goals',label:'Metas',icon:Target},{key:'commissions',label:'Comissões',icon:BadgeDollarSign},{key:'documents',label:'Documentos',icon:FileText},{key:'history',label:'Rastreabilidade',icon:History}]
  function reset(){setEditing(null);setPersonType('individual');setName('');setDocumentNumber('');setEmail('');setPhone('');setCreci('');setAddress(emptyAddress);setNotes('');setBank(emptyBank);setModalError('')}
  function startCreate(){reset();setSuccess('');setOpen(true)}
  async function startEdit(item:Person){setModalError('');setSuccess('');setEditing(item);setPersonType(item.person_type);setName(item.name);setDocumentNumber(item.document_number||'');setEmail(item.email||'');setPhone(item.phone||'');setAddress({...emptyAddress,...item.address});const creciMatch=(item.notes||'').match(/(?:^|\n)CRECI:\s*(.+)/i);setCreci(creciMatch?.[1]?.trim()||'');setNotes((item.notes||'').replace(/(?:^|\n)CRECI:\s*.+/i,'').trim());setBank(emptyBank);setOpen(true);setBankLoading(true);try{const result=await apiRequest<BankDetails|null>(`/people/${item.id}/bank-details`);if(result)setBank({bank_name:result.bank_name||'',bank_code:result.bank_code||'',branch:result.branch||'',account_number:result.account_number||'',account_digit:result.account_digit||'',account_type:result.account_type||'checking',pix_key_type:result.pix_key_type||'none',pix_key:result.pix_key||'',account_holder_name:result.account_holder_name||'',account_holder_document:result.account_holder_document||''})}catch(cause){setModalError(cause instanceof ApiError?cause.detail:'Não foi possível carregar os dados bancários do corretor.')}finally{setBankLoading(false)}}
  function payload():PersonCreate{const combinedNotes=[creci.trim()?`CRECI: ${creci.trim()}`:'',notes.trim()].filter(Boolean).join('\n');const preserved=[...(editing?.role_keys||[]),'broker'];return{person_type:personType,name:name.trim(),document_number:documentNumber||null,email:email||null,phone:phone||null,address,notes:combinedNotes||null,role_keys:[...new Set(preserved)] as PersonCreate['role_keys']}}
  async function submit(event:FormEvent){event.preventDefault();setSaving(true);setModalError('');setSuccess('');try{const wasEditing=Boolean(editing);const result=editing?await apiRequest<Person>(`/people/${editing.id}`,{method:'PUT',body:JSON.stringify(payload())}):await apiRequest<Person>('/people',{method:'POST',body:JSON.stringify(payload())});await apiRequest<BankDetails>(`/people/${result.id}/bank-details`,{method:'PUT',body:JSON.stringify({...bank,pix_key:bank.pix_key_type==='none'?null:bank.pix_key||null})});setOpen(false);reset();setSuccess(`${result.name} ${wasEditing?'atualizado':'cadastrado'} como corretor.`);await load()}catch(cause){setModalError(cause instanceof ApiError?cause.detail:'Não foi possível salvar o corretor.')}finally{setSaving(false)}}
  const setBankField=<K extends keyof BankForm>(key:K,value:BankForm[K])=>setBank(current=>({...current,[key]:value}))


  return <section className="workspace brokers-workspace broker-directory-v9"><div className="page-heading"><div><span className="eyebrow">Equipe · Corretores</span><h1>Corretores</h1><p>Lista e ficha operacional no mesmo módulo, com carteira e informações do corretor organizadas por abas.</p></div>{canCreate&&<button className="button primary" type="button" onClick={startCreate}><Plus size={14}/> Novo corretor</button>}</div>
    {pageError&&<div className="form-alert danger-alert">{pageError}</div>}{success&&<div className="form-alert success-alert">{success}</div>}
    {loading?<article className="panel settings-loading">Carregando corretores...</article>:<div className="broker-master-detail">
      <aside className="panel broker-directory-list">
        <div className="broker-directory-search"><Search size={14}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Buscar corretor..."/></div>
        <div className="broker-directory-count">{filtered.length} corretor(es)</div>
        <div className="broker-directory-items">{filtered.map(item=>{const creci=(item.notes||'').match(/(?:^|\n)CRECI:\s*(.+)/i)?.[1]?.trim();const portfolioCount=properties.filter(property=>property.responsible_broker?.person_id===item.id).length;return <button className={'broker-directory-row '+(selectedId===item.id?'active':'')} type="button" key={item.id} onClick={()=>{setSelectedId(item.id);setDetailTab('overview')}}><span className="broker-directory-avatar"><UserRoundCheck size={17}/></span><span className="broker-directory-copy"><strong>{item.name}</strong><small>{creci?'CRECI '+creci:'CRECI não informado'}</small><i>{portfolioCount} imóvel(is) na carteira</i></span></button>})}{filtered.length===0&&<div className="broker-directory-empty">Nenhum corretor encontrado.</div>}</div>
      </aside>
      <main className="panel broker-profile">
        {!selected?<div className="broker-profile-empty"><UserRoundCheck size={34}/><strong>Selecione um corretor</strong><span>A ficha completa aparecerá aqui.</span></div>:<>
          <header className="broker-profile-header"><div className="broker-profile-avatar"><UserRoundCheck size={23}/></div><div className="broker-profile-title"><span className="eyebrow">Ficha do corretor</span><h2>{selected.name}</h2><div>{selected.email&&<span><Mail size={12}/>{selected.email}</span>}{selected.phone&&<span><Phone size={12}/>{selected.phone}</span>}{selected.address?.city&&<span><MapPin size={12}/>{selected.address.city}/{selected.address.state}</span>}</div></div>{canEdit&&<button className="button secondary compact" type="button" onClick={()=>void startEdit(selected)}><Pencil size={13}/> Editar</button>}</header>
          <nav className="broker-profile-tabs" aria-label="Seções da ficha do corretor">{tabs.map(tab=>{const Icon=tab.icon;return <button className={detailTab===tab.key?'active':''} type="button" key={tab.key} onClick={()=>setDetailTab(tab.key)}><Icon size={13}/><span>{tab.label}</span></button>})}</nav>
          <div className="broker-profile-body">
            {detailTab==='overview'&&<div className="broker-overview"><section className="broker-kpi-grid"><article><span>Carteira</span><strong>{brokerStats.total}</strong><small>imóveis vinculados</small></article><article><span>Disponíveis</span><strong>{brokerStats.available}</strong><small>prontos para negócio</small></article><article><span>Publicados</span><strong>{brokerStats.published}</strong><small>no site público</small></article><article><span>Locados</span><strong>{brokerStats.leased}</strong><small>na carteira atual</small></article></section><section className="broker-overview-grid"><article><span>Identificação</span><strong>{documentLabel(selected.document_number)}</strong><small>{(selected.notes||'').match(/(?:^|\n)CRECI:\s*(.+)/i)?.[1]?.trim()?'CRECI '+(selected.notes||'').match(/(?:^|\n)CRECI:\s*(.+)/i)?.[1]?.trim():'CRECI não informado'}</small></article><article><span>Contato</span><strong>{selected.phone||'Telefone não informado'}</strong><small>{selected.email||'E-mail não informado'}</small></article><article><span>Base</span><strong>{selected.address?.city||'Cidade não informada'}{selected.address?.state?'/'+selected.address.state:''}</strong><small>{[selected.address?.neighborhood,selected.address?.street].filter(Boolean).join(' · ')||'Endereço não informado'}</small></article><article><span>Status</span><strong className="broker-active-label"><BadgeCheck size={13}/> Ativo</strong><small>cadastro habilitado no ERP</small></article></section></div>}
            {detailTab==='portfolio'&&<section className="broker-tab-section"><div className="broker-tab-heading"><div><span className="eyebrow">Carteira</span><h3>Imóveis sob responsabilidade</h3></div><strong>{selectedProperties.length}</strong></div>{selectedProperties.length?<div className="broker-property-list">{selectedProperties.map(property=><article key={property.id}><div><span>#{property.code}</span><strong>{property.public_title||[property.address.street,property.address.number].filter(Boolean).join(', ')||'Imóvel sem título'}</strong><small>{[property.address.neighborhood,property.address.city].filter(Boolean).join(' · ')}</small></div><div><span className={'status-badge '+(property.status==='available'?'success':property.status==='leased'?'neutral':'warning')}>{property.status}</span><strong>{property.rent_amount?Number(property.rent_amount).toLocaleString('pt-BR',{style:'currency',currency:'BRL'}):'—'}</strong></div></article>)}</div>:<div className="broker-tab-empty">Nenhum imóvel está atribuído a este corretor.</div>}</section>}
            {['leads','visits','proposals','goals','commissions','documents','history'].includes(detailTab)&&<section className="broker-tab-section"><div className="broker-tab-heading"><div><span className="eyebrow">{tabs.find(tab=>tab.key===detailTab)?.label}</span><h3>{detailTab==='leads'?'Atendimentos comerciais':detailTab==='visits'?'Agenda de visitas':detailTab==='proposals'?'Propostas do corretor':detailTab==='goals'?'Metas e desempenho':detailTab==='commissions'?'Comissões do corretor':detailTab==='documents'?'Documentos profissionais':'Rastreabilidade da ficha'}</h3></div></div><div className="broker-tab-empty">Esta aba já faz parte da ficha canônica do corretor. Os dados serão consolidados aqui conforme os vínculos operacionais forem sendo alimentados pelos respectivos módulos.</div></section>}
          </div>
        </>}
      </main>
    </div>}
    {open&&<div className="portfolio-modal-backdrop" onMouseDown={event=>{if(event.currentTarget===event.target&&!saving)setOpen(false)}}><form className="panel portfolio-modal broker-modal" onSubmit={submit} role="dialog" aria-modal="true"><div className="portfolio-modal-header"><div><span className="eyebrow">Cadastro de corretor</span><h2>{editing?'Editar corretor':'Novo corretor'}</h2><p>Dados profissionais, contato e recebimento de comissões no mesmo cadastro.</p></div><button className="portfolio-modal-close" type="button" aria-label="Fechar" disabled={saving} onClick={()=>setOpen(false)}><X size={17}/></button></div>
      <div className="broker-modal-body">{modalError&&<div className="form-alert danger-alert broker-modal-error" role="alert">{modalError}</div>}
        <section className="broker-form-section"><div className="broker-section-heading"><div className="broker-section-icon"><UserRoundCheck size={16}/></div><div><strong>Identificação e contato</strong><span>Dados básicos e registro profissional.</span></div></div><div className="broker-form-grid"><label><span>Tipo</span><select value={personType} onChange={e=>setPersonType(e.target.value as 'individual'|'company')}><option value="individual">Pessoa física</option><option value="company">Pessoa jurídica</option></select></label><label><span>CPF / CNPJ</span><input data-format="cpf-cnpj" value={documentNumber} onChange={e=>setDocumentNumber(e.target.value)} placeholder="CPF ou CNPJ"/></label><label className="full"><span>Nome / Razão social</span><input required value={name} onChange={e=>setName(e.target.value)} placeholder="Nome completo ou razão social"/></label><label><span>E-mail</span><input type="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="email@exemplo.com"/></label><label><span>Telefone / WhatsApp</span><input data-format="phone" value={phone} onChange={e=>setPhone(e.target.value)} placeholder="(41) 99999-9999"/></label><label><span>CRECI</span><input value={creci} onChange={e=>setCreci(e.target.value)} placeholder="Ex.: PR 12345-F"/></label></div></section>
        <section className="broker-form-section"><div className="broker-section-heading"><div className="broker-section-icon"><Building2 size={16}/></div><div><strong>Endereço</strong><span>Endereço principal do corretor.</span></div></div><div className="broker-form-grid"><label><span>CEP</span><input data-format="cep" value={address.postal_code} onChange={e=>setAddress(current=>({...current,postal_code:e.target.value}))} placeholder="00000-000"/></label><label className="street"><span>Rua / Logradouro</span><input value={address.street} onChange={e=>setAddress(current=>({...current,street:e.target.value}))}/></label><label><span>Número</span><input value={address.number} onChange={e=>setAddress(current=>({...current,number:e.target.value}))}/></label><label><span>Complemento</span><input value={address.complement} onChange={e=>setAddress(current=>({...current,complement:e.target.value}))}/></label><label><span>Bairro</span><input value={address.neighborhood} onChange={e=>setAddress(current=>({...current,neighborhood:e.target.value}))}/></label><label><span>Cidade</span><input value={address.city} onChange={e=>setAddress(current=>({...current,city:e.target.value}))}/></label><label className="uf"><span>UF</span><input maxLength={2} value={address.state} onChange={e=>setAddress(current=>({...current,state:e.target.value.toUpperCase()}))}/></label></div></section>
        <section className="broker-form-section bank-section"><div className="broker-section-heading"><div className="broker-section-icon"><Landmark size={16}/></div><div><strong>Dados bancários</strong><span>Conta preferencial para pagamento de comissões e repasses ao corretor.</span></div>{bankLoading&&<small>Carregando...</small>}</div><div className="broker-form-grid broker-bank-grid"><label className="bank-name"><span>Banco</span><input value={bank.bank_name} onChange={e=>setBankField('bank_name',e.target.value)} placeholder="Ex.: Banco Inter"/></label><label className="bank-code"><span>Código</span><input inputMode="numeric" value={bank.bank_code} onChange={e=>setBankField('bank_code',e.target.value)} placeholder="077"/></label><label><span>Agência</span><input value={bank.branch} onChange={e=>setBankField('branch',e.target.value)} placeholder="0001"/></label><label className="account-number"><span>Conta</span><div className="broker-account-combo"><input value={bank.account_number} onChange={e=>setBankField('account_number',e.target.value)} placeholder="00000000"/><input value={bank.account_digit} onChange={e=>setBankField('account_digit',e.target.value)} placeholder="DV" aria-label="Dígito da conta"/></div></label><label><span>Tipo de conta</span><select value={bank.account_type} onChange={e=>setBankField('account_type',e.target.value as BankAccountType)}><option value="checking">Conta corrente</option><option value="savings">Conta poupança</option><option value="payment">Conta de pagamento</option></select></label><label><span>Tipo da chave Pix</span><select value={bank.pix_key_type} onChange={e=>setBankField('pix_key_type',e.target.value as PixKeyType)}><option value="none">Sem chave Pix</option><option value="cpf_cnpj">CPF / CNPJ</option><option value="email">E-mail</option><option value="phone">Telefone</option><option value="random">Chave aleatória</option></select></label><label className="full"><span>Chave Pix</span><input disabled={bank.pix_key_type==='none'} data-format={bank.pix_key_type==='cpf_cnpj'?'cpf-cnpj':bank.pix_key_type==='phone'?'phone':undefined} value={bank.pix_key} onChange={e=>setBankField('pix_key',e.target.value)} placeholder={bank.pix_key_type==='none'?'Selecione um tipo de chave Pix':'Informe a chave Pix'}/></label><label><span>Titular da conta</span><input value={bank.account_holder_name} onChange={e=>setBankField('account_holder_name',e.target.value)} placeholder={name||'Nome do titular'}/></label><label><span>CPF / CNPJ do titular</span><input data-format="cpf-cnpj" value={bank.account_holder_document} onChange={e=>setBankField('account_holder_document',e.target.value)} placeholder="CPF ou CNPJ"/></label></div></section>
        <section className="broker-form-section notes-section"><div className="broker-section-heading"><div className="broker-section-icon"><WalletCards size={16}/></div><div><strong>Observações</strong><span>Informações complementares do cadastro.</span></div></div><div className="broker-form-grid"><label className="full"><textarea rows={3} value={notes} onChange={e=>setNotes(e.target.value)} placeholder="Observações internas sobre o corretor..."/></label></div></section>
      </div><div className="form-actions broker-modal-actions"><button className="button secondary" type="button" disabled={saving} onClick={()=>setOpen(false)}>Cancelar</button><button className="button primary" disabled={saving||bankLoading}>{saving?'Salvando...':'Salvar corretor'}</button></div></form></div>}
  </section>
}
