import { Building2, Landmark, UserRoundCheck, WalletCards, X } from 'lucide-react'
import { FormEvent, useEffect, useState } from 'react'
import { ApiError, apiRequest } from '../../api/client'
import type { Address, Person, PersonCreate } from '../../api/types'
import './brokers.css'

const emptyAddress:Address={street:'',number:'',complement:'',neighborhood:'',city:'Curitiba',state:'PR',postal_code:''}
type BankAccountType='checking'|'savings'|'payment'
type PixKeyType='none'|'cpf_cnpj'|'email'|'phone'|'random'
type BankForm={bank_name:string;bank_code:string;branch:string;account_number:string;account_digit:string;account_type:BankAccountType;pix_key_type:PixKeyType;pix_key:string;account_holder_name:string;account_holder_document:string}
type BankDetails=BankForm&{id:string;person_id:string;created_at:string;updated_at:string}
const emptyBank:BankForm={bank_name:'',bank_code:'',branch:'',account_number:'',account_digit:'',account_type:'checking',pix_key_type:'none',pix_key:'',account_holder_name:'',account_holder_document:''}

type Props={open:boolean;onClose:()=>void;onCreated:(person:Person)=>void}

export function BrokerCreateModal({open,onClose,onCreated}:Props){
  const [saving,setSaving]=useState(false),[error,setError]=useState('')
  const [personType,setPersonType]=useState<'individual'|'company'>('individual'),[name,setName]=useState(''),[documentNumber,setDocumentNumber]=useState(''),[email,setEmail]=useState(''),[phone,setPhone]=useState(''),[creci,setCreci]=useState(''),[address,setAddress]=useState<Address>(emptyAddress),[notes,setNotes]=useState(''),[bank,setBank]=useState<BankForm>(emptyBank)
  useEffect(()=>{if(!open)return;const close=(event:KeyboardEvent)=>{if(event.key==='Escape'&&!saving)onClose()};window.addEventListener('keydown',close);return()=>window.removeEventListener('keydown',close)},[open,saving,onClose])
  function reset(){setPersonType('individual');setName('');setDocumentNumber('');setEmail('');setPhone('');setCreci('');setAddress(emptyAddress);setNotes('');setBank(emptyBank);setError('')}
  const setBankField=<K extends keyof BankForm>(key:K,value:BankForm[K])=>setBank(current=>({...current,[key]:value}))
  async function submit(event:FormEvent){event.preventDefault();setSaving(true);setError('');try{const combinedNotes=[creci.trim()?`CRECI: ${creci.trim()}`:'',notes.trim()].filter(Boolean).join('\n');const payload:PersonCreate={person_type:personType,name:name.trim(),document_number:documentNumber||null,email:email||null,phone:phone||null,address,notes:combinedNotes||null,role_keys:['broker']};const saved=await apiRequest<Person>('/people',{method:'POST',body:JSON.stringify(payload)});await apiRequest<BankDetails>(`/people/${saved.id}/bank-details`,{method:'PUT',body:JSON.stringify({...bank,pix_key:bank.pix_key_type==='none'?null:bank.pix_key||null})});reset();onCreated(saved);onClose()}catch(cause){setError(cause instanceof ApiError?cause.detail:'Não foi possível cadastrar o corretor.')}finally{setSaving(false)}}
  if(!open)return null
  return <div className="portfolio-modal-backdrop" onMouseDown={event=>{if(event.currentTarget===event.target&&!saving)onClose()}}><form className="panel portfolio-modal broker-modal" onSubmit={submit} role="dialog" aria-modal="true"><div className="portfolio-modal-header"><div><span className="eyebrow">Cadastro de corretor</span><h2>Novo corretor</h2><p>O mesmo cadastro canônico usado no módulo Corretores, incluindo endereço e recebimento.</p></div><button className="portfolio-modal-close" type="button" aria-label="Fechar" disabled={saving} onClick={onClose}><X size={17}/></button></div>
    <div className="broker-modal-body">{error&&<div className="form-alert danger-alert broker-modal-error" role="alert">{error}</div>}
      <section className="broker-form-section"><div className="broker-section-heading"><div className="broker-section-icon"><UserRoundCheck size={16}/></div><div><strong>Identificação e contato</strong><span>Dados básicos e registro profissional.</span></div></div><div className="broker-form-grid"><label><span>Tipo</span><select value={personType} onChange={e=>setPersonType(e.target.value as 'individual'|'company')}><option value="individual">Pessoa física</option><option value="company">Pessoa jurídica</option></select></label><label><span>CPF / CNPJ</span><input data-format="cpf-cnpj" value={documentNumber} onChange={e=>setDocumentNumber(e.target.value)} placeholder="CPF ou CNPJ"/></label><label className="full"><span>Nome / Razão social</span><input required value={name} onChange={e=>setName(e.target.value)} placeholder="Nome completo ou razão social"/></label><label><span>E-mail</span><input type="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="email@exemplo.com"/></label><label><span>Telefone / WhatsApp</span><input data-format="phone" value={phone} onChange={e=>setPhone(e.target.value)} placeholder="(41) 99999-9999"/></label><label><span>CRECI</span><input value={creci} onChange={e=>setCreci(e.target.value)} placeholder="Ex.: PR 12345-F"/></label></div></section>
      <section className="broker-form-section"><div className="broker-section-heading"><div className="broker-section-icon"><Building2 size={16}/></div><div><strong>Endereço</strong><span>Endereço principal do corretor.</span></div></div><div className="broker-form-grid"><label><span>CEP</span><input data-format="cep" value={address.postal_code} onChange={e=>setAddress(current=>({...current,postal_code:e.target.value}))} placeholder="00000-000"/></label><label className="street"><span>Rua / Logradouro</span><input value={address.street} onChange={e=>setAddress(current=>({...current,street:e.target.value}))}/></label><label><span>Número</span><input value={address.number} onChange={e=>setAddress(current=>({...current,number:e.target.value}))}/></label><label><span>Complemento</span><input value={address.complement} onChange={e=>setAddress(current=>({...current,complement:e.target.value}))}/></label><label><span>Bairro</span><input value={address.neighborhood} onChange={e=>setAddress(current=>({...current,neighborhood:e.target.value}))}/></label><label><span>Cidade</span><input value={address.city} onChange={e=>setAddress(current=>({...current,city:e.target.value}))}/></label><label className="uf"><span>UF</span><input maxLength={2} value={address.state} onChange={e=>setAddress(current=>({...current,state:e.target.value.toUpperCase()}))}/></label></div></section>
      <section className="broker-form-section bank-section"><div className="broker-section-heading"><div className="broker-section-icon"><Landmark size={16}/></div><div><strong>Dados bancários</strong><span>Conta preferencial para pagamento das comissões.</span></div></div><div className="broker-form-grid broker-bank-grid"><label className="bank-name"><span>Banco</span><input value={bank.bank_name} onChange={e=>setBankField('bank_name',e.target.value)} placeholder="Ex.: Banco Inter"/></label><label className="bank-code"><span>Código</span><input inputMode="numeric" value={bank.bank_code} onChange={e=>setBankField('bank_code',e.target.value)} placeholder="077"/></label><label><span>Agência</span><input value={bank.branch} onChange={e=>setBankField('branch',e.target.value)} placeholder="0001"/></label><label className="account-number"><span>Conta</span><div className="broker-account-combo"><input value={bank.account_number} onChange={e=>setBankField('account_number',e.target.value)} placeholder="00000000"/><input value={bank.account_digit} onChange={e=>setBankField('account_digit',e.target.value)} placeholder="DV" aria-label="Dígito da conta"/></div></label><label><span>Tipo de conta</span><select value={bank.account_type} onChange={e=>setBankField('account_type',e.target.value as BankAccountType)}><option value="checking">Conta corrente</option><option value="savings">Conta poupança</option><option value="payment">Conta de pagamento</option></select></label><label><span>Tipo da chave Pix</span><select value={bank.pix_key_type} onChange={e=>setBankField('pix_key_type',e.target.value as PixKeyType)}><option value="none">Sem chave Pix</option><option value="cpf_cnpj">CPF / CNPJ</option><option value="email">E-mail</option><option value="phone">Telefone</option><option value="random">Chave aleatória</option></select></label><label className="full"><span>Chave Pix</span><input disabled={bank.pix_key_type==='none'} data-format={bank.pix_key_type==='cpf_cnpj'?'cpf-cnpj':bank.pix_key_type==='phone'?'phone':undefined} value={bank.pix_key} onChange={e=>setBankField('pix_key',e.target.value)} placeholder={bank.pix_key_type==='none'?'Selecione um tipo de chave Pix':'Informe a chave Pix'}/></label><label><span>Titular da conta</span><input value={bank.account_holder_name} onChange={e=>setBankField('account_holder_name',e.target.value)} placeholder={name||'Nome do titular'}/></label><label><span>CPF / CNPJ do titular</span><input data-format="cpf-cnpj" value={bank.account_holder_document} onChange={e=>setBankField('account_holder_document',e.target.value)} placeholder="CPF ou CNPJ"/></label></div></section>
      <section className="broker-form-section notes-section"><div className="broker-section-heading"><div className="broker-section-icon"><WalletCards size={16}/></div><div><strong>Observações</strong><span>Informações complementares do cadastro.</span></div></div><div className="broker-form-grid"><label className="full"><textarea rows={3} value={notes} onChange={e=>setNotes(e.target.value)} placeholder="Observações internas sobre o corretor..."/></label></div></section>
    </div><div className="form-actions broker-modal-actions"><button className="button secondary" type="button" disabled={saving} onClick={onClose}>Cancelar</button><button className="button primary" disabled={saving||!name.trim()}>{saving?'Salvando...':'Salvar corretor'}</button></div></form></div>
}
