import { BadgeCheck, Mail, MapPin, Pencil, Phone, Plus, Search, UserRoundCheck, X } from 'lucide-react'
import { FormEvent, useCallback, useEffect, useMemo, useState } from 'react'
import { ApiError, apiRequest } from '../../api/client'
import type { Address, Person, PersonCreate } from '../../api/types'
import './brokers.css'

const emptyAddress:Address={street:'',number:'',complement:'',neighborhood:'',city:'Curitiba',state:'PR',postal_code:''}
function documentLabel(value:string|null){return value||'CPF/CNPJ não informado'}

export function BrokersPage({permissions}:{permissions:string[]}){
  const canCreate=permissions.includes('properties.create'),canEdit=permissions.includes('properties.edit')
  const [items,setItems]=useState<Person[]>([]),[query,setQuery]=useState(''),[loading,setLoading]=useState(true),[error,setError]=useState(''),[success,setSuccess]=useState('')
  const [open,setOpen]=useState(false),[editing,setEditing]=useState<Person|null>(null),[saving,setSaving]=useState(false)
  const [personType,setPersonType]=useState<'individual'|'company'>('individual'),[name,setName]=useState(''),[documentNumber,setDocumentNumber]=useState(''),[email,setEmail]=useState(''),[phone,setPhone]=useState(''),[creci,setCreci]=useState(''),[address,setAddress]=useState<Address>(emptyAddress),[notes,setNotes]=useState('')

  const load=useCallback(async()=>{setLoading(true);setError('');try{setItems(await apiRequest<Person[]>('/people?role=broker'))}catch(cause){setError(cause instanceof ApiError?cause.detail:'Não foi possível carregar os corretores.')}finally{setLoading(false)}},[])
  useEffect(()=>{void load()},[load])
  const filtered=useMemo(()=>{const q=query.trim().toLowerCase();if(!q)return items;return items.filter(item=>`${item.name} ${item.document_number||''} ${item.email||''} ${item.phone||''} ${item.notes||''}`.toLowerCase().includes(q))},[items,query])

  function reset(){setEditing(null);setPersonType('individual');setName('');setDocumentNumber('');setEmail('');setPhone('');setCreci('');setAddress(emptyAddress);setNotes('')}
  function startCreate(){reset();setOpen(true)}
  function startEdit(item:Person){setEditing(item);setPersonType(item.person_type);setName(item.name);setDocumentNumber(item.document_number||'');setEmail(item.email||'');setPhone(item.phone||'');setAddress({...emptyAddress,...item.address});const creciMatch=(item.notes||'').match(/(?:^|\n)CRECI:\s*(.+)/i);setCreci(creciMatch?.[1]?.trim()||'');setNotes((item.notes||'').replace(/(?:^|\n)CRECI:\s*.+/i,'').trim());setOpen(true)}
  function payload():PersonCreate{const combinedNotes=[creci.trim()?`CRECI: ${creci.trim()}`:'',notes.trim()].filter(Boolean).join('\n');return{person_type:personType,name:name.trim(),document_number:documentNumber||null,email:email||null,phone:phone||null,address,notes:combinedNotes||null,role_keys:['broker']}}
  async function submit(event:FormEvent){event.preventDefault();setSaving(true);setError('');setSuccess('');try{const result=editing?await apiRequest<Person>(`/people/${editing.id}`,{method:'PUT',body:JSON.stringify(payload())}):await apiRequest<Person>('/people',{method:'POST',body:JSON.stringify(payload())});setOpen(false);reset();setSuccess(`${result.name} ${editing?'atualizado':'cadastrado'} como corretor.`);await load()}catch(cause){setError(cause instanceof ApiError?cause.detail:'Não foi possível salvar o corretor.')}finally{setSaving(false)}}

  return <section className="workspace brokers-workspace"><div className="page-heading"><div><span className="eyebrow">Carteira · Corretores</span><h1>Corretores</h1><p>Cadastro canônico dos corretores, separado da operação de imóveis e conectado às regras de comissão.</p></div>{canCreate&&<button className="button primary" type="button" onClick={startCreate}><Plus size={14}/> Novo corretor</button>}</div>
    {error&&<div className="form-alert danger-alert">{error}</div>}{success&&<div className="form-alert success-alert">{success}</div>}
    <div className="panel brokers-toolbar"><label><Search size={14}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Buscar por nome, CPF/CNPJ, CRECI ou contato"/></label><span>{filtered.length} corretor(es)</span></div>
    {loading?<article className="panel settings-loading">Carregando corretores...</article>:<div className="brokers-grid">{filtered.map(item=>{const creci=(item.notes||'').match(/(?:^|\n)CRECI:\s*(.+)/i)?.[1]?.trim();return <article className="panel broker-card" key={item.id}><div className="broker-avatar"><UserRoundCheck size={21}/></div><div className="broker-main"><div><h3>{item.name}</h3><span className="status-badge success"><BadgeCheck size={11}/> Corretor</span></div><strong>{documentLabel(item.document_number)}</strong>{creci&&<small>CRECI {creci}</small>}<div className="broker-contact">{item.email&&<span><Mail size={12}/>{item.email}</span>}{item.phone&&<span><Phone size={12}/>{item.phone}</span>}{item.address?.city&&<span><MapPin size={12}/>{item.address.city}/{item.address.state}</span>}</div></div>{canEdit&&<button className="button secondary compact" type="button" onClick={()=>startEdit(item)}><Pencil size={13}/> Editar</button>}</article>})}{filtered.length===0&&<article className="panel brokers-empty"><UserRoundCheck size={30}/><strong>Nenhum corretor encontrado.</strong><span>Cadastre o primeiro corretor para usá-lo nas propostas e regras de comissão.</span></article>}</div>}
    {open&&<div className="portfolio-modal-backdrop" onMouseDown={event=>{if(event.currentTarget===event.target&&!saving)setOpen(false)}}><form className="panel portfolio-modal broker-modal" onSubmit={submit} role="dialog" aria-modal="true"><div className="portfolio-modal-header"><div><span className="eyebrow">Cadastro de corretor</span><h2>{editing?'Editar corretor':'Novo corretor'}</h2><p>O registro continua sendo uma Pessoa do ERP; esta tela apenas organiza o papel de corretor.</p></div><button className="portfolio-modal-close" type="button" aria-label="Fechar" disabled={saving} onClick={()=>setOpen(false)}><X size={17}/></button></div><div className="broker-form-grid"><label><span>Tipo</span><select value={personType} onChange={e=>setPersonType(e.target.value as 'individual'|'company')}><option value="individual">Pessoa física</option><option value="company">Pessoa jurídica</option></select></label><label><span>CPF / CNPJ</span><input value={documentNumber} onChange={e=>setDocumentNumber(e.target.value)} placeholder="CPF ou CNPJ"/></label><label className="full"><span>Nome</span><input required value={name} onChange={e=>setName(e.target.value)} /></label><label><span>E-mail</span><input type="email" value={email} onChange={e=>setEmail(e.target.value)}/></label><label><span>Telefone / WhatsApp</span><input value={phone} onChange={e=>setPhone(e.target.value)}/></label><label><span>CRECI</span><input value={creci} onChange={e=>setCreci(e.target.value)} placeholder="Ex.: PR 12345-F"/></label><label><span>CEP</span><input value={address.postal_code} onChange={e=>setAddress(current=>({...current,postal_code:e.target.value}))}/></label><label className="full"><span>Endereço</span><input value={address.street} onChange={e=>setAddress(current=>({...current,street:e.target.value}))}/></label><label><span>Número</span><input value={address.number} onChange={e=>setAddress(current=>({...current,number:e.target.value}))}/></label><label><span>Complemento</span><input value={address.complement} onChange={e=>setAddress(current=>({...current,complement:e.target.value}))}/></label><label><span>Bairro</span><input value={address.neighborhood} onChange={e=>setAddress(current=>({...current,neighborhood:e.target.value}))}/></label><label><span>Cidade</span><input value={address.city} onChange={e=>setAddress(current=>({...current,city:e.target.value}))}/></label><label><span>UF</span><input maxLength={2} value={address.state} onChange={e=>setAddress(current=>({...current,state:e.target.value.toUpperCase()}))}/></label><label className="full"><span>Observações</span><textarea rows={3} value={notes} onChange={e=>setNotes(e.target.value)}/></label></div><div className="form-actions"><button className="button secondary" type="button" disabled={saving} onClick={()=>setOpen(false)}>Cancelar</button><button className="button primary" disabled={saving}>{saving?'Salvando...':'Salvar corretor'}</button></div></form></div>}
  </section>
}
