import { FileText, Landmark, MapPin, Pencil, Plus, Search, UserRound, Users, X } from 'lucide-react'
import { FormEvent, useCallback, useEffect, useMemo, useState } from 'react'
import { ApiError, apiRequest } from '../../api/client'
import type { Address, Person, PersonCreate } from '../../api/types'
import { EntityDocumentsPanel } from '../documents/EntityDocumentsPanel'

const emptyAddress = (): Address => ({ street: '', number: '', complement: '', neighborhood: '', city: 'Curitiba', state: 'PR', postal_code: '' })
const emptyPersonForm = (): PersonCreate => ({ person_type: 'individual', name: '', document_number: '', email: '', phone: '', address: emptyAddress(), notes: '', role_keys: ['owner'] })
const roleOptions = [['owner','Proprietário'],['tenant','Locatário'],['guarantor','Garantidor'],['broker','Corretor'],['supplier','Fornecedor'],['referrer','Angariador']] as const
type PersonRoleKey = PersonCreate['role_keys'][number]

type BankAccountType = 'checking' | 'savings' | 'payment'
type PixKeyType = 'none' | 'cpf_cnpj' | 'email' | 'phone' | 'random'
type BankForm = { bank_name:string; bank_code:string; branch:string; account_number:string; account_digit:string; account_type:BankAccountType; pix_key_type:PixKeyType; pix_key:string; account_holder_name:string; account_holder_document:string }
type BankDetails = BankForm & { id:string; person_id:string; created_at:string; updated_at:string }
const emptyBank = ():BankForm => ({ bank_name:'', bank_code:'', branch:'', account_number:'', account_digit:'', account_type:'checking', pix_key_type:'none', pix_key:'', account_holder_name:'', account_holder_document:'' })

type MaritalStatus = '' | 'single' | 'married' | 'stable_union' | 'divorced' | 'widowed' | 'separated' | 'other'
type ProfileForm = { secondary_phone:string; identity_number:string; identity_issuer:string; birth_date:string; nationality:string; marital_status:MaritalStatus; occupation:string; trade_name:string; state_registration:string; municipal_registration:string }
type ProfileDetails = Omit<ProfileForm,'marital_status'> & { marital_status:Exclude<MaritalStatus,''>|null; id:string; person_id:string; created_at:string; updated_at:string }
const emptyProfile = ():ProfileForm => ({ secondary_phone:'', identity_number:'', identity_issuer:'', birth_date:'', nationality:'Brasileira', marital_status:'', occupation:'', trade_name:'', state_registration:'', municipal_registration:'' })

type PersonTab = 'main' | 'address' | 'bank' | 'profile' | 'documents'

function bankHasData(value:BankForm){return Boolean(value.bank_name.trim()||value.bank_code.trim()||value.branch.trim()||value.account_number.trim()||value.account_digit.trim()||value.pix_key_type!=='none'||value.pix_key.trim()||value.account_holder_name.trim()||value.account_holder_document.trim())}
function profileHasData(value:ProfileForm,personType:PersonCreate['person_type']){if(value.secondary_phone.trim())return true;if(personType==='company')return Boolean(value.trade_name.trim()||value.state_registration.trim()||value.municipal_registration.trim());return Boolean(value.identity_number.trim()||value.identity_issuer.trim()||value.birth_date||value.nationality.trim()||value.marital_status||value.occupation.trim())}

export function PeopleWorkspacePage({ permissions }: { permissions: string[] }) {
  const canCreate = permissions.includes('properties.create'), canEdit = permissions.includes('properties.edit')
  const [items,setItems]=useState<Person[]>([]),[query,setQuery]=useState(''),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false)
  const [showForm,setShowForm]=useState(false),[editingId,setEditingId]=useState<string|null>(null),[form,setForm]=useState<PersonCreate>(emptyPersonForm)
  const [bank,setBank]=useState<BankForm>(emptyBank),[profile,setProfile]=useState<ProfileForm>(emptyProfile),[bankExists,setBankExists]=useState(false),[profileExists,setProfileExists]=useState(false)
  const [activeTab,setActiveTab]=useState<PersonTab>('main'),[detailsLoading,setDetailsLoading]=useState(false)
  const [error,setError]=useState(''),[success,setSuccess]=useState('')
  const load=useCallback(async()=>{setLoading(true);setError('');try{setItems(await apiRequest<Person[]>('/people'))}catch(cause){setError(cause instanceof ApiError?cause.detail:'Não foi possível carregar as pessoas.')}finally{setLoading(false)}},[])
  useEffect(()=>{void load()},[load])
  useEffect(()=>{if(!showForm)return;const previous=document.body.style.overflow;document.body.style.overflow='hidden';const close=(event:KeyboardEvent)=>{if(event.key==='Escape'&&!saving)setShowForm(false)};window.addEventListener('keydown',close);return()=>{document.body.style.overflow=previous;window.removeEventListener('keydown',close)}},[showForm,saving])
  const filtered=useMemo(()=>{const term=query.trim().toLowerCase();if(!term)return items;return items.filter(person=>`${person.name} ${person.document_number??''} ${person.email??''}`.toLowerCase().includes(term))},[items,query])
  function roleLabel(role:string){return roleOptions.find(([key])=>key===role)?.[1]??role}
  function resetExtended(){setBank(emptyBank());setProfile(emptyProfile());setBankExists(false);setProfileExists(false);setDetailsLoading(false);setActiveTab('main')}
  function openNew(){setEditingId(null);setForm(emptyPersonForm());resetExtended();setError('');setSuccess('');setShowForm(true)}
  async function openEdit(person:Person){
    if(!canEdit)return
    setEditingId(person.id);setForm({person_type:person.person_type,name:person.name,document_number:person.document_number??'',email:person.email??'',phone:person.phone??'',address:{...emptyAddress(),...person.address},notes:person.notes??'',role_keys:person.role_keys as PersonRoleKey[]});resetExtended();setError('');setSuccess('');setShowForm(true);setDetailsLoading(true)
    try{
      const [loadedBank,loadedProfile]=await Promise.all([apiRequest<BankDetails|null>(`/people/${person.id}/bank-details`),apiRequest<ProfileDetails|null>(`/people/${person.id}/profile`)])
      if(loadedBank){setBankExists(true);setBank({bank_name:loadedBank.bank_name||'',bank_code:loadedBank.bank_code||'',branch:loadedBank.branch||'',account_number:loadedBank.account_number||'',account_digit:loadedBank.account_digit||'',account_type:loadedBank.account_type||'checking',pix_key_type:loadedBank.pix_key_type||'none',pix_key:loadedBank.pix_key||'',account_holder_name:loadedBank.account_holder_name||'',account_holder_document:loadedBank.account_holder_document||''})}
      if(loadedProfile){setProfileExists(true);setProfile({secondary_phone:loadedProfile.secondary_phone||'',identity_number:loadedProfile.identity_number||'',identity_issuer:loadedProfile.identity_issuer||'',birth_date:loadedProfile.birth_date||'',nationality:loadedProfile.nationality||'',marital_status:loadedProfile.marital_status||'',occupation:loadedProfile.occupation||'',trade_name:loadedProfile.trade_name||'',state_registration:loadedProfile.state_registration||'',municipal_registration:loadedProfile.municipal_registration||''})}
    }catch(cause){setError(cause instanceof ApiError?cause.detail:'Não foi possível carregar os dados complementares da pessoa.')}finally{setDetailsLoading(false)}
  }
  function closeModal(){if(!saving){setShowForm(false);setEditingId(null);setError('');resetExtended()}}
  function updateAddress(key:keyof Address,value:string){setForm(current=>({...current,address:{...current.address,[key]:value}}))}
  function toggleRole(role:PersonRoleKey){setForm(current=>({...current,role_keys:current.role_keys.includes(role)?current.role_keys.filter(item=>item!==role):[...current.role_keys,role]}))}
  const setBankField=<K extends keyof BankForm>(key:K,value:BankForm[K])=>setBank(current=>({...current,[key]:value}))
  const setProfileField=<K extends keyof ProfileForm>(key:K,value:ProfileForm[K])=>setProfile(current=>({...current,[key]:value}))
  function updateSaved(saved:Person,editing:boolean){setItems(current=>(editing?current.map(item=>item.id===saved.id?saved:item):[...current,saved]).sort((a,b)=>a.name.localeCompare(b.name)))}
  async function save(event:FormEvent){
    event.preventDefault();const editing=editingId!==null;if((editing&&!canEdit)||(!editing&&!canCreate))return
    if(!form.name.trim()){setActiveTab('main');setError('Informe o nome ou a razão social da pessoa.');return}
    if(bank.pix_key_type!=='none'&&!bank.pix_key.trim()){setActiveTab('bank');setError('Informe a chave Pix ou selecione “Sem chave Pix”.');return}
    setSaving(true);setError('');setSuccess('');let saved:Person|null=null
    try{
      saved=await apiRequest<Person>(editing?`/people/${editingId}`:'/people',{method:editing?'PUT':'POST',body:JSON.stringify(form)})
      setEditingId(saved.id)
      const extended:Promise<unknown>[]=[]
      if(bankExists||bankHasData(bank))extended.push(apiRequest<BankDetails>(`/people/${saved.id}/bank-details`,{method:'PUT',body:JSON.stringify({...bank,pix_key:bank.pix_key_type==='none'?null:bank.pix_key||null})}))
      if(profileExists||profileHasData(profile,form.person_type))extended.push(apiRequest<ProfileDetails>(`/people/${saved.id}/profile`,{method:'PUT',body:JSON.stringify({...profile,birth_date:profile.birth_date||null,marital_status:profile.marital_status||null})}))
      await Promise.all(extended)
      updateSaved(saved,editing);setShowForm(false);setEditingId(null);resetExtended();setSuccess(editing?'Cadastro atualizado.':'Pessoa cadastrada.')
    }catch(cause){
      if(saved){updateSaved(saved,editing);setError(`O cadastro principal foi salvo, mas os dados complementares não foram concluídos. ${cause instanceof ApiError?cause.detail:'Tente salvar novamente.'}`)}
      else setError(cause instanceof ApiError?cause.detail:'Não foi possível salvar a pessoa.')
    }finally{setSaving(false)}
  }
  const tabButton=(key:PersonTab,label:string,Icon:typeof UserRound)=><button type="button" role="tab" aria-selected={activeTab===key} className={activeTab===key?'active':''} onClick={()=>setActiveTab(key)}><Icon size={14}/><span>{label}</span></button>
  return <section className="workspace portfolio-workspace"><div className="page-heading portfolio-heading"><div><span className="eyebrow">Cadastro canônico</span><h1>Pessoas</h1><p>Um único cadastro pode assumir papéis diferentes ao longo da operação, sem duplicidade.</p></div>{canCreate&&<button className="button primary" type="button" onClick={openNew}><Plus size={15}/> Nova pessoa</button>}</div>{error&&!showForm&&<div className="form-alert danger-alert">{error}</div>}{success&&<div className="form-alert success-alert">{success}</div>}<div className="portfolio-toolbar panel"><div className="portfolio-tabs"><button className="active" type="button"><Users size={15}/> Pessoas <span>{items.length}</span></button></div><label className="portfolio-search"><Search size={15}/><input placeholder="Buscar por nome, CPF/CNPJ ou e-mail..." value={query} onChange={event=>setQuery(event.target.value)}/></label></div>{loading?<article className="panel settings-loading">Carregando pessoas...</article>:<div className="portfolio-card-list">{filtered.map(person=><article className="panel person-row" key={person.id}><div className="avatar avatar-user">{person.name.trim().slice(0,2).toUpperCase()}</div><div className="person-main"><strong>{person.name}</strong><span>{person.document_number||'Documento não informado'} · {person.email||'E-mail não informado'}</span></div><div className="person-roles">{person.role_keys.length?person.role_keys.map(role=><i className="permission-chip" key={role}>{roleLabel(role)}</i>):<span>Sem papel operacional</span>}</div>{canEdit&&<button className="portfolio-edit-button" type="button" onClick={()=>void openEdit(person)} aria-label={`Editar ${person.name}`} title="Editar pessoa"><Pencil size={14}/></button>}</article>)}{filtered.length===0&&<article className="panel portfolio-empty"><Users size={26}/><strong>Nenhuma pessoa encontrada.</strong><span>Ajuste a busca ou cadastre uma nova pessoa.</span></article>}</div>}{showForm&&<div className="portfolio-modal-backdrop" role="presentation" onMouseDown={event=>{if(event.target===event.currentTarget)closeModal()}}><form className="panel portfolio-modal person-modal" onSubmit={save} role="dialog" aria-modal="true" aria-labelledby="person-modal-title"><div className="portfolio-modal-header"><div><span className="eyebrow">Cadastro canônico</span><h2 id="person-modal-title">{editingId?'Editar pessoa':'Nova pessoa'}</h2><p>Identificação, endereço, recebimentos e dados contratuais no mesmo cadastro.</p></div><button className="portfolio-modal-close" type="button" onClick={closeModal} disabled={saving} aria-label="Fechar"><X size={18}/></button></div>
    <div className="person-form-tabs" role="tablist" aria-label="Seções do cadastro">{tabButton('main','Dados principais',UserRound)}{tabButton('address','Endereço',MapPin)}{tabButton('bank','Dados bancários',Landmark)}{tabButton('profile','Contratuais',FileText)}{editingId&&permissions.includes('documents.view')&&tabButton('documents','Documentos',FileText)}</div>
    <div className="portfolio-modal-body person-modal-body">{error&&<div className="form-alert danger-alert">{error}</div>}{detailsLoading&&<div className="person-detail-loading">Carregando dados complementares...</div>}
      {activeTab==='main'&&<div className="person-tab-panel"><div className="person-tab-heading"><strong>Identificação e contato</strong><span>Dados básicos e papéis que esta pessoa exerce na operação.</span></div><div className="form-grid three-columns"><label className="field"><span>Tipo</span><select value={form.person_type} onChange={e=>setForm(c=>({...c,person_type:e.target.value as PersonCreate['person_type']}))}><option value="individual">Pessoa física</option><option value="company">Pessoa jurídica</option></select></label><label className="field"><span>{form.person_type==='company'?'CNPJ':'CPF'}</span><input data-format="cpf-cnpj" value={form.document_number??''} onChange={e=>setForm(c=>({...c,document_number:e.target.value}))}/></label><label className="field field-span-2"><span>{form.person_type==='company'?'Razão social':'Nome completo'}</span><input autoFocus value={form.name} onChange={e=>setForm(c=>({...c,name:e.target.value}))}/></label><label className="field field-span-2"><span>E-mail</span><input type="email" value={form.email??''} onChange={e=>setForm(c=>({...c,email:e.target.value}))}/></label><label className="field field-span-2"><span>Telefone / WhatsApp</span><input data-format="phone" value={form.phone??''} onChange={e=>setForm(c=>({...c,phone:e.target.value}))}/></label><div className="field field-span-3"><span>Papéis na operação</span><div className="portfolio-role-grid">{roleOptions.map(([key,label])=><label className="portfolio-role-option" key={key}><input type="checkbox" checked={form.role_keys.includes(key)} onChange={()=>toggleRole(key)}/><span>{label}</span></label>)}</div></div></div></div>}
      {activeTab==='address'&&<div className="person-tab-panel"><div className="person-tab-heading"><strong>Endereço principal</strong><span>Usado em contratos, correspondências e documentos da operação.</span></div><div className="form-grid three-columns"><label className="field"><span>CEP</span><input data-format="cep" value={form.address.postal_code} onChange={e=>updateAddress('postal_code',e.target.value)}/></label><label className="field field-span-2"><span>Rua / Logradouro</span><input value={form.address.street} onChange={e=>updateAddress('street',e.target.value)}/></label><label className="field"><span>Número</span><input value={form.address.number} onChange={e=>updateAddress('number',e.target.value)}/></label><label className="field field-span-2"><span>Complemento</span><input value={form.address.complement} onChange={e=>updateAddress('complement',e.target.value)}/></label><label className="field field-span-2"><span>Bairro</span><input value={form.address.neighborhood} onChange={e=>updateAddress('neighborhood',e.target.value)}/></label><label className="field field-span-2"><span>Cidade</span><input value={form.address.city} onChange={e=>updateAddress('city',e.target.value)}/></label><label className="field"><span>UF</span><input maxLength={2} value={form.address.state} onChange={e=>updateAddress('state',e.target.value.toUpperCase())}/></label></div></div>}
      {activeTab==='bank'&&<div className="person-tab-panel"><div className="person-tab-heading"><strong>Dados bancários</strong><span>Conta preferencial reutilizada em repasses, comissões e outros pagamentos do ERP.</span></div><div className="form-grid three-columns person-bank-grid"><label className="field field-span-2"><span>Banco</span><input value={bank.bank_name} onChange={e=>setBankField('bank_name',e.target.value)} placeholder="Ex.: Banco Inter"/></label><label className="field"><span>Código</span><input inputMode="numeric" value={bank.bank_code} onChange={e=>setBankField('bank_code',e.target.value)} placeholder="077"/></label><label className="field"><span>Agência</span><input value={bank.branch} onChange={e=>setBankField('branch',e.target.value)} placeholder="0001"/></label><label className="field field-span-2"><span>Conta</span><div className="person-account-combo"><input value={bank.account_number} onChange={e=>setBankField('account_number',e.target.value)} placeholder="00000000"/><input value={bank.account_digit} onChange={e=>setBankField('account_digit',e.target.value)} placeholder="DV" aria-label="Dígito da conta"/></div></label><label className="field"><span>Tipo de conta</span><select value={bank.account_type} onChange={e=>setBankField('account_type',e.target.value as BankAccountType)}><option value="checking">Conta corrente</option><option value="savings">Conta poupança</option><option value="payment">Conta de pagamento</option></select></label><label className="field"><span>Tipo da chave Pix</span><select value={bank.pix_key_type} onChange={e=>setBankField('pix_key_type',e.target.value as PixKeyType)}><option value="none">Sem chave Pix</option><option value="cpf_cnpj">CPF / CNPJ</option><option value="email">E-mail</option><option value="phone">Telefone</option><option value="random">Chave aleatória</option></select></label><label className="field field-span-2"><span>Chave Pix</span><input disabled={bank.pix_key_type==='none'} data-format={bank.pix_key_type==='cpf_cnpj'?'cpf-cnpj':bank.pix_key_type==='phone'?'phone':undefined} value={bank.pix_key} onChange={e=>setBankField('pix_key',e.target.value)} placeholder={bank.pix_key_type==='none'?'Selecione um tipo de chave Pix':'Informe a chave Pix'}/></label><label className="field field-span-2"><span>Titular da conta</span><input value={bank.account_holder_name} onChange={e=>setBankField('account_holder_name',e.target.value)} placeholder={form.name||'Nome do titular'}/></label><label className="field field-span-2"><span>CPF / CNPJ do titular</span><input data-format="cpf-cnpj" value={bank.account_holder_document} onChange={e=>setBankField('account_holder_document',e.target.value)} placeholder={form.document_number||'CPF ou CNPJ'}/></label></div><div className="person-tab-helper"><Landmark size={14}/><span>O cadastro bancário é único por Pessoa. Se ela também for corretor ou proprietário, o Financeiro usa estes mesmos dados.</span></div></div>}
      {activeTab==='profile'&&<div className="person-tab-panel"><div className="person-tab-heading"><strong>Dados complementares e contratuais</strong><span>Informações que normalmente seriam pedidas novamente na elaboração de contratos.</span></div><div className="form-grid three-columns">{form.person_type==='individual'?<><label className="field"><span>RG / Identidade</span><input value={profile.identity_number} onChange={e=>setProfileField('identity_number',e.target.value)}/></label><label className="field"><span>Órgão emissor</span><input value={profile.identity_issuer} onChange={e=>setProfileField('identity_issuer',e.target.value)} placeholder="Ex.: SESP/PR"/></label><label className="field"><span>Data de nascimento</span><input type="date" value={profile.birth_date} onChange={e=>setProfileField('birth_date',e.target.value)}/></label><label className="field"><span>Nacionalidade</span><input value={profile.nationality} onChange={e=>setProfileField('nationality',e.target.value)}/></label><label className="field"><span>Estado civil</span><select value={profile.marital_status} onChange={e=>setProfileField('marital_status',e.target.value as MaritalStatus)}><option value="">Não informado</option><option value="single">Solteiro(a)</option><option value="married">Casado(a)</option><option value="stable_union">União estável</option><option value="divorced">Divorciado(a)</option><option value="widowed">Viúvo(a)</option><option value="separated">Separado(a)</option><option value="other">Outro</option></select></label><label className="field field-span-2"><span>Profissão</span><input value={profile.occupation} onChange={e=>setProfileField('occupation',e.target.value)}/></label></>:<><label className="field field-span-2"><span>Nome fantasia</span><input value={profile.trade_name} onChange={e=>setProfileField('trade_name',e.target.value)}/></label><label className="field"><span>Inscrição estadual</span><input value={profile.state_registration} onChange={e=>setProfileField('state_registration',e.target.value)}/></label><label className="field"><span>Inscrição municipal</span><input value={profile.municipal_registration} onChange={e=>setProfileField('municipal_registration',e.target.value)}/></label></>}<label className="field field-span-2"><span>Telefone alternativo</span><input data-format="phone" value={profile.secondary_phone} onChange={e=>setProfileField('secondary_phone',e.target.value)}/></label><label className="field field-span-3"><span>Observações internas</span><textarea rows={4} maxLength={2000} value={form.notes??''} onChange={e=>setForm(c=>({...c,notes:e.target.value}))} placeholder="Informações complementares relevantes para a operação..."/></label></div><div className="person-tab-helper"><FileText size={14}/><span>Cônjuge, representantes e outras pessoas relacionadas devem continuar sendo cadastrados como Pessoas próprias; o vínculo será tratado na operação/contrato, evitando dados duplicados.</span></div></div>}
      {activeTab==='documents'&&editingId&&<EntityDocumentsPanel entityType="person" entityId={editingId} entityLabel={form.name||'Pessoa'} permissions={permissions} compact/>}
    </div><div className="form-actions portfolio-modal-actions"><button className="button secondary" type="button" onClick={closeModal} disabled={saving}>Cancelar</button><button className="button primary" disabled={saving||detailsLoading} type="submit">{saving?'Salvando...':editingId?'Salvar alterações':'Cadastrar pessoa'}</button></div></form></div>}</section>
}
