import { Building2, CalendarDays, Copy, Download, FileText, Home, RefreshCw, ShieldCheck, UserRound, WalletCards } from 'lucide-react'
import { useEffect, useMemo, useState } from 'react'
import { ApiError, publicApiRequest, publicBlobRequest } from '../api/client'
import './external-portal.css'

type Context='owner'|'tenant'
type Property={id:string;code:string;address:Record<string,string>;ownership_percent?:number|null;relation:Context;lease_id?:string;lease_code?:string}
type Charge={id:string;code:string;competence:string;due_date:string;property_code:string;amount:number;status:string;paid_at:string|null;boleto_line:string|null;pix_copy_paste:string|null}
type Repasse={id:string;competence:string;property_code:string;amount:number;due_date:string;status:string;paid_at:string|null}
type Payload={organization_name:string;portal_type:'person';roles:Context[];person_id:string;person_name:string;document_number:string|null;owner_properties:Property[];tenant_properties:Property[];charges:Charge[];repasses:Repasse[];owner_year_total:number;owner_open_amount:number;tenant_year_total:number;tenant_open_amount:number;last_used_at:string|null}
const money=(value:number)=>Number(value||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'})
const dateLabel=(value:string)=>new Date(`${value.slice(0,10)}T12:00:00`).toLocaleDateString('pt-BR')
const currentMonth=()=>{const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}`}
function addressLabel(address:Record<string,string>){return [address.street||address.logradouro,address.number||address.numero,address.neighborhood||address.bairro,address.city||address.cidade,address.state||address.uf].filter(Boolean).join(', ')||'Endereço não informado'}
function openBlob(blob:Blob){const url=URL.createObjectURL(blob);window.open(url,'_blank','noopener,noreferrer');setTimeout(()=>URL.revokeObjectURL(url),60000)}

export function ExternalPortalPage({token}:{token:string}){
 const [data,setData]=useState<Payload|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState(''),[month,setMonth]=useState(currentMonth()),[context,setContext]=useState<Context>('owner')
 async function load(){setLoading(true);setError('');try{const result=await publicApiRequest<Payload>(`/portal/${encodeURIComponent(token)}`);setData(result);setContext(current=>result.roles.includes(current)?current:(result.roles[0]||'owner'))}catch(e){setError(e instanceof ApiError?e.detail:'Não foi possível abrir este portal.')}finally{setLoading(false)}}
 useEffect(()=>{void load()},[token])
 async function statement(){try{openBlob(await publicBlobRequest(`/portal/${encodeURIComponent(token)}/statement.pdf?competence=${month}-01`))}catch(e){setError(e instanceof ApiError?e.detail:'Não foi possível abrir a prestação de contas.')}}
 async function annual(selected:Context){try{openBlob(await publicBlobRequest(`/portal/${encodeURIComponent(token)}/annual-income.pdf?year=${new Date().getFullYear()}&context=${selected}`))}catch(e){setError(e instanceof ApiError?e.detail:'Não foi possível abrir o documento anual.')}}
 async function copy(value:string){await navigator.clipboard.writeText(value)}
 const properties=useMemo(()=>data?(context==='owner'?data.owner_properties:data.tenant_properties):[],[data,context])
 if(loading)return <main className="external-portal-shell"><div className="external-portal-loading"><div className="external-portal-mark">IM</div><strong>Abrindo seu portal...</strong></div></main>
 if(error&&!data)return <main className="external-portal-shell"><div className="external-portal-loading"><div className="external-portal-mark">!</div><strong>Acesso indisponível</strong><span>{error}</span></div></main>
 if(!data)return null
 const owner=context==='owner';const openCharges=data.charges.filter(charge=>['generated','sent','overdue'].includes(charge.status));const yearTotal=owner?data.owner_year_total:data.tenant_year_total;const openAmount=owner?data.owner_open_amount:data.tenant_open_amount
 return <main className="external-portal-shell"><header className="external-portal-header"><div><div className="external-portal-mark">{data.organization_name.trim().slice(0,2).toUpperCase()}</div><div><strong>{data.organization_name}</strong><span>Área do cliente</span></div></div><button onClick={()=>void load()}><RefreshCw size={14}/> Atualizar</button></header><section className="external-portal-content">
 <section className="external-portal-hero"><div className="external-portal-hero-copy"><span className="external-portal-kicker">{owner?'Portal do proprietário':'Portal do locatário'}</span><h1>Olá, {data.person_name.split(' ')[0]}.</h1><p>{owner?'Acompanhe patrimônio, repasses e documentos em um único lugar.':'Acompanhe sua locação, cobranças e documentos em um único lugar.'}</p><div className="external-portal-identity"><ShieldCheck size={14}/><span>{data.document_number||'CPF/CNPJ não informado'} · acesso protegido e autorizado pela imobiliária</span></div></div><div className="external-portal-hero-badge"><UserRound size={18}/><div><small>Perfil atual</small><strong>{owner?'Proprietário':'Locatário'}</strong></div></div></section>
 {error&&<div className="external-portal-alert">{error}</div>}
 {data.roles.length>1&&<div className="external-context-switch"><div><span>Visualizando como</span><strong>{owner?'Proprietário':'Locatário'}</strong></div><div className="external-context-actions"><button className={context==='owner'?'active':''} onClick={()=>setContext('owner')}>Proprietário</button><button className={context==='tenant'?'active':''} onClick={()=>setContext('tenant')}>Locatário</button></div></div>}
 {data.roles.length===0?<section className="external-portal-card external-empty-role"><UserRound size={24}/><strong>Nenhum vínculo financeiro ativo.</strong><span>O endereço do portal continua o mesmo e passará a exibir informações automaticamente quando houver novo imóvel ou contrato.</span></section>:<>
 <div className="external-portal-metrics"><article><div className="external-metric-icon"><WalletCards size={18}/></div><div><span>{owner?'Recebido no ano':'Pago no ano'}</span><strong>{money(yearTotal)}</strong><small>{owner?'Repasses efetivamente pagos':'Pagamentos identificados no ano'}</small></div></article><article><div className="external-metric-icon"><FileText size={18}/></div><div><span>{owner?'Repasses pendentes':'Cobranças em aberto'}</span><strong>{money(openAmount)}</strong><small>{owner?'Valores ainda a repassar':'Saldo financeiro atual'}</small></div></article><article><div className="external-metric-icon"><Building2 size={18}/></div><div><span>{owner?'Imóveis no patrimônio':'Locações vinculadas'}</span><strong>{properties.length}</strong><small>{owner?'Vínculos patrimoniais ativos':'Contratos vinculados ao acesso'}</small></div></article></div>
 <div className="external-portal-main-grid"><section className="external-portal-card external-property-section"><div className="external-portal-card-head"><div><span>{owner?'Patrimônio':'Locação / contrato'}</span><h2>{owner?'Seus imóveis':'Sua locação'}</h2><p>{owner?'Visão rápida dos imóveis vinculados ao seu CPF/CNPJ.':'Imóveis e contratos vinculados ao seu acesso.'}</p></div><Home size={20}/></div><div className="external-property-grid">{properties.map(property=><article key={`${property.relation}-${property.id}`}><div className="external-property-icon"><Building2 size={16}/></div><div className="external-property-copy"><div className="external-property-topline"><small>{owner?'Imóvel':'Locação'} {property.code}</small>{owner&&property.ownership_percent!=null&&<i>{property.ownership_percent.toLocaleString('pt-BR')}%</i>}</div><strong>{addressLabel(property.address)}</strong>{!owner&&property.lease_code&&<span>Contrato · {property.lease_code}</span>}{owner&&<span>Vínculo patrimonial ativo</span>}</div></article>)}{properties.length===0&&<p>Nenhum imóvel disponível neste contexto.</p>}</div></section><aside className="external-portal-card external-documents-card"><div className="external-portal-card-head"><div><span>Autosserviço</span><h2>Documentos anuais</h2><p>Emita seus documentos sem solicitar atendimento.</p></div><CalendarDays size={20}/></div><div className="external-document-callout"><div className="external-document-icon"><FileText size={18}/></div><div><small>{new Date().getFullYear()}</small><strong>{owner?'Informe anual de rendimentos':'Comprovante anual de pagamentos'}</strong><span>{owner?'Consolidado dos repasses do ano-calendário.':'Consolidado dos pagamentos liquidados no ano.'}</span></div><button onClick={()=>void annual(context)}><Download size={14}/> Baixar PDF</button></div></aside></div>
 {owner?<section className="external-portal-card"><div className="external-portal-card-head"><div><span>Financeiro · proprietário</span><h2>Repasses</h2></div><WalletCards size={20}/></div><div className="external-portal-list">{data.repasses.map(repasse=><div key={repasse.id}><div><strong>{repasse.property_code} · {repasse.competence.slice(0,7).split('-').reverse().join('/')}</strong><span>Previsto {dateLabel(repasse.due_date)} · {repasse.status==='paid'?'Pago':'Pendente'}</span></div><strong>{money(repasse.amount)}</strong></div>)}{data.repasses.length===0&&<div className="external-empty-state"><WalletCards size={18}/><div><strong>Nenhum repasse nesta consulta</strong><span>Quando houver movimentação, os valores e datas aparecerão aqui.</span></div></div>}</div><div className="external-portal-actions"><input type="month" value={month} onChange={e=>setMonth(e.target.value)}/><button onClick={()=>void statement()}><Download size={14}/> Prestação de contas</button></div></section>:<section className="external-portal-card"><div className="external-portal-card-head"><div><span>Financeiro · locatário</span><h2>Cobranças</h2></div><FileText size={20}/></div><div className="external-portal-list">{data.charges.map(charge=><div className={charge.status==='overdue'?'overdue':''} key={charge.id}><div><strong>{charge.code} · {charge.property_code}</strong><span>Venc. {dateLabel(charge.due_date)} · {charge.status==='paid'?'Pago':charge.status==='overdue'?'Em atraso':'Em aberto'}</span>{charge.boleto_line&&<small>Linha digitável disponível</small>}{charge.pix_copy_paste&&<small>Pix disponível</small>}</div><div><strong>{money(charge.amount)}</strong>{charge.boleto_line&&<button className="external-copy" onClick={()=>void copy(charge.boleto_line!)}><Copy size={12}/> Boleto</button>}{charge.pix_copy_paste&&<button className="external-copy" onClick={()=>void copy(charge.pix_copy_paste!)}><Copy size={12}/> Pix</button>}</div></div>)}{data.charges.length===0&&<div className="external-empty-state"><FileText size={18}/><div><strong>Nenhuma cobrança disponível</strong><span>Novas cobranças e pagamentos aparecerão automaticamente nesta área.</span></div></div>}</div><div className="external-portal-actions"><span>{openCharges.length} cobrança(s) atualmente em aberto</span></div></section>}
 </>}
 </section></main>
}
