import { Building2, Copy, Download, FileText, Home, RefreshCw, WalletCards } from 'lucide-react'
import { useEffect, useState } from 'react'
import { ApiError, publicApiRequest, publicBlobRequest } from '../api/client'
import './external-portal.css'

type Property={id:string;code:string;address:Record<string,string>;ownership_percent?:number|null}
type Charge={id:string;code:string;competence:string;due_date:string;property_code:string;amount:number;status:string;paid_at:string|null;boleto_line:string|null;pix_copy_paste:string|null}
type Repasse={id:string;competence:string;property_code:string;amount:number;due_date:string;status:string;paid_at:string|null}
type Payload={organization_name:string;portal_type:'owner'|'tenant';person_id:string;person_name:string;expires_at:string;properties:Property[];charges:Charge[];repasses:Repasse[];current_year_total:number;open_amount:number}
const money=(v:number)=>Number(v||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'})
const dateLabel=(v:string)=>new Date(`${v.slice(0,10)}T12:00:00`).toLocaleDateString('pt-BR')
const currentMonth=()=>{const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}`}
function addressLabel(a:Record<string,string>){return [a.street||a.logradouro,a.number||a.numero,a.neighborhood||a.bairro,a.city||a.cidade,a.state||a.uf].filter(Boolean).join(', ')||'Endereço não informado'}
function openBlob(blob:Blob){const url=URL.createObjectURL(blob);window.open(url,'_blank','noopener,noreferrer');setTimeout(()=>URL.revokeObjectURL(url),60000)}

export function ExternalPortalPage({token}:{token:string}){
 const [data,setData]=useState<Payload|null>(null);const [loading,setLoading]=useState(true);const [error,setError]=useState('');const [month,setMonth]=useState(currentMonth())
 async function load(){setLoading(true);setError('');try{setData(await publicApiRequest<Payload>(`/portal/${encodeURIComponent(token)}`))}catch(e){setError(e instanceof ApiError?e.detail:'Não foi possível abrir este portal.')}finally{setLoading(false)}}
 useEffect(()=>{void load()},[token])
 async function pdf(type:'statement'|'annual'){try{const path=type==='statement'?`/portal/${encodeURIComponent(token)}/statement.pdf?competence=${month}-01`:`/portal/${encodeURIComponent(token)}/annual-income.pdf?year=${new Date().getFullYear()}`;openBlob(await publicBlobRequest(path))}catch(e){setError(e instanceof ApiError?e.detail:'Não foi possível abrir o documento.')}}
 async function copy(value:string){await navigator.clipboard.writeText(value)}
 if(loading)return <main className="external-portal-shell"><div className="external-portal-loading"><div className="external-portal-mark">IM</div><strong>Abrindo seu portal...</strong></div></main>
 if(error&&!data)return <main className="external-portal-shell"><div className="external-portal-loading"><div className="external-portal-mark">!</div><strong>Acesso indisponível</strong><span>{error}</span></div></main>
 if(!data)return null
 const owner=data.portal_type==='owner';const openCharges=data.charges.filter(c=>['generated','sent','overdue'].includes(c.status))
 return <main className="external-portal-shell"><header className="external-portal-header"><div><div className="external-portal-mark">{data.organization_name.trim().slice(0,2).toUpperCase()}</div><div><strong>{data.organization_name}</strong><span>{owner?'Portal do proprietário':'Portal do locatário'}</span></div></div><button onClick={()=>void load()}><RefreshCw size={14}/> Atualizar</button></header><section className="external-portal-content"><div className="external-portal-title"><div><span>Olá,</span><h1>{data.person_name}</h1><p>{owner?'Acompanhe seus imóveis, repasses e documentos financeiros.':'Acompanhe suas cobranças, pagamentos e documentos financeiros.'}</p></div><small>Acesso válido até {new Date(data.expires_at).toLocaleDateString('pt-BR')}</small></div>{error&&<div className="external-portal-alert">{error}</div>}
 <div className="external-portal-metrics"><article><WalletCards size={18}/><span>{owner?'Recebido no ano':'Pago no ano'}</span><strong>{money(data.current_year_total)}</strong></article><article><FileText size={18}/><span>{owner?'Repasses pendentes':'Em aberto'}</span><strong>{money(data.open_amount)}</strong></article><article><Building2 size={18}/><span>Imóveis vinculados</span><strong>{data.properties.length}</strong></article></div>
 <section className="external-portal-card"><div className="external-portal-card-head"><div><span>Patrimônio / contrato</span><h2>Imóveis</h2></div><Home size={20}/></div><div className="external-property-grid">{data.properties.map(p=><article key={p.id}><strong>Imóvel {p.code}</strong><span>{addressLabel(p.address)}</span>{p.ownership_percent!=null&&<small>Participação: {p.ownership_percent.toLocaleString('pt-BR')}%</small>}</article>)}</div></section>
 {owner?<section className="external-portal-card"><div className="external-portal-card-head"><div><span>Financeiro</span><h2>Repasses</h2></div><WalletCards size={20}/></div><div className="external-portal-list">{data.repasses.map(r=><div key={r.id}><div><strong>{r.property_code} · {r.competence.slice(0,7).split('-').reverse().join('/')}</strong><span>Previsto {dateLabel(r.due_date)} · {r.status==='paid'?'Pago':'Pendente'}</span></div><strong>{money(r.amount)}</strong></div>)}{data.repasses.length===0&&<p>Nenhum repasse disponível.</p>}</div><div className="external-portal-actions"><input type="month" value={month} onChange={e=>setMonth(e.target.value)}/><button onClick={()=>void pdf('statement')}><Download size={14}/> Prestação de contas</button><button onClick={()=>void pdf('annual')}><Download size={14}/> Informe anual</button></div></section>:<section className="external-portal-card"><div className="external-portal-card-head"><div><span>Financeiro</span><h2>Cobranças</h2></div><FileText size={20}/></div><div className="external-portal-list">{data.charges.map(c=><div className={c.status==='overdue'?'overdue':''} key={c.id}><div><strong>{c.code} · {c.property_code}</strong><span>Venc. {dateLabel(c.due_date)} · {c.status==='paid'?'Pago':c.status==='overdue'?'Em atraso':'Em aberto'}</span>{c.boleto_line&&<small>Linha digitável disponível</small>}{c.pix_copy_paste&&<small>Pix disponível</small>}</div><div><strong>{money(c.amount)}</strong>{c.boleto_line&&<button className="external-copy" onClick={()=>void copy(c.boleto_line!)}><Copy size={12}/> Boleto</button>}{c.pix_copy_paste&&<button className="external-copy" onClick={()=>void copy(c.pix_copy_paste!)}><Copy size={12}/> Pix</button>}</div></div>)}{data.charges.length===0&&<p>Nenhuma cobrança disponível.</p>}</div><div className="external-portal-actions"><button onClick={()=>void pdf('annual')}><Download size={14}/> Informe anual</button><span>{openCharges.length} cobrança(s) atualmente em aberto</span></div></section>}
 </section></main>
}
