import {
  Building2, CalendarDays, CheckCircle2, ClipboardCheck, Download, FileText, Home,
  KeyRound, LifeBuoy, LogOut, RefreshCw, ShieldCheck, WalletCards, Wrench, XCircle,
} from 'lucide-react'
import { FormEvent, useCallback, useEffect, useMemo, useState } from 'react'
import { ApiError, publicApiRequest, publicBlobRequest } from '../api/client'
import './tenant-portal.css'
import './owner-portal.css'

type Tab = 'home'|'properties'|'contracts'|'finance'|'documents'|'inspections'|'maintenance'|'account'
type PropertyItem={id:string;code:string;status:string;property_type:string;purpose:string;title:string;address:Record<string,string>;rent_amount:number|null;condo_amount:number|null;iptu_amount:number|null;ownership_percent:number;active_lease_id:string|null;active_lease_code:string|null;active_rent_amount:number|null;publication_enabled:boolean}
type AdminContract={id:string;code:string;property_id:string;status:string;plan:string;admin_fee_type:string;admin_fee_percent:number|null;admin_fee_amount:number|null;intermediation_percent:number;owner_repasse_business_days:number;start_date:string|null;end_date:string|null;signed_at:string|null;archive_status:string}
type Lease={id:string;code:string;property_id:string;status:string;tenant_names:string[];rent_amount:number;due_day:number;start_date:string;end_date:string;operational_end_date:string|null;adjustment_index:string;next_adjustment_date:string;guarantee_type:string;signed_at:string|null}
type Repasse={id:string;charge_id:string;lease_contract_id:string;property_id:string;competence:string|null;rent_amount:number;owner_rent_share:number;ownership_percent:number;admin_fee:number;intermediation_fee:number;agency_fee_withheld:number;other_adjustments:number;amount:number;due_date:string;status:string;paid_at:string|null;payment_reference:string|null}
type DocumentItem={key:string;title:string;category:string;filename:string;content_type:string;status:string;entity_type:string;entity_label:string|null;updated_at:string;download_path:string}
type Inspection={id:string;code:string;property_id:string;lease_contract_id:string;inspection_type:string;status:string;scheduled_at:string|null;performed_at:string|null;finalized_at:string|null;report_available:boolean}
type Maintenance={id:string;code:string;property_id:string;lease_contract_id:string|null;title:string;category:string;priority:string;status:string;description:string;responsibility:string;approval_required:boolean;owner_charge_amount:number|null;owner_decision_pending:boolean;reported_at:string;scheduled_at:string|null;completed_at:string|null}
type Annual={year:number;received_amount:number;scheduled_amount:number;repasses:number;properties:number}
type Overview={
 person:{id:string;name:string;email:string;document_number:string|null};organization:{name:string;email:string|null;phone:string|null};
 metrics:{properties:number;active_leases:number;pending_repasse_amount:number;received_this_year:number;maintenance_open:number;next_repasse_date:string|null;next_repasse_amount:number|null};
 properties:PropertyItem[];administration_contracts:AdminContract[];leases:Lease[];repasses:Repasse[];documents:DocumentItem[];inspections:Inspection[];maintenance:Maintenance[];annual_reports:Annual[]
}

const money=(value:number|null|undefined)=>Number(value||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'})
const dateLabel=(value:string|null)=>value?new Date(`${value.slice(0,10)}T12:00:00`).toLocaleDateString('pt-BR'):'—'
const dateTimeLabel=(value:string|null)=>value?new Date(value).toLocaleString('pt-BR'):'—'
const competence=(value:string|null)=>value?value.slice(0,7).split('-').reverse().join('/'):'—'
const addressLabel=(address:Record<string,string>)=>[address.street||address.logradouro,address.number||address.numero,address.complement||address.complemento,address.neighborhood||address.bairro,address.city||address.cidade,address.state||address.uf].filter(Boolean).join(', ')||'Endereço não informado'
const statusLabel=(value:string)=>({signed:'Ativo',paid:'Pago',settled:'Pago',pending:'Pendente',settled_zero:'Sem repasse',generated:'Gerado',overdue:'Em atraso',cancelled:'Cancelado',requested:'Solicitado',triage:'Em análise',awaiting_quote:'Em orçamento',awaiting_approval:'Aguardando aprovação',approved:'Aprovado',scheduled:'Agendado',in_progress:'Em execução',completed:'Concluído',draft:'Rascunho',review:'Em revisão'} as Record<string,string>)[value]||value
const maintenanceStatus=statusLabel
const inspectionType=(value:string)=>value==='initial'?'Vistoria de entrada':value==='final'?'Vistoria de saída':value
const documentCategory=(value:string)=>({contract:'Contrato',inspection:'Vistoria',finance:'Financeiro',property:'Imóvel',identity:'Cadastro',legal:'Jurídico',general:'Geral',other:'Outro'} as Record<string,string>)[value]||value
function openBlob(blob:Blob){const url=URL.createObjectURL(blob);window.open(url,'_blank','noopener,noreferrer');setTimeout(()=>URL.revokeObjectURL(url),60000)}
function Metric({icon:Icon,label,value,caption}:{icon:typeof Home;label:string;value:string;caption:string}){return <article className="tenant-metric"><Icon size={19}/><span>{label}</span><strong>{value}</strong><small>{caption}</small></article>}

export function OwnerPortalPage({onSwitchRole}:{onSwitchRole?:()=>void}){
 const [data,setData]=useState<Overview|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState(''),[success,setSuccess]=useState(''),[tab,setTab]=useState<Tab>('home'),[passwordOpen,setPasswordOpen]=useState(false)
 const load=useCallback(async()=>{setLoading(true);setError('');try{setData(await publicApiRequest<Overview>('/owner-portal/overview'))}catch(cause){setError(cause instanceof ApiError?cause.detail:'Não foi possível carregar o portal do proprietário.')}finally{setLoading(false)}},[])
 useEffect(()=>{void load()},[load])
 async function logout(){try{await publicApiRequest('/tenant-portal/auth/logout',{method:'POST'})}finally{window.location.reload()}}
 async function openDocument(item:DocumentItem){try{openBlob(await publicBlobRequest(item.download_path))}catch(cause){setError(cause instanceof ApiError?cause.detail:'Não foi possível abrir o documento.')}}
 async function openStatement(item:Repasse){if(!item.competence)return;setError('');try{const params=new URLSearchParams({property_id:item.property_id});openBlob(await publicBlobRequest(`/owner-portal/statements/${item.competence.slice(0,10)}/pdf?${params.toString()}`))}catch(cause){setError(cause instanceof ApiError?cause.detail:'Não foi possível gerar a prestação de contas.')}}
 async function openAnnualIncome(year:number){setError('');try{openBlob(await publicBlobRequest(`/owner-portal/reports/${year}/income.pdf`))}catch(cause){setError(cause instanceof ApiError?cause.detail:'Não foi possível gerar o informe de rendimentos.')}}
 async function decide(item:Maintenance,decision:'approve'|'reject'){setError('');setSuccess('');try{await publicApiRequest(`/owner-portal/maintenance/${item.id}/decision`,{method:'POST',body:JSON.stringify({decision})});setSuccess(decision==='approve'?'Orçamento aprovado. A imobiliária já pode seguir com a execução.':'Orçamento recusado. A imobiliária poderá apresentar outra opção.');await load()}catch(cause){setError(cause instanceof ApiError?cause.detail:'Não foi possível registrar a decisão.')}}
 if(loading&&!data)return <main className="tenant-login-shell"><div className="tenant-loading"><div className="tenant-brand-mark">IM</div><strong>Preparando o Portal do Proprietário...</strong></div></main>
 if(!data)return <main className="tenant-login-shell"><section className="tenant-login-card"><div className="tenant-alert danger"><XCircle size={16}/>{error||'Portal indisponível.'}</div></section></main>
 const nextRepasse=data.repasses.filter(item=>!['paid','settled','settled_zero','cancelled'].includes(item.status)).sort((a,b)=>a.due_date.localeCompare(b.due_date))[0]
 const paid=data.repasses.filter(item=>['paid','settled'].includes(item.status)).sort((a,b)=>(b.paid_at||'').localeCompare(a.paid_at||''))
 const openMaintenance=data.maintenance.filter(item=>!['completed','cancelled'].includes(item.status))
 const propertyMap=new Map(data.properties.map(item=>[item.id,item]))
 return <main className="tenant-portal-shell owner-portal-shell"><header className="tenant-topbar"><div className="tenant-brand"><div className="tenant-brand-mark">{data.organization.name.trim().slice(0,2).toUpperCase()||'IM'}</div><div><strong>{data.organization.name}</strong><span>Portal do Proprietário</span></div></div><div className="tenant-top-actions">{onSwitchRole&&<button onClick={onSwitchRole}><RefreshCw size={16}/><span>Trocar área</span></button>}<button onClick={()=>void load()}><RefreshCw size={16}/><span>Atualizar</span></button><button onClick={()=>void logout()}><LogOut size={16}/><span>Sair</span></button></div></header><div className="tenant-layout"><aside className="tenant-sidebar owner-sidebar"><div className="tenant-user"><div>{data.person.name.trim().slice(0,2).toUpperCase()}</div><strong>{data.person.name}</strong><span>Proprietário</span></div><nav>{([
  ['home','Início',Home],['properties','Imóveis',Building2],['contracts','Contratos',FileText],['finance','Financeiro',WalletCards],['documents','Documentos',FileText],['inspections','Vistorias',ClipboardCheck],['maintenance','Manutenções',Wrench],['account','Minha conta',KeyRound],
 ] as [Tab,string,typeof Home][]).map(([key,label,Icon])=><button key={key} className={tab===key?'active':''} onClick={()=>setTab(key)}><Icon size={17}/><span>{label}</span></button>)}</nav><div className="tenant-help"><LifeBuoy size={17}/><strong>Precisa de ajuda?</strong>{data.organization.phone&&<a href={`tel:${data.organization.phone}`}>{data.organization.phone}</a>}{data.organization.email&&<a href={`mailto:${data.organization.email}`}>{data.organization.email}</a>}</div></aside><section className="tenant-content">{error&&<div className="tenant-alert danger"><XCircle size={16}/>{error}</div>}{success&&<div className="tenant-alert success"><CheckCircle2 size={16}/>{success}</div>}
 {tab==='home'&&<><div className="tenant-heading"><div><span className="tenant-eyebrow">Olá, {data.person.name.split(' ')[0]}</span><h1>Resumo da sua carteira</h1><p>Imóveis, locações, repasses e pendências em um único lugar.</p></div><span className="tenant-status signed">Portal ativo</span></div><div className="tenant-metrics"><Metric icon={Building2} label="Imóveis" value={String(data.metrics.properties)} caption={`${data.metrics.active_leases} locação(ões) ativa(s)`}/><Metric icon={WalletCards} label="Próximo repasse" value={nextRepasse?money(nextRepasse.amount):'—'} caption={nextRepasse?`Previsto para ${dateLabel(nextRepasse.due_date)}`:'Nenhum repasse pendente'}/><Metric icon={CalendarDays} label="Recebido no ano" value={money(data.metrics.received_this_year)} caption="Repasses efetivamente pagos"/><Metric icon={Wrench} label="Manutenções abertas" value={String(data.metrics.maintenance_open)} caption="Chamados em andamento"/></div>{nextRepasse&&<article className="tenant-card owner-next-repasse"><div className="tenant-card-head"><div><span>Próximo repasse</span><h2>{dateLabel(nextRepasse.due_date)} · {money(nextRepasse.amount)}</h2></div><WalletCards size={20}/></div><div className="owner-breakdown"><div><span>Aluguel proporcional</span><strong>{money(nextRepasse.owner_rent_share)}</strong></div><div><span>Taxas da imobiliária</span><strong>- {money(nextRepasse.agency_fee_withheld)}</strong></div><div><span>Outros ajustes</span><strong>{nextRepasse.other_adjustments===0?'—':money(nextRepasse.other_adjustments)}</strong></div><div className="total"><span>Líquido a repassar</span><strong>{money(nextRepasse.amount)}</strong></div></div></article>}<div className="tenant-home-grid"><article className="tenant-card"><div className="tenant-card-head"><div><span>Imóveis</span><h2>Sua carteira</h2></div><Building2 size={20}/></div><div className="tenant-compact-list">{data.properties.slice(0,4).map(item=><div key={item.id}><div><strong>{item.title}</strong><span>{addressLabel(item.address)}</span></div><small className={`tenant-inline-status ${item.status}`}>{item.active_lease_id?'Locado':statusLabel(item.status)}</small></div>)}</div><button className="tenant-text-button" onClick={()=>setTab('properties')}>Ver todos os imóveis</button></article><article className="tenant-card"><div className="tenant-card-head"><div><span>Financeiro</span><h2>Últimos repasses</h2></div><WalletCards size={20}/></div><div className="tenant-compact-list">{paid.slice(0,4).map(item=><div key={item.id}><div><strong>{competence(item.competence)}</strong><span>Pago em {dateTimeLabel(item.paid_at)}</span></div><b>{money(item.amount)}</b></div>)}{paid.length===0&&<p>Nenhum repasse pago ainda.</p>}</div><button className="tenant-text-button" onClick={()=>setTab('finance')}>Abrir prestação de contas</button></article></div></>}
 {tab==='properties'&&<><div className="tenant-heading"><div><span className="tenant-eyebrow">Imóveis</span><h1>Meus imóveis</h1><p>Acompanhe situação, participação e locação atual de cada imóvel administrado.</p></div></div><div className="tenant-stack">{data.properties.map(item=><article className="tenant-card" key={item.id}><div className="tenant-card-head"><div><span>{item.code}</span><h2>{item.title}</h2></div><span className={`tenant-status ${item.active_lease_id?'signed':item.status}`}>{item.active_lease_id?'Locado':statusLabel(item.status)}</span></div><p className="tenant-address">{addressLabel(item.address)}</p><div className="tenant-detail-grid"><div><span>Participação</span><strong>{item.ownership_percent.toLocaleString('pt-BR')}%</strong></div><div><span>Aluguel atual</span><strong>{money(item.active_rent_amount||item.rent_amount)}</strong></div><div><span>Contrato de locação</span><strong>{item.active_lease_code||'Sem locação ativa'}</strong></div><div><span>Publicação</span><strong>{item.publication_enabled?'Anunciado':'Não publicado'}</strong></div></div></article>)}</div></>}
 {tab==='contracts'&&<><div className="tenant-heading"><div><span className="tenant-eyebrow">Contratos</span><h1>Contratos administrados</h1><p>Contratos de administração e locações vinculadas aos seus imóveis.</p></div></div><div className="tenant-stack"><article className="tenant-card"><div className="tenant-card-head"><div><span>Administração</span><h2>Contratos com a imobiliária</h2></div></div>{data.administration_contracts.map(item=><div className="owner-contract-row" key={item.id}><div><strong>{item.code}</strong><span>{propertyMap.get(item.property_id)?.title||'Imóvel'}</span></div><div><span>Administração</span><b>{item.admin_fee_type==='percent'?`${item.admin_fee_percent||0}%`:money(item.admin_fee_amount)}</b></div><div><span>Repasse</span><b>{item.owner_repasse_business_days} dia(s) útil(eis)</b></div><small className={`tenant-inline-status ${item.status}`}>{statusLabel(item.status)}</small></div>)}</article><article className="tenant-card"><div className="tenant-card-head"><div><span>Locações</span><h2>Contratos com locatários</h2></div></div>{data.leases.map(item=><div className="owner-contract-row" key={item.id}><div><strong>{item.code}</strong><span>{propertyMap.get(item.property_id)?.title||'Imóvel'} · {item.tenant_names.join(', ')||'Locatário'}</span></div><div><span>Aluguel</span><b>{money(item.rent_amount)}</b></div><div><span>Próximo reajuste</span><b>{dateLabel(item.next_adjustment_date)} · {item.adjustment_index}</b></div><small className={`tenant-inline-status ${item.status}`}>{statusLabel(item.status)}</small></div>)}</article></div></>}
 {tab==='finance'&&<><div className="tenant-heading"><div><span className="tenant-eyebrow">Financeiro</span><h1>Repasses e prestação de contas</h1><p>Veja o aluguel recebido, taxas, ajustes e o líquido repassado competência por competência. A memória completa pode ser aberta em PDF.</p></div></div><div className="owner-finance-summary"><article className="tenant-card"><span>Pendente de repasse</span><strong>{money(data.metrics.pending_repasse_amount)}</strong></article><article className="tenant-card"><span>Recebido no ano</span><strong>{money(data.metrics.received_this_year)}</strong></article><article className="tenant-card"><span>Próxima data</span><strong>{dateLabel(data.metrics.next_repasse_date)}</strong></article></div><article className="tenant-card"><div className="tenant-card-head"><div><span>Prestação de contas</span><h2>Histórico de repasses</h2></div></div><div className="owner-repasse-list">{data.repasses.map(item=><div className="owner-repasse-row" key={item.id}><div className="owner-repasse-main"><strong>{competence(item.competence)}</strong><span>{propertyMap.get(item.property_id)?.title||'Imóvel'} · vencimento do repasse {dateLabel(item.due_date)}</span>{item.paid_at&&<small>Pago em {dateTimeLabel(item.paid_at)}{item.payment_reference?` · ${item.payment_reference}`:''}</small>}<button type="button" className="tenant-text-button" disabled={!item.competence} onClick={()=>void openStatement(item)}><Download size={13}/> Prestação de contas em PDF</button></div><div className="owner-repasse-breakdown"><span>Aluguel <b>{money(item.owner_rent_share)}</b></span><span>Administração <b>- {money(item.admin_fee)}</b></span>{item.intermediation_fee>0&&<span>Intermediação <b>- {money(item.intermediation_fee)}</b></span>}{item.other_adjustments!==0&&<span>Ajustes <b>{money(item.other_adjustments)}</b></span>}</div><div className="owner-repasse-total"><small className={`tenant-inline-status ${item.status}`}>{statusLabel(item.status)}</small><strong>{money(item.amount)}</strong><span>Líquido</span></div></div>)}{data.repasses.length===0&&<div className="tenant-empty">Nenhum repasse disponível.</div>}</div></article></>}
 {tab==='documents'&&<><div className="tenant-heading"><div><span className="tenant-eyebrow">Documentos</span><h1>Documentos e informes</h1><p>Contratos, laudos e documentos anuais disponíveis sem solicitar atendimento à imobiliária.</p></div></div><div className="tenant-card-section-head"><div><span className="tenant-section-kicker">Documentos anuais</span><h2>Informes de rendimentos</h2><p>Consolidação dos repasses efetivamente recebidos em cada ano-calendário.</p></div><CalendarDays size={19}/></div><div className="owner-report-grid">{data.annual_reports.map(item=><article className="tenant-card" key={item.year}><span className="tenant-eyebrow">Ano-calendário</span><h2>{item.year}</h2><strong>{money(item.received_amount)}</strong><small>efetivamente recebido</small><div className="tenant-detail-grid"><div><span>Previsto</span><strong>{money(item.scheduled_amount)}</strong></div><div><span>Repasses</span><strong>{item.repasses}</strong></div><div><span>Imóveis</span><strong>{item.properties}</strong></div></div><button type="button" className="tenant-text-button" onClick={()=>void openAnnualIncome(item.year)}><Download size={13}/> Baixar informe em PDF</button></article>)}{data.annual_reports.length===0&&<article className="tenant-card tenant-empty">Ainda não há dados anuais de repasse.</article>}</div><div className="tenant-card-section-head"><div><span className="tenant-section-kicker">Demais documentos</span><h2>Contratos e laudos</h2></div><FileText size={19}/></div><div className="tenant-document-grid">{data.documents.map(item=><article className="tenant-card tenant-document" key={item.key}><div className="tenant-document-icon"><FileText size={18}/></div><div><small>{documentCategory(item.category)}</small><strong>{item.title}</strong><span>{item.entity_label||item.filename}</span><em>Atualizado em {dateTimeLabel(item.updated_at)}</em></div><button onClick={()=>void openDocument(item)}><Download size={13}/> Abrir</button></article>)}{data.documents.length===0&&<article className="tenant-card tenant-empty">Nenhum documento liberado.</article>}</div></>}
 {tab==='inspections'&&<><div className="tenant-heading"><div><span className="tenant-eyebrow">Vistorias</span><h1>Vistorias dos imóveis</h1><p>Acompanhe entrada, saída e situação dos laudos.</p></div></div><div className="tenant-stack">{data.inspections.map(item=><article className="tenant-card" key={item.id}><div className="tenant-card-head"><div><span>{inspectionType(item.inspection_type)}</span><h2>{item.code}</h2></div><span className={`tenant-inline-status ${item.status}`}>{statusLabel(item.status)}</span></div><p>{propertyMap.get(item.property_id)?.title||'Imóvel'}</p><div className="tenant-detail-grid"><div><span>Agendada</span><strong>{dateTimeLabel(item.scheduled_at)}</strong></div><div><span>Realizada</span><strong>{dateTimeLabel(item.performed_at)}</strong></div><div><span>Finalizada</span><strong>{dateTimeLabel(item.finalized_at)}</strong></div><div><span>Laudo</span><strong>{item.report_available?'Disponível':'Em preparação'}</strong></div></div></article>)}{data.inspections.length===0&&<article className="tenant-card tenant-empty">Nenhuma vistoria disponível.</article>}</div></>}
 {tab==='maintenance'&&<><div className="tenant-heading"><div><span className="tenant-eyebrow">Manutenções</span><h1>Chamados dos seus imóveis</h1><p>Acompanhe andamento e aprove orçamentos quando a despesa for de sua responsabilidade.</p></div></div><div className="tenant-stack">{data.maintenance.map(item=><article className={`tenant-card ${item.owner_decision_pending?'owner-maintenance-pending':''}`} key={item.id}><div className="tenant-card-head"><div><span>{item.code} · {propertyMap.get(item.property_id)?.title||'Imóvel'}</span><h2>{item.title}</h2></div><span className={`tenant-inline-status ${item.status}`}>{maintenanceStatus(item.status)}</span></div><p>{item.description}</p><div className="tenant-maintenance-meta"><span>Responsabilidade <b>{item.responsibility==='owner'?'Proprietário':item.responsibility==='tenant'?'Locatário':item.responsibility==='agency'?'Imobiliária':'Em definição'}</b></span><span>Aberto em <b>{dateTimeLabel(item.reported_at)}</b></span>{item.scheduled_at&&<span>Agendado <b>{dateTimeLabel(item.scheduled_at)}</b></span>}</div>{item.owner_charge_amount!==null&&<div className="owner-commercial-value"><span>Valor apresentado ao proprietário</span><strong>{money(item.owner_charge_amount)}</strong><small>Este é o valor comercial da manutenção para sua aprovação.</small></div>}{item.owner_decision_pending&&<div className="owner-decision-actions"><button className="tenant-secondary" onClick={()=>void decide(item,'reject')}>Recusar orçamento</button><button className="tenant-primary" onClick={()=>void decide(item,'approve')}><ShieldCheck size={14}/> Aprovar orçamento</button></div>}</article>)}{data.maintenance.length===0&&<article className="tenant-card tenant-empty">Nenhuma manutenção registrada.</article>}</div></>}
 {tab==='account'&&<><div className="tenant-heading"><div><span className="tenant-eyebrow">Minha conta</span><h1>Dados e segurança</h1><p>Consulte seu cadastro e altere sua senha de acesso.</p></div></div><article className="tenant-card"><div className="tenant-detail-grid"><div><span>Nome</span><strong>{data.person.name}</strong></div><div><span>CPF/CNPJ</span><strong>{data.person.document_number||'—'}</strong></div><div><span>E-mail</span><strong>{data.person.email||'Não informado'}</strong></div><div><span>Perfil</span><strong>Proprietário</strong></div></div><button className="tenant-primary owner-account-button" onClick={()=>setPasswordOpen(true)}><KeyRound size={14}/> Alterar senha</button></article></>}
 </section></div>{passwordOpen&&<PasswordModal onClose={()=>setPasswordOpen(false)} onSuccess={()=>{setPasswordOpen(false);setSuccess('Senha alterada com sucesso. As demais sessões foram encerradas.')}}/>}</main>
}

function PasswordModal({onClose,onSuccess}:{onClose:()=>void;onSuccess:()=>void}){
 const [current,setCurrent]=useState(''),[next,setNext]=useState(''),[confirm,setConfirm]=useState(''),[error,setError]=useState(''),[saving,setSaving]=useState(false)
 async function submit(event:FormEvent){event.preventDefault();setError('');if(next!==confirm){setError('As novas senhas não coincidem.');return}setSaving(true);try{await publicApiRequest('/tenant-portal/account/password',{method:'POST',body:JSON.stringify({current_password:current,new_password:next})});onSuccess()}catch(cause){setError(cause instanceof ApiError?cause.detail:'Não foi possível alterar a senha.')}finally{setSaving(false)}}
 return <div className="tenant-modal-backdrop" onMouseDown={event=>{if(event.currentTarget===event.target&&!saving)onClose()}}><form className="tenant-modal" onSubmit={submit}><div className="tenant-modal-head"><div><span className="tenant-eyebrow">Segurança</span><h2>Alterar senha</h2><p>A sessão atual permanece aberta; outras sessões serão encerradas.</p></div><button type="button" onClick={onClose}>×</button></div>{error&&<div className="tenant-alert danger"><XCircle size={16}/>{error}</div>}<label><span>Senha atual</span><input type="password" value={current} onChange={e=>setCurrent(e.target.value)} minLength={8} required/></label><label><span>Nova senha</span><input type="password" value={next} onChange={e=>setNext(e.target.value)} minLength={8} required/></label><label><span>Confirmar nova senha</span><input type="password" value={confirm} onChange={e=>setConfirm(e.target.value)} minLength={8} required/></label><div className="tenant-modal-actions"><button type="button" className="tenant-secondary" onClick={onClose}>Cancelar</button><button className="tenant-primary" disabled={saving}>{saving?'Salvando...':'Salvar nova senha'}</button></div></form></div>
}
