import {
  Building2, CalendarDays, CheckCircle2, ClipboardCheck, Copy, Download, FileText,
  Home, KeyRound, LifeBuoy, LogOut, RefreshCw, ShieldCheck, Wrench, XCircle,
} from 'lucide-react'
import { FormEvent, useCallback, useEffect, useMemo, useState } from 'react'
import { ApiError, publicApiRequest, publicBlobRequest } from '../api/client'
import './tenant-portal.css'

type Tab = 'home' | 'contract' | 'payments' | 'documents' | 'inspections' | 'maintenance'
type Me = { person_id:string; person_name:string; email:string; document_number:string|null; organization_name:string; organization_email:string|null; organization_phone:string|null }
type Lease = { id:string; code:string; status:string; property_id:string; property_code:string; property_address:Record<string,string>; rent_amount:number; due_day:number; start_date:string; end_date:string; operational_end_date:string|null; adjustment_index:string; adjustment_period_months:number; next_adjustment_date:string; guarantee_type:string; signed_at:string|null }
type Charge = { id:string; code:string; lease_contract_id:string; competence:string; due_date:string; amount:number; status:string; paid_at:string|null; paid_amount:number|null; boleto_line:string|null; pix_copy_paste:string|null; billing_pdf_available:boolean }
type DocumentItem = { key:string; title:string; category:string; filename:string; content_type:string; status:string; entity_label:string|null; updated_at:string; download_path:string }
type Inspection = { id:string; code:string; lease_contract_id:string; inspection_type:string; status:string; scheduled_at:string|null; performed_at:string|null; contest_deadline:string|null; finalized_at:string|null; report_available:boolean }
type Maintenance = { id:string; code:string; lease_contract_id:string|null; title:string; category:string; priority:string; status:string; description:string; reported_at:string; scheduled_at:string|null; completed_at:string|null }
type Overview = {
  person:{id:string;name:string;email:string;document_number:string|null}; organization:{name:string;email:string|null;phone:string|null};
  metrics:{active_leases:number;open_amount:number;open_charges:number;maintenance_open:number;next_due_date:string|null};
  leases:Lease[];charges:Charge[];documents:DocumentItem[];inspections:Inspection[];maintenance:Maintenance[]
}

const money=(value:number)=>Number(value||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'})
const dateLabel=(value:string|null)=>value?new Date(`${value.slice(0,10)}T12:00:00`).toLocaleDateString('pt-BR'):'—'
const dateTimeLabel=(value:string|null)=>value?new Date(value).toLocaleString('pt-BR'):'—'
const addressLabel=(address:Record<string,string>)=>[address.street||address.logradouro,address.number||address.numero,address.complement||address.complemento,address.neighborhood||address.bairro,address.city||address.cidade,address.state||address.uf].filter(Boolean).join(', ')||'Endereço não informado'
const chargeStatus=(value:string)=>value==='paid'?'Pago':value==='overdue'?'Em atraso':value==='cancelled'?'Cancelado':'Em aberto'
const maintenanceStatus=(value:string)=>({requested:'Solicitado',triage:'Em análise',quoted:'Orçamento',approved:'Aprovado',scheduled:'Agendado',in_progress:'Em execução',completed:'Concluído',cancelled:'Cancelado'} as Record<string,string>)[value]||value
const inspectionType=(value:string)=>value==='initial'?'Vistoria de entrada':value==='final'?'Vistoria de saída':value
const documentCategory=(value:string)=>({contract:'Contrato',inspection:'Vistoria',maintenance:'Manutenção',finance:'Financeiro',property:'Imóvel',identity:'Cadastro',legal:'Jurídico',general:'Geral',other:'Outro'} as Record<string,string>)[value]||value
function openBlob(blob:Blob){const url=URL.createObjectURL(blob);window.open(url,'_blank','noopener,noreferrer');setTimeout(()=>URL.revokeObjectURL(url),60000)}

function PortalLogin({onAuthenticated}:{onAuthenticated:()=>void}){
  const [email,setEmail]=useState(''),[password,setPassword]=useState(''),[error,setError]=useState(''),[saving,setSaving]=useState(false)
  async function submit(event:FormEvent){event.preventDefault();setSaving(true);setError('');try{await publicApiRequest('/tenant-portal/auth/login',{method:'POST',body:JSON.stringify({email,password})});onAuthenticated()}catch(cause){setError(cause instanceof ApiError?cause.detail:'Não foi possível entrar no portal.')}finally{setSaving(false)}}
  return <main className="tenant-login-shell"><section className="tenant-login-card"><div className="tenant-login-brand"><div className="tenant-brand-mark">IM</div><div><strong>Portal do Inquilino</strong><span>Acesso seguro à sua locação</span></div></div><div className="tenant-login-copy"><span className="tenant-eyebrow">Bem-vindo</span><h1>Sua locação em um só lugar.</h1><p>Consulte contrato, pagamentos, documentos, vistorias e acompanhe chamados de manutenção.</p></div>{error&&<div className="tenant-alert danger"><XCircle size={16}/><span>{error}</span></div>}<form onSubmit={submit}><label><span>E-mail</span><input type="email" value={email} onChange={e=>setEmail(e.target.value)} autoComplete="email" required placeholder="voce@email.com"/></label><label><span>Senha</span><input type="password" value={password} onChange={e=>setPassword(e.target.value)} autoComplete="current-password" minLength={8} required placeholder="Sua senha"/></label><button className="tenant-primary" disabled={saving}>{saving?'Entrando...':'Entrar no portal'}</button></form><small>O acesso é liberado pela imobiliária para o e-mail cadastrado no seu contrato.</small></section></main>
}

function Metric({icon:Icon,label,value,caption}:{icon:typeof Home;label:string;value:string;caption:string}){return <article className="tenant-metric"><Icon size={19}/><span>{label}</span><strong>{value}</strong><small>{caption}</small></article>}

export function TenantPortalPage(){
  const [me,setMe]=useState<Me|null>(null),[data,setData]=useState<Overview|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState(''),[tab,setTab]=useState<Tab>('home'),[maintenanceOpen,setMaintenanceOpen]=useState(false)
  const load=useCallback(async()=>{setLoading(true);setError('');try{const [profile,overview]=await Promise.all([publicApiRequest<Me>('/tenant-portal/me'),publicApiRequest<Overview>('/tenant-portal/overview')]);setMe(profile);setData(overview)}catch(cause){if(cause instanceof ApiError&&cause.status===401){setMe(null);setData(null)}else setError(cause instanceof ApiError?cause.detail:'Não foi possível carregar o portal.')}finally{setLoading(false)}},[])
  useEffect(()=>{void load()},[load])
  async function logout(){try{await publicApiRequest('/tenant-portal/auth/logout',{method:'POST'})}finally{setMe(null);setData(null);setTab('home')}}
  async function copy(value:string,label:string){try{await navigator.clipboard.writeText(value);setError(`${label} copiado.`);setTimeout(()=>setError(''),1800)}catch{setError(`Não foi possível copiar ${label.toLowerCase()}.`)}}
  async function openDocument(item:DocumentItem){try{openBlob(await publicBlobRequest(item.download_path))}catch(cause){setError(cause instanceof ApiError?cause.detail:'Não foi possível abrir o documento.')}}
  async function openBilling(charge:Charge){try{openBlob(await publicBlobRequest(`/tenant-portal/charges/${charge.id}/billing.pdf`))}catch(cause){setError(cause instanceof ApiError?cause.detail:'Não foi possível abrir o boleto.') }}
  if(loading&&!me)return <main className="tenant-login-shell"><div className="tenant-loading"><div className="tenant-brand-mark">IM</div><strong>Preparando seu portal...</strong></div></main>
  if(!me||!data)return <PortalLogin onAuthenticated={()=>void load()}/>
  const activeLease=data.leases.find(item=>item.status==='signed')||data.leases[0]||null
  const openCharges=data.charges.filter(item=>['generated','sent','overdue'].includes(item.status))
  return <main className="tenant-portal-shell"><header className="tenant-topbar"><div className="tenant-brand"><div className="tenant-brand-mark">{data.organization.name.trim().slice(0,2).toUpperCase()||'IM'}</div><div><strong>{data.organization.name}</strong><span>Portal do Inquilino</span></div></div><div className="tenant-top-actions"><button onClick={()=>void load()} title="Atualizar"><RefreshCw size={16}/><span>Atualizar</span></button><button onClick={()=>void logout()} title="Sair"><LogOut size={16}/><span>Sair</span></button></div></header><div className="tenant-layout"><aside className="tenant-sidebar"><div className="tenant-user"><div>{data.person.name.trim().slice(0,2).toUpperCase()}</div><strong>{data.person.name}</strong><span>{data.person.email}</span></div><nav>{([
    ['home','Início',Home],['contract','Contrato',Building2],['payments','Pagamentos',CalendarDays],['documents','Documentos',FileText],['inspections','Vistorias',ClipboardCheck],['maintenance','Manutenção',Wrench],
  ] as [Tab,string,typeof Home][]).map(([key,label,Icon])=><button key={key} className={tab===key?'active':''} onClick={()=>setTab(key)}><Icon size={17}/><span>{label}</span></button>)}</nav><div className="tenant-help"><LifeBuoy size={17}/><strong>Precisa de ajuda?</strong>{data.organization.phone&&<a href={`tel:${data.organization.phone}`}>{data.organization.phone}</a>}{data.organization.email&&<a href={`mailto:${data.organization.email}`}>{data.organization.email}</a>}</div></aside><section className="tenant-content">{error&&<div className={`tenant-alert ${error.endsWith('copiado.')?'success':'danger'}`}>{error.endsWith('copiado.')?<CheckCircle2 size={16}/>:<XCircle size={16}/>}<span>{error}</span></div>}
  {tab==='home'&&<><div className="tenant-heading"><div><span className="tenant-eyebrow">Olá, {data.person.name.split(' ')[0]}</span><h1>Resumo da sua locação</h1><p>Acompanhe o que precisa da sua atenção e acesse rapidamente os principais itens do contrato.</p></div>{activeLease&&<span className={`tenant-status ${activeLease.status}`}>{activeLease.status==='signed'?'Locação ativa':'Contrato encerrado'}</span>}</div><div className="tenant-metrics"><Metric icon={Building2} label="Locações ativas" value={String(data.metrics.active_leases)} caption={activeLease?.code||'Nenhum contrato ativo'}/><Metric icon={CalendarDays} label="Próximo vencimento" value={dateLabel(data.metrics.next_due_date)} caption={`${data.metrics.open_charges} cobrança(s) em aberto`}/><Metric icon={KeyRound} label="Saldo em aberto" value={money(data.metrics.open_amount)} caption={openCharges.some(item=>item.status==='overdue')?'Existe cobrança em atraso':'Situação financeira atual'}/><Metric icon={Wrench} label="Chamados abertos" value={String(data.metrics.maintenance_open)} caption="Manutenções em andamento"/></div>{activeLease&&<article className="tenant-card tenant-property-card"><div className="tenant-card-head"><div><span>Seu imóvel</span><h2>{activeLease.code}</h2></div><Home size={20}/></div><strong>{addressLabel(activeLease.property_address)}</strong><div className="tenant-property-details"><span>Aluguel <b>{money(activeLease.rent_amount)}</b></span><span>Vencimento <b>dia {activeLease.due_day}</b></span><span>Reajuste <b>{activeLease.adjustment_index}</b></span><span>Próximo reajuste <b>{dateLabel(activeLease.next_adjustment_date)}</b></span></div></article>}<div className="tenant-home-grid"><article className="tenant-card"><div className="tenant-card-head"><div><span>Financeiro</span><h2>Cobranças recentes</h2></div><CalendarDays size={20}/></div><div className="tenant-compact-list">{data.charges.slice(0,4).map(item=><div key={item.id}><div><strong>{item.code}</strong><span>Vence {dateLabel(item.due_date)}</span></div><div><b>{money(item.amount)}</b><small className={`tenant-inline-status ${item.status}`}>{chargeStatus(item.status)}</small></div></div>)}{data.charges.length===0&&<p>Nenhuma cobrança disponível.</p>}</div><button className="tenant-text-button" onClick={()=>setTab('payments')}>Ver todos os pagamentos</button></article><article className="tenant-card"><div className="tenant-card-head"><div><span>Manutenção</span><h2>Últimos chamados</h2></div><Wrench size={20}/></div><div className="tenant-compact-list">{data.maintenance.slice(0,4).map(item=><div key={item.id}><div><strong>{item.code}</strong><span>{item.title}</span></div><small className={`tenant-inline-status ${item.status}`}>{maintenanceStatus(item.status)}</small></div>)}{data.maintenance.length===0&&<p>Nenhum chamado aberto até agora.</p>}</div><button className="tenant-text-button" onClick={()=>setMaintenanceOpen(true)}>Abrir novo chamado</button></article></div></>}
  {tab==='contract'&&<><div className="tenant-heading"><div><span className="tenant-eyebrow">Contrato</span><h1>Dados da locação</h1><p>Condições principais registradas no contrato assinado.</p></div></div><div className="tenant-stack">{data.leases.map(lease=><article className="tenant-card" key={lease.id}><div className="tenant-card-head"><div><span>{lease.status==='signed'?'Contrato vigente':'Histórico'}</span><h2>{lease.code}</h2></div><span className={`tenant-status ${lease.status}`}>{lease.status==='signed'?'Ativo':'Encerrado'}</span></div><p className="tenant-address">{addressLabel(lease.property_address)}</p><div className="tenant-detail-grid"><div><span>Aluguel</span><strong>{money(lease.rent_amount)}</strong></div><div><span>Vencimento</span><strong>Dia {lease.due_day}</strong></div><div><span>Início</span><strong>{dateLabel(lease.start_date)}</strong></div><div><span>Término previsto</span><strong>{dateLabel(lease.end_date)}</strong></div><div><span>Índice de reajuste</span><strong>{lease.adjustment_index}</strong></div><div><span>Próximo reajuste</span><strong>{dateLabel(lease.next_adjustment_date)}</strong></div><div><span>Garantia</span><strong>{lease.guarantee_type}</strong></div><div><span>Data da assinatura</span><strong>{dateTimeLabel(lease.signed_at)}</strong></div></div></article>)}{data.leases.length===0&&<article className="tenant-card tenant-empty">Nenhum contrato de locação vinculado a esta conta.</article>}</div></>}
  {tab==='payments'&&<><div className="tenant-heading"><div><span className="tenant-eyebrow">Financeiro</span><h1>Pagamentos e cobranças</h1><p>Consulte vencimentos, histórico e copie Pix ou linha digitável quando disponíveis.</p></div></div><article className="tenant-card"><div className="tenant-payment-list">{data.charges.map(charge=><div className={`tenant-payment-row ${charge.status}`} key={charge.id}><div className="tenant-payment-main"><div><strong>{charge.code}</strong><span>Competência {charge.competence.slice(0,7).split('-').reverse().join('/')} · vencimento {dateLabel(charge.due_date)}</span></div><small className={`tenant-inline-status ${charge.status}`}>{chargeStatus(charge.status)}</small></div><div className="tenant-payment-value"><strong>{money(charge.amount)}</strong>{charge.paid_at&&<span>Pago em {dateTimeLabel(charge.paid_at)}</span>}</div><div className="tenant-payment-actions">{charge.pix_copy_paste&&<button onClick={()=>void copy(charge.pix_copy_paste!,'Pix')}><Copy size={13}/> Copiar Pix</button>}{charge.boleto_line&&<button onClick={()=>void copy(charge.boleto_line!,'Linha digitável')}><Copy size={13}/> Linha digitável</button>}{charge.billing_pdf_available&&<button onClick={()=>void openBilling(charge)}><Download size={13}/> PDF</button>}</div></div>)}{data.charges.length===0&&<div className="tenant-empty">Nenhuma cobrança disponível.</div>}</div></article></>}
  {tab==='documents'&&<><div className="tenant-heading"><div><span className="tenant-eyebrow">Arquivos</span><h1>Documentos da locação</h1><p>Contratos, laudos e documentos vinculados aos seus contratos.</p></div></div><div className="tenant-document-grid">{data.documents.map(item=><article className="tenant-card tenant-document" key={item.key}><div className="tenant-document-icon"><FileText size={20}/></div><div><small>{documentCategory(item.category)}</small><strong>{item.title}</strong><span>{item.filename}</span><em>Atualizado em {dateTimeLabel(item.updated_at)}</em></div><button onClick={()=>void openDocument(item)}><Download size={15}/> Abrir</button></article>)}{data.documents.length===0&&<article className="tenant-card tenant-empty">Nenhum documento disponível.</article>}</div></>}
  {tab==='inspections'&&<><div className="tenant-heading"><div><span className="tenant-eyebrow">Vistorias</span><h1>Vistorias do imóvel</h1><p>Acompanhe entrada, saída e prazos relacionados aos laudos.</p></div></div><div className="tenant-stack">{data.inspections.map(item=><article className="tenant-card" key={item.id}><div className="tenant-card-head"><div><span>{inspectionType(item.inspection_type)}</span><h2>{item.code}</h2></div><span className={`tenant-inline-status ${item.status}`}>{item.status}</span></div><div className="tenant-detail-grid"><div><span>Agendada</span><strong>{dateTimeLabel(item.scheduled_at)}</strong></div><div><span>Realizada</span><strong>{dateTimeLabel(item.performed_at)}</strong></div><div><span>Prazo de contestação</span><strong>{dateTimeLabel(item.contest_deadline)}</strong></div><div><span>Finalizada</span><strong>{dateTimeLabel(item.finalized_at)}</strong></div></div></article>)}{data.inspections.length===0&&<article className="tenant-card tenant-empty">Nenhuma vistoria disponível.</article>}</div></>}
  {tab==='maintenance'&&<><div className="tenant-heading"><div><span className="tenant-eyebrow">Manutenção</span><h1>Chamados do imóvel</h1><p>Abra um chamado e acompanhe o andamento sem precisar sair do portal.</p></div><button className="tenant-primary compact" onClick={()=>setMaintenanceOpen(true)}><Wrench size={14}/> Novo chamado</button></div><div className="tenant-stack">{data.maintenance.map(item=><article className="tenant-card" key={item.id}><div className="tenant-card-head"><div><span>{item.code}</span><h2>{item.title}</h2></div><span className={`tenant-inline-status ${item.status}`}>{maintenanceStatus(item.status)}</span></div><p>{item.description}</p><div className="tenant-maintenance-meta"><span>Prioridade <b>{item.priority}</b></span><span>Aberto em <b>{dateTimeLabel(item.reported_at)}</b></span>{item.scheduled_at&&<span>Agendado <b>{dateTimeLabel(item.scheduled_at)}</b></span>}</div></article>)}{data.maintenance.length===0&&<article className="tenant-card tenant-empty">Você ainda não possui chamados de manutenção.</article>}</div></>}
  </section></div>{maintenanceOpen&&<MaintenanceModal leases={data.leases.filter(item=>item.status==='signed')} onClose={()=>setMaintenanceOpen(false)} onCreated={async()=>{setMaintenanceOpen(false);await load();setTab('maintenance')}}/>}</main>
}

function MaintenanceModal({leases,onClose,onCreated}:{leases:Lease[];onClose:()=>void;onCreated:()=>Promise<void>}){
  const [leaseId,setLeaseId]=useState(leases[0]?.id||''),[title,setTitle]=useState(''),[category,setCategory]=useState('general'),[priority,setPriority]=useState('normal'),[description,setDescription]=useState(''),[error,setError]=useState(''),[saving,setSaving]=useState(false)
  const selected=useMemo(()=>leases.find(item=>item.id===leaseId),[leases,leaseId])
  async function submit(event:FormEvent){event.preventDefault();setSaving(true);setError('');try{await publicApiRequest('/tenant-portal/maintenance',{method:'POST',body:JSON.stringify({lease_contract_id:leaseId,title,category,priority,description})});await onCreated()}catch(cause){setError(cause instanceof ApiError?cause.detail:'Não foi possível abrir o chamado.')}finally{setSaving(false)}}
  return <div className="tenant-modal-backdrop" onMouseDown={event=>{if(event.currentTarget===event.target&&!saving)onClose()}}><form className="tenant-modal" onSubmit={submit} role="dialog" aria-modal="true"><div className="tenant-modal-head"><div><span className="tenant-eyebrow">Novo chamado</span><h2>Solicitar manutenção</h2><p>Descreva o problema com clareza para facilitar a triagem da imobiliária.</p></div><button type="button" onClick={onClose} disabled={saving}>×</button></div>{error&&<div className="tenant-alert danger"><XCircle size={16}/>{error}</div>}<label><span>Locação</span><select value={leaseId} onChange={e=>setLeaseId(e.target.value)} required>{leases.map(item=><option key={item.id} value={item.id}>{item.code} · {addressLabel(item.property_address)}</option>)}</select></label>{selected&&<small className="tenant-selected-address">{addressLabel(selected.property_address)}</small>}<div className="tenant-form-grid"><label><span>Título</span><input value={title} onChange={e=>setTitle(e.target.value)} required minLength={3} placeholder="Ex.: Vazamento na cozinha"/></label><label><span>Categoria</span><select value={category} onChange={e=>setCategory(e.target.value)}><option value="general">Geral</option><option value="hydraulic">Hidráulica</option><option value="electrical">Elétrica</option><option value="structural">Estrutural</option><option value="appliance">Equipamento</option><option value="other">Outro</option></select></label><label><span>Prioridade</span><select value={priority} onChange={e=>setPriority(e.target.value)}><option value="low">Baixa</option><option value="normal">Normal</option><option value="high">Alta</option><option value="urgent">Urgente</option></select></label></div><label><span>Descrição</span><textarea value={description} onChange={e=>setDescription(e.target.value)} required minLength={5} rows={5} placeholder="Informe onde ocorre, quando começou e outros detalhes úteis."/></label><div className="tenant-modal-actions"><button type="button" className="tenant-secondary" onClick={onClose} disabled={saving}>Cancelar</button><button className="tenant-primary" disabled={saving||!leaseId}>{saving?'Enviando...':'Abrir chamado'}</button></div></form></div>
}
