import { Camera, CheckCircle2, ChevronDown, ChevronUp, ClipboardCheck, FileText, KeyRound, Plus, RotateCcw, ShieldCheck, Trash2 } from 'lucide-react'
import { FormEvent, useCallback, useEffect, useMemo, useState } from 'react'
import { ApiError, apiBlobRequest, apiRequest } from '../../api/client'

type Lease = { id:string; code:string; property_id:string; property_code:string; property_address:Record<string,string>; tenants:Array<{name:string}>; status:string; archive_status:string; final_document_hash:string|null; inspection_contest_days:number }
type Photo = { id:string; filename:string; content_type:string; reference:string; uploaded_at:string }
type ItemCondition = 'excellent'|'good'|'regular'|'poor'|'damaged'|'not_applicable'
type InspectionItem = { key:string; label:string; condition:ItemCondition; notes:string|null; photos:Photo[] }
type Environment = { key:string; name:string; notes:string|null; items:InspectionItem[] }
type Contestation = { id:string; environment_key:string; item_key:string; description:string; created_at:string; resolution:string|null; resolved_at:string|null }
type Handover = { id:string; handed_over_at:string; recipient_name:string; recipient_document:string|null; keys:Array<{label:string;quantity:number;notes?:string|null}>; meter_readings:Record<string,unknown>; notes:string|null; created_at:string }
type Inspection = { id:string; code:string; inspection_type:'initial'|'final'; status:'draft'|'ready'|'contested'|'finalized'|'cancelled'; lease_contract_id:string; lease_code:string; property_id:string; property_code:string; property_address:Record<string,string>; tenants:Array<{name:string}>; environments:Environment[]; contestations:Contestation[]; inspector_name:string|null; scheduled_at:string|null; performed_at:string|null; contest_deadline:string|null; finalized_at:string|null; notes:string|null; current_version:number; report_reference:string|null; report_hash:string|null; report_version:number|null; key_handover:Handover|null; versions:Array<{version_number:number;change_summary:string|null;created_at:string}> }
type FormState = { lease_contract_id:string; scheduled_at:string; inspector_name:string; environments:Environment[]; notes:string }

const conditionLabels:Record<ItemCondition,string> = { excellent:'Excelente', good:'Bom', regular:'Regular', poor:'Ruim', damaged:'Danificado', not_applicable:'N/A' }
const statusLabels:Record<Inspection['status'],string> = { draft:'Rascunho', ready:'Laudo concluído', contested:'Contestada', finalized:'Finalizada', cancelled:'Cancelada' }
function key(prefix:string){ return `${prefix}-${Math.random().toString(36).slice(2,9)}` }
function defaultEnvironments():Environment[]{ return ['Sala','Cozinha','Quarto','Banheiro','Área de serviço'].map((name,index)=>({key:`amb-${index+1}`,name,notes:null,items:[{key:`item-${index+1}-1`,label:'Condição geral',condition:'good',notes:null,photos:[]}]})) }
function blankForm():FormState { return {lease_contract_id:'',scheduled_at:'',inspector_name:'',environments:defaultEnvironments(),notes:''} }
function addressLine(address:Record<string,string>){ return [address.street,address.number,address.neighborhood,address.city].filter(Boolean).join(', ') || 'Endereço não informado' }
function localInput(value:string|null){ if(!value)return ''; const d=new Date(value); const off=d.getTimezoneOffset(); return new Date(d.getTime()-off*60000).toISOString().slice(0,16) }
function iso(value:string){ return value ? new Date(value).toISOString() : null }

export function InspectionsPage({permissions}:{permissions:string[]}){
  const canManage=permissions.includes('inspections.manage')
  const [items,setItems]=useState<Inspection[]>([]); const [leases,setLeases]=useState<Lease[]>([])
  const [loading,setLoading]=useState(true); const [saving,setSaving]=useState(false); const [error,setError]=useState(''); const [success,setSuccess]=useState('')
  const [showForm,setShowForm]=useState(false); const [editing,setEditing]=useState<Inspection|null>(null); const [form,setForm]=useState<FormState>(blankForm()); const [changeSummary,setChangeSummary]=useState('')
  const [expanded,setExpanded]=useState<string|null>(null); const [handoverFor,setHandoverFor]=useState<string|null>(null)
  const [query,setQuery]=useState(''); const [statusFilter,setStatusFilter]=useState<'all'|Inspection['status']>('all'); const [typeFilter,setTypeFilter]=useState<'all'|Inspection['inspection_type']>('all')

  const load=useCallback(async()=>{ setLoading(true);setError('');try{const [inspections,contracts]=await Promise.all([apiRequest<Inspection[]>('/inspections'),apiRequest<Lease[]>('/lease-contracts')]);setItems(inspections);setLeases(contracts)}catch(cause){setError(cause instanceof ApiError?cause.detail:'Não foi possível carregar as vistorias.')}finally{setLoading(false)}},[])
  useEffect(()=>{void load()},[load])
  const eligibleLeases=useMemo(()=>leases.filter(lease=>lease.status==='signed'&&lease.archive_status==='archived'&&lease.final_document_hash&&!items.some(item=>item.lease_contract_id===lease.id&&item.inspection_type==='initial')), [leases,items])
  const metrics=useMemo(()=>({draft:items.filter(i=>i.status==='draft').length,ready:items.filter(i=>i.status==='ready').length,contested:items.filter(i=>i.status==='contested').length,finalized:items.filter(i=>i.status==='finalized').length}),[items])
  const visibleItems=useMemo(()=>{const term=query.trim().toLowerCase();return items.filter(item=>{const statusOk=statusFilter==='all'||item.status===statusFilter;const typeOk=typeFilter==='all'||item.inspection_type===typeFilter;const haystack=`${item.code} ${item.lease_code} ${item.property_code} ${addressLine(item.property_address)} ${item.tenants.map(t=>t.name).join(' ')}`.toLowerCase();return statusOk&&typeOk&&(!term||haystack.includes(term))})},[items,query,statusFilter,typeFilter])

  function openNew(){setEditing(null);setForm(blankForm());setChangeSummary('');setShowForm(true);setError('');setSuccess('')}
  function openEdit(item:Inspection){setEditing(item);setForm({lease_contract_id:item.lease_contract_id,scheduled_at:localInput(item.scheduled_at),inspector_name:item.inspector_name??'',environments:item.environments.map(e=>({...e,items:e.items.map(i=>({...i,photos:[...i.photos]}))})),notes:item.notes??''});setChangeSummary('');setShowForm(true)}
  function updateEnvironment(index:number,patch:Partial<Environment>){setForm(current=>({...current,environments:current.environments.map((entry,i)=>i===index?{...entry,...patch}:entry)}))}
  function updateItem(envIndex:number,itemIndex:number,patch:Partial<InspectionItem>){setForm(current=>({...current,environments:current.environments.map((env,i)=>i===envIndex?{...env,items:env.items.map((item,j)=>j===itemIndex?{...item,...patch}:item)}:env)}))}
  async function save(event:FormEvent){event.preventDefault();setSaving(true);setError('');setSuccess('');try{const body={lease_contract_id:form.lease_contract_id,scheduled_at:iso(form.scheduled_at),inspector_name:form.inspector_name||null,environments:form.environments,notes:form.notes||null};const result=await apiRequest<Inspection>(editing?`/inspections/${editing.id}`:'/inspections',{method:editing?'PUT':'POST',body:JSON.stringify(editing?{...body,change_summary:changeSummary}:body)});setShowForm(false);setEditing(null);await load();setSuccess(editing?`${result.code} ganhou a versão ${result.current_version}.`:`${result.code} criada. Agora você pode anexar fotos e concluir o laudo.`)}catch(cause){setError(cause instanceof ApiError?cause.detail:'Não foi possível salvar a vistoria.')}finally{setSaving(false)}}
  async function workflow(item:Inspection,action:'complete'|'return_draft'|'finalize'|'cancel'){let reason:string|null=null;if(action==='cancel'){reason=window.prompt('Motivo do cancelamento:');if(!reason?.trim())return}setSaving(true);setError('');try{const result=await apiRequest<Inspection>(`/inspections/${item.id}/workflow`,{method:'POST',body:JSON.stringify({action,reason})});await load();setSuccess(action==='complete'?`${result.code}: laudo concluído e hash gerado.`:action==='finalize'?`${result.code}: vistoria finalizada.`:`${result.code}: fluxo atualizado.`)}catch(cause){setError(cause instanceof ApiError?cause.detail:'Não foi possível atualizar a vistoria.')}finally{setSaving(false)}}
  async function openPdf(item:Inspection){try{const blob=await apiBlobRequest(`/inspections/${item.id}/document/pdf`);const url=URL.createObjectURL(blob);window.open(url,'_blank','noopener,noreferrer');setTimeout(()=>URL.revokeObjectURL(url),60000)}catch(cause){setError(cause instanceof ApiError?cause.detail:'Não foi possível abrir o laudo.')}}
  async function uploadPhoto(item:Inspection,environmentKey:string,itemKey:string,file:File){setSaving(true);setError('');try{const data=new FormData();data.append('environment_key',environmentKey);data.append('item_key',itemKey);data.append('file',file);await apiRequest<Inspection>(`/inspections/${item.id}/photos`,{method:'POST',body:data});await load();setSuccess('Foto anexada ao histórico da vistoria.')}catch(cause){setError(cause instanceof ApiError?cause.detail:'Não foi possível anexar a foto.')}finally{setSaving(false)}}
  async function contest(item:Inspection,environmentKey:string,itemKey:string,description:string){setSaving(true);setError('');try{await apiRequest(`/inspections/${item.id}/contestations`,{method:'POST',body:JSON.stringify({environment_key:environmentKey,item_key:itemKey,description})});await load();setSuccess('Contestação registrada dentro do prazo.')}catch(cause){setError(cause instanceof ApiError?cause.detail:'Não foi possível registrar a contestação.')}finally{setSaving(false)}}
  async function resolve(item:Inspection,contestationId:string,resolution:string){setSaving(true);setError('');try{await apiRequest(`/inspections/${item.id}/contestations/resolve`,{method:'POST',body:JSON.stringify({contestation_id:contestationId,resolution,change_summary:'Tratamento de contestação',environments:null})});await load();setSuccess('Contestação resolvida e novo hash do laudo gerado.')}catch(cause){setError(cause instanceof ApiError?cause.detail:'Não foi possível resolver a contestação.')}finally{setSaving(false)}}

  const selectedInspection = visibleItems.find(item=>item.id===expanded) ?? visibleItems[0] ?? null

  return <section className="workspace inspection-workspace"><div className="page-heading portfolio-heading"><div><span className="eyebrow">Operação · Entrada e saída</span><h1>Vistorias</h1><p>Laudos de entrada e saída versionados, com fotos e histórico vinculados ao contrato assinado.</p></div>{canManage&&<button className="button primary" type="button" onClick={openNew}><Plus size={15}/> Nova vistoria</button>}</div>
  <div className="dashboard-metrics inspection-metrics"><article className="panel metric-card"><span>Rascunhos</span><strong>{metrics.draft}</strong><small>em execução</small></article><article className="panel metric-card"><span>Laudos concluídos</span><strong>{metrics.ready}</strong><small>aptos para chaves</small></article><article className="panel metric-card"><span>Contestadas</span><strong>{metrics.contested}</strong><small>exigem tratativa</small></article><article className="panel metric-card"><span>Finalizadas</span><strong>{metrics.finalized}</strong><small>histórico encerrado</small></article></div>
  {error&&<div className="form-alert danger-alert">{error}</div>}{success&&<div className="form-alert success-alert">{success}</div>}
  {showForm&&<form className="panel inspection-form" onSubmit={save}><div className="panel-heading panel-heading-row"><div><span className="eyebrow">{editing?`Nova versão · ${editing.code}`:'Vistoria inicial'}</span><h2>Ambientes e itens</h2></div><ClipboardCheck size={20}/></div><div className="form-grid three-columns"><label className="field field-span-2"><span>Contrato de locação</span><select required disabled={Boolean(editing)} value={form.lease_contract_id} onChange={e=>setForm(c=>({...c,lease_contract_id:e.target.value}))}><option value="">Selecione...</option>{(editing?leases:eligibleLeases).map(lease=><option key={lease.id} value={lease.id}>{lease.code} · Imóvel #{lease.property_code} · {lease.tenants.map(t=>t.name).join(' / ')}</option>)}</select></label><label className="field"><span>Agendamento</span><input type="datetime-local" value={form.scheduled_at} onChange={e=>setForm(c=>({...c,scheduled_at:e.target.value}))}/></label><label className="field field-span-2"><span>Vistoriador</span><input value={form.inspector_name} onChange={e=>setForm(c=>({...c,inspector_name:e.target.value}))}/></label><label className="field"><span>Observações gerais</span><input value={form.notes} onChange={e=>setForm(c=>({...c,notes:e.target.value}))}/></label>{editing&&<label className="field field-span-3"><span>Resumo da nova versão</span><input required minLength={3} value={changeSummary} onChange={e=>setChangeSummary(e.target.value)}/></label>}</div>
  <div className="inspection-environments">{form.environments.map((env,envIndex)=><article className="inspection-environment" key={env.key}><div className="inspection-environment-heading"><input aria-label="Nome do ambiente" value={env.name} onChange={e=>updateEnvironment(envIndex,{name:e.target.value})}/><button className="icon-button" type="button" aria-label="Remover ambiente" onClick={()=>setForm(c=>({...c,environments:c.environments.filter((_,i)=>i!==envIndex)}))}><Trash2 size={14}/></button></div>{env.items.map((entry,itemIndex)=><div className="inspection-item-editor" key={entry.key}><input value={entry.label} onChange={e=>updateItem(envIndex,itemIndex,{label:e.target.value})}/><select value={entry.condition} onChange={e=>updateItem(envIndex,itemIndex,{condition:e.target.value as ItemCondition})}>{Object.entries(conditionLabels).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select><input placeholder="Observações do item" value={entry.notes??''} onChange={e=>updateItem(envIndex,itemIndex,{notes:e.target.value||null})}/>{editing&&<label className="inspection-photo-button"><Camera size={14}/> Foto<input type="file" accept="image/jpeg,image/png,image/webp" onChange={e=>{const file=e.target.files?.[0];if(file)void uploadPhoto(editing,env.key,entry.key,file)}}/></label>}<button className="icon-button" type="button" onClick={()=>updateEnvironment(envIndex,{items:env.items.filter((_,i)=>i!==itemIndex)})}><Trash2 size={14}/></button>{entry.photos.length>0&&<small>{entry.photos.length} foto(s) arquivada(s)</small>}</div>)}<button className="button secondary compact" type="button" onClick={()=>updateEnvironment(envIndex,{items:[...env.items,{key:key('item'),label:'Novo item',condition:'good',notes:null,photos:[]}]})}><Plus size={13}/> Item</button></article>)}</div><button className="button secondary" type="button" onClick={()=>setForm(c=>({...c,environments:[...c.environments,{key:key('amb'),name:'Novo ambiente',notes:null,items:[{key:key('item'),label:'Condição geral',condition:'good',notes:null,photos:[]}]}]}))}><Plus size={14}/> Ambiente</button><div className="form-actions"><button className="button secondary" type="button" onClick={()=>setShowForm(false)}>Cancelar</button><button className="button primary" disabled={saving} type="submit">{saving?'Salvando...':editing?'Salvar nova versão':'Criar vistoria'}</button></div></form>}
  <div className="panel inspection-ops-toolbar"><label><span>Buscar</span><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Código, imóvel ou locatário..."/></label><select aria-label="Filtrar por status" value={statusFilter} onChange={e=>setStatusFilter(e.target.value as 'all'|Inspection['status'])}><option value="all">Todos os status</option>{Object.entries(statusLabels).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select><select aria-label="Filtrar por tipo" value={typeFilter} onChange={e=>setTypeFilter(e.target.value as 'all'|Inspection['inspection_type'])}><option value="all">Entrada e saída</option><option value="initial">Entrada</option><option value="final">Saída</option></select></div>
  {loading?<article className="panel settings-loading">Carregando vistorias...</article>:items.length===0?<article className="panel portfolio-empty"><ClipboardCheck size={26}/><strong>Nenhuma vistoria inicial ainda.</strong><span>Ela será liberada quando existir uma locação assinada e arquivada.</span></article>:visibleItems.length===0?<article className="panel portfolio-empty"><ClipboardCheck size={24}/><strong>Nenhuma vistoria com esses filtros.</strong><span>Ajuste status, tipo ou busca para ampliar a fila.</span></article>:<div className="inspection-master-detail">
    <aside className="panel inspection-master-list">
      <div className="inspection-master-head"><div><span className="eyebrow">Fila operacional</span><strong>{visibleItems.length} de {items.length}</strong></div></div>
      <div className="inspection-master-scroll">{visibleItems.map(item=><button type="button" className={`inspection-master-row ${selectedInspection?.id===item.id?'active':''}`} key={item.id} onClick={()=>setExpanded(item.id)}>
        <div className="inspection-master-row-top"><span>{item.inspection_type==='final'?'Saída':'Entrada'} · {item.code}</span><i className={`status-badge ${item.status==='finalized'?'success':item.status==='contested'?'danger':item.status==='ready'?'warning':'neutral'}`}>{statusLabels[item.status]}</i></div>
        <strong>{item.lease_code} · Imóvel #{item.property_code}</strong>
        <small>{addressLine(item.property_address)}</small>
        <em>{item.tenants.map(t=>t.name).join(' / ')||'Sem locatário vinculado'}</em>
        <div className="inspection-master-row-meta"><span>{item.key_handover?'Chaves entregues':'Chaves pendentes'}</span><span className={item.contest_deadline?'attention':''}>{item.contest_deadline?`Prazo ${new Date(item.contest_deadline).toLocaleDateString('pt-BR')}`:'Sem prazo ativo'}</span><span className={item.contestations.some(c=>!c.resolved_at)?'attention':''}>{item.contestations.some(c=>!c.resolved_at)?`${item.contestations.filter(c=>!c.resolved_at).length} contestação(ões)`:'Sem pendências'}</span></div>
      </button>)}</div>
    </aside>
    {selectedInspection&&<section className="panel inspection-detail-workspace">
      <div className="inspection-detail-header"><div><span className="eyebrow">{selectedInspection.inspection_type==='final'?'Vistoria de saída':'Vistoria de entrada'}</span><h2>{selectedInspection.code}</h2><p>{selectedInspection.lease_code} · Imóvel #{selectedInspection.property_code} · {addressLine(selectedInspection.property_address)}</p><div className="inspection-detail-context"><span>{selectedInspection.tenants.map(t=>t.name).join(' / ')||'Sem locatário'}</span><span>{selectedInspection.inspector_name||'Vistoriador não informado'}</span><span>Versão {selectedInspection.current_version}</span></div></div><i className={`status-badge ${selectedInspection.status==='finalized'?'success':selectedInspection.status==='contested'?'danger':selectedInspection.status==='ready'?'warning':'neutral'}`}>{statusLabels[selectedInspection.status]}</i></div>
      <div className="inspection-detail-kpis"><div><FileText size={14}/><span>Laudo</span><strong>{selectedInspection.report_version?`v${selectedInspection.report_version}`:'—'}</strong></div><div><KeyRound size={14}/><span>Chaves</span><strong>{selectedInspection.key_handover?'Entregues':'Pendentes'}</strong></div><div><ShieldCheck size={14}/><span>Prazo</span><strong>{selectedInspection.contest_deadline?new Date(selectedInspection.contest_deadline).toLocaleDateString('pt-BR'):'Não iniciado'}</strong></div><div><ShieldCheck size={14}/><span>Contestações</span><strong>{selectedInspection.contestations.filter(c=>!c.resolved_at).length} aberta(s)</strong></div></div>
      <div className="inspection-detail-actions">{selectedInspection.status==='draft'&&canManage&&<><button className="button secondary" onClick={()=>openEdit(selectedInspection)}>Editar</button><button className="button primary" disabled={saving} onClick={()=>void workflow(selectedInspection,'complete')}><CheckCircle2 size={14}/> Concluir laudo</button></>}{selectedInspection.status==='ready'&&canManage&&!selectedInspection.key_handover&&<><button className="button secondary" onClick={()=>void workflow(selectedInspection,'return_draft')}><RotateCcw size={14}/> Rascunho</button><button className="button primary" onClick={()=>setHandoverFor(selectedInspection.id)}><KeyRound size={14}/> Entregar chaves</button></>}{selectedInspection.status==='ready'&&selectedInspection.key_handover&&canManage&&<button className="button primary" onClick={()=>void workflow(selectedInspection,'finalize')}><ShieldCheck size={14}/> Finalizar</button>}{selectedInspection.report_hash&&<button className="button secondary" onClick={()=>void openPdf(selectedInspection)}><FileText size={14}/> Abrir laudo</button>}</div>
      {handoverFor===selectedInspection.id&&<KeyHandoverForm item={selectedInspection} onCancel={()=>setHandoverFor(null)} onSaved={async()=>{setHandoverFor(null);await load();setSuccess('Entrega de chaves registrada. O prazo de contestação começou automaticamente.')}}/>}
      <InspectionDetails item={selectedInspection} canManage={canManage} saving={saving} onContest={contest} onResolve={resolve}/>
    </section>}
  </div>}</section>
}

function KeyHandoverForm({item,onCancel,onSaved}:{item:Inspection;onCancel:()=>void;onSaved:()=>Promise<void>}){const [recipient,setRecipient]=useState(item.tenants[0]?.name??'');const [document,setDocument]=useState('');const [when,setWhen]=useState(localInput(new Date().toISOString()));const [keyLabel,setKeyLabel]=useState('Porta principal');const [quantity,setQuantity]=useState(2);const [water,setWater]=useState('');const [electricity,setElectricity]=useState('');const [error,setError]=useState('');async function submit(e:FormEvent){e.preventDefault();setError('');try{await apiRequest(`/inspections/${item.id}/keys`,{method:'POST',body:JSON.stringify({handed_over_at:new Date(when).toISOString(),recipient_name:recipient,recipient_document:document||null,keys:[{label:keyLabel,quantity,notes:null}],meter_readings:{water:water||null,electricity:electricity||null},notes:null})});await onSaved()}catch(cause){setError(cause instanceof ApiError?cause.detail:'Não foi possível registrar as chaves.')}}return <form className="inspection-handover" onSubmit={submit}><div><span className="eyebrow">Entrega de chaves</span><h3>Registro imutável</h3></div>{error&&<div className="form-alert danger-alert">{error}</div>}<div className="form-grid three-columns"><label className="field"><span>Recebedor</span><input required value={recipient} onChange={e=>setRecipient(e.target.value)}/></label><label className="field"><span>CPF/CNPJ</span><input value={document} onChange={e=>setDocument(e.target.value)}/></label><label className="field"><span>Data e hora</span><input required type="datetime-local" value={when} onChange={e=>setWhen(e.target.value)}/></label><label className="field"><span>Tipo de chave</span><input required value={keyLabel} onChange={e=>setKeyLabel(e.target.value)}/></label><label className="field"><span>Quantidade</span><input min={1} type="number" value={quantity} onChange={e=>setQuantity(Number(e.target.value))}/></label><label className="field"><span>Leitura água</span><input value={water} onChange={e=>setWater(e.target.value)}/></label><label className="field"><span>Leitura energia</span><input value={electricity} onChange={e=>setElectricity(e.target.value)}/></label></div><div className="form-actions"><button className="button secondary" type="button" onClick={onCancel}>Cancelar</button><button className="button primary" type="submit">Confirmar entrega</button></div></form>}

function InspectionDetails({item,canManage,saving,onContest,onResolve}:{item:Inspection;canManage:boolean;saving:boolean;onContest:(i:Inspection,e:string,k:string,d:string)=>Promise<void>;onResolve:(i:Inspection,c:string,r:string)=>Promise<void>}){const [environment,setEnvironment]=useState(item.environments[0]?.key??'');const environmentObj=item.environments.find(e=>e.key===environment);const [entry,setEntry]=useState(environmentObj?.items[0]?.key??'');const [description,setDescription]=useState('');const [resolutions,setResolutions]=useState<Record<string,string>>({});return <div className="inspection-expanded"><div className="inspection-detail-panel"><span className="eyebrow">Ambientes</span>{item.environments.map(env=><div className="inspection-detail-environment" key={env.key}><strong>{env.name}</strong>{env.items.map(i=><span key={i.key}>{i.label} · {conditionLabels[i.condition]} · {i.photos.length} foto(s){i.notes?` · ${i.notes}`:''}</span>)}</div>)}</div><div className="inspection-detail-panel"><span className="eyebrow">Versões</span>{item.versions.slice().reverse().map(v=><div className="contract-version-row" key={v.version_number}><strong>v{v.version_number}</strong><span>{v.change_summary||'Sem resumo'}</span><small>{new Date(v.created_at).toLocaleString('pt-BR')}</small></div>)}</div><div className="inspection-detail-panel"><span className="eyebrow">Contestações</span>{item.contestations.map(c=><div className="inspection-contestation" key={c.id}><strong>{c.environment_key} / {c.item_key}</strong><span>{c.description}</span>{c.resolved_at?<small>Resolvida: {c.resolution}</small>:canManage&&<div className="inspection-inline-action"><input placeholder="Tratativa" value={resolutions[c.id]??''} onChange={e=>setResolutions(r=>({...r,[c.id]:e.target.value}))}/><button className="button secondary compact" disabled={saving||!(resolutions[c.id]??'').trim()} onClick={()=>void onResolve(item,c.id,resolutions[c.id])}>Resolver</button></div>}</div>)}{canManage&&item.key_handover&&item.status!=='finalized'&&<div className="inspection-contest-form"><select value={environment} onChange={e=>{setEnvironment(e.target.value);const env=item.environments.find(x=>x.key===e.target.value);setEntry(env?.items[0]?.key??'')}}>{item.environments.map(e=><option value={e.key} key={e.key}>{e.name}</option>)}</select><select value={entry} onChange={e=>setEntry(e.target.value)}>{(item.environments.find(e=>e.key===environment)?.items??[]).map(i=><option value={i.key} key={i.key}>{i.label}</option>)}</select><input placeholder="Descrição da contestação" value={description} onChange={e=>setDescription(e.target.value)}/><button className="button secondary compact" disabled={saving||description.trim().length<3} onClick={()=>{void onContest(item,environment,entry,description);setDescription('')}}>Registrar</button></div>}{item.contestations.length===0&&<span className="muted-copy">Nenhuma contestação registrada.</span>}</div></div>}
